### ISSUE TITLE
Passes are registered even if no Race is running

### ISSUE THREAD

**Issue by Klaus-Michael** [RotorHazard/RotorHazard#104]
Since the changed on the 20th the system continues to register passes after a race was stopped. Those passes are saved to the database when pressing save laps.

**Comment by HazardCreative** [comment]
Steps to reproduce? I'm not seeing the issue.

**Comment by Klaus-Michael** [comment]
I had a look again,
After Clearing ALL the caches of my Browser the issue is no longer visible. 
I thought I did this before raising the issue, but seems doing it again solved it.

**Comment by HazardCreative** [comment]
Actaully, I saw this happening at yesterday's race. There must be some condition that allows it. Please provide information if anyone can create steps to reproduce.

**Comment by BoLtWD** [comment]
I had the same when racing. After a race had finished and stopped if a pilot did a bit of free flying with race stopped the timer would resister a beep first pass then a pass each time the quad passed the timer.
