### ISSUE TITLE
Are profiles still relevant?

### ISSUE THREAD

**Issue by HazardCreative** [RotorHazard/RotorHazard#106]
The "profile" section is a holdover from Delta5 and contains tuning values and frequency settings. The D5 also stored some race format data (which now exists in Race Formats) and before 2.0 RotorHazard stored the filter ratio here (which is no longer needed).

I take my timer to very different venues and am not using profiles at all. Is this particular feature still relevant for anyone? Should it be expanded to include other settings, or removed entirely?

**Comment by pulquero** [comment]
I think ultimately it should be removed because hopefully we can advance to a stage where we have live 'auto calibration'. If profiles are still needed in the meantime then maybe the settings can be moved to config.json, or environment vars or something which is less burden than having a UI.

**Comment by BoLtWD** [comment]
Like you not relay used them.
