### ISSUE TITLE
No module named neopixel - Make readme clearer to install LED support even if not being used?

### ISSUE THREAD

**Issue by Ryanf55** [RotorHazard/RotorHazard#107]
Hello,

Just ran through the install on a fresh Rasberry Pi. It doesn't come with the neopixel library by default and there is no neopixel version specified in src/requirements.txt.

I also tried `sudo pip install neopixel`

Being able to disable it in configuration would be nice.

```
 ~/RotorHazard/src/server $ python server.py

Traceback (most recent call last):
  File "server.py", line 28, in <module>
    from neopixel import *
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
ImportError: No module named neopixel
```

**Comment by HazardCreative** [comment]
The proper solution is to make the module optional and only try to use it if it exists.

**Comment by pulquero** [comment]
Can you confirm that you are using master or the last release. In master, it should be optional - else I wouldn't be able to run it on windows.

**Comment by pulquero** [comment]
In fact, it can't be master since L28 is not
from neopixel import *

**Comment by Ryanf55** [comment]
After investigating, it is not master, rather version 1.0.0 when I first cloned the repo. This bug has already been fixed. 

I will modify the related pull request to update documentation that the LED's are optional.
