### ISSUE TITLE
Warn if node API is too high

### ISSUE THREAD

**Issue by HazardCreative** [RotorHazard/RotorHazard#110]
Newer nodes are generally not compatible with older servers. This should be easy to check for and warn in the startup log.

**Comment by Ryanf55** [comment]
Where could I find the info for the API limits at each server version? I'm happy to work on this one.

**Comment by HazardCreative** [comment]
Oh, thank you! I'm actually sitting on an unpushed commit for this one.

**Comment by Ryanf55** [comment]
Ah. Figured I'd ask before embarking because it seemed a fairly quick one to fix:)
