### ISSUE TITLE
Results are calculated on first connection

### ISSUE THREAD

**Issue by HazardCreative** [RotorHazard/RotorHazard#112]
This significantly slows down the ability to use the timer immediately after the first connection if the database has saved races in it. Results should only be calculated when someone visits the results page to request them.

**Comment by BoLtWD** [comment]
If this significantly slows down the ability to use the timer then should accessing this data during a race be restricted as this may effect the race being run?

**Comment by HazardCreative** [comment]
I was thinking it should be throttled instead of restricted, but I've opened a separate issue for that: #113
