### ISSUE TITLE
Results calculations are slow

### ISSUE THREAD

**Issue by HazardCreative** [RotorHazard/RotorHazard#113]
Results calculations should be optimized. Also, broken into separate threads so processing of other items isn't completely stalled.

**Comment by pulquero** [comment]
I think the main problem here is the use of database calls inside nested loops.

**Comment by HazardCreative** [comment]
I would like to clean up this kind of thing throughout. I'm not an expert, but methods/structuring like this always seemed slow and error-prone to me. Perhaps worth opening a separate issue for general cleanup tasks?
https://github.com/RotorHazard/RotorHazard/blob/master/src/server/server.py#L2057

**Comment by HazardCreative** [comment]
I would welcome optimization of the calc_leaderboard function with the database changes you've discussed here. However, with the introduction of more atomic caching, the results generation time is significantly improved and no longer a real issue.
