### ISSUE TITLE
raising the exitat value above 127 results in a interface error

### ISSUE THREAD

**Issue by Klaus-Michael** [RotorHazard/RotorHazard#114]
When raising the exitat value to 128  or above the value is not saved and an interface error is raised:

Node exit-at set: Node 1 Level 127
Interface: Retry (checksum) in read_block:  addr=8 offs=50 size=1 retry=2 ts=-38416999.1562
Interface: Retry (checksum) in read_block:  addr=8 offs=50 size=1 retry=3 ts=-38416921.8548
Interface: Retry (checksum) in read_block:  addr=8 offs=50 size=1 retry=4 ts=-38416844.4929
Interface: Retry (checksum) limit reached in read_block:  addr=8 offs=50 size=1 retry=5 ts=-38416767.2282
Interface: Value Not Set (1): 114/128/<Node.Node instance at 0x757bcd78>
Interface: Retry (checksum) in read_block:  addr=8 offs=50 size=1 retry=2 ts=-38416536.976
Interface: Retry (checksum) in read_block:  addr=8 offs=50 size=1 retry=3 ts=-38416459.8767
Interface: Retry (checksum) in read_block:  addr=8 offs=50 size=1 retry=4 ts=-38416382.4963
Interface: Retry (checksum) limit reached in read_block:  addr=8 offs=50 size=1 retry=5 ts=-38416305.0248
Interface: Value Not Set (2): 114/128/<Node.Node instance at 0x757bcd78>
Interface: Retry (checksum) in read_block:  addr=8 offs=50 size=1 retry=2 ts=-38416073.756
Interface: Retry (checksum) in read_block:  addr=8 offs=50 size=1 retry=3 ts=-38415996.5385
Interface: Retry (checksum) in read_block:  addr=8 offs=50 size=1 retry=4 ts=-38415919.3457
Interface: Retry (checksum) limit reached in read_block:  addr=8 offs=50 size=1 retry=5 ts=-38415842.4093
Interface: Value Not Set (3): 114/128/<Node.Node instance at 0x757bcd78>
Interface: Retry (checksum) in read_block:  addr=8 offs=50 size=1 retry=2 ts=-38415611.3179
Interface: Retry (checksum) in read_block:  addr=8 offs=50 size=1 retry=3 ts=-38415534.3142
Interface: Retry (checksum) in read_block:  addr=8 offs=50 size=1 retry=4 ts=-38415457.3845
Interface: Retry (checksum) limit reached in read_block:  addr=8 offs=50 size=1 retry=5 ts=-38415380.0908
Interface: Value Not Set (4): 114/128/<Node.Node instance at 0x757bcd78>
Interface: Retry (checksum) in read_block:  addr=8 offs=50 size=1 retry=2 ts=-38415148.911
Interface: Retry (checksum) in read_block:  addr=8 offs=50 size=1 retry=3 ts=-38415071.6819
Interface: Retry (checksum) in read_block:  addr=8 offs=50 size=1 retry=4 ts=-38414991.2551
Interface: Retry (checksum) limit reached in read_block:  addr=8 offs=50 size=1 retry=5 ts=-38414913.9297
Interface: Value Not Set (5): 114/128/<Node.Node instance at 0x757bcd78>
Node exit-at set: Node 1 Level 128

**Comment by Klaus-Michael** [comment]
@pulquero  something for you?

**Comment by pulquero** [comment]
This looks like a 2's-complement problem.
