### ISSUE TITLE
saving a race with new EnterAt and ExitAt values in the Marshal page does not save those values to the DB

### ISSUE THREAD

**Issue by Klaus-Michael** [RotorHazard/RotorHazard#118]
When recalculating a round on the Marshal Page with new EnterAt and ExitAt values those values are not saved in the DB for this race when committing the recalculated race.
When loading the race again the orginal EnterAt and ExitAt values are loaded.
While it might be interesting to restore the original settings it would be more intuitive to get the values that were used for the calculation of the saved data. Maybe add a additional option to restore the Original Node Data.

**Comment by HazardCreative** [comment]
This was intended but I guess it somehow got passed over in the implementation. I don't think saving the original calibration is necessary; it's impossible to make lap data unrecoverable just by changing enter/exit points.
