### ISSUE TITLE
Alert Box is blocking Site Navigation

### ISSUE THREAD

**Issue by Klaus-Michael** [RotorHazard/RotorHazard#120]
The alert Box on top of the screen is blocking the site navigation buttons.
I would prefer a box that pops up without blocking anything and preferable that does not need to be confirmed by pressing any button.

**Comment by HazardCreative** [comment]
I agree there's room for improvement here, but we need to approach it differently. Pushing the nav up and down when the items are opened and dismissed would be disruptive. Automatic/timed dismissal is an accessibility issue, and I want to conform to a minimum standard of WCAG 2.1 AA. Reserving space for a notice is wasteful most of the time and notices can still overflow the space.

One silent improvement in this version is that the ESC key will dismiss the active notice, but that doesn't help mobile users.

A possibility might be to fix the notices to the bottom of the window instead, but that's less commonly seen in UI. I'm open to other suggestions.

**Comment by Klaus-Michael** [comment]
Moving the alert to the bottom would work as it would not disrupt the usage of the page itself. Might be worth a try.

**Comment by HazardCreative** [comment]
Let's give this a try and see if we like it. If so it may fix both this and #119. It's minor enough that I'm comfortable slotting it into the 2.0 release.

**Comment by Klaus-Michael** [comment]
sounds good
