### ISSUE TITLE
limits for warnings in the Tuning Node sections seems to be still set for the "old" RSSI Range

### ISSUE THREAD

**Issue by Klaus-Michael** [RotorHazard/RotorHazard#127]
it looks as if the warnings in the Tuning Node Sections are still scaled to be valid for the old 255 Style RSSI Reading. With the Reduction down to 128max all my nodes are basically showing the warning as I'm typically around 15 between enter and exit (which seems to work OK)

**Comment by frizzle101101** [comment]
Can someone explain why ot is 128 max now or when did that change
