### ISSUE TITLE
Javascript errors on Raspberry Pi GUI

### ISSUE THREAD

**Issue by HazardCreative** [RotorHazard/RotorHazard#130]
A few users have tried running on Linux and failed. Since I don't have a Linux system (I don't set up the pi with a desktop), I can't debug the issue further and find out if it's fixable or inherent to one of the libraries.

**Comment by ethomas997** [comment]
Do you mean running the simulator/mock setup?  Or do you mean running the UI in a browser on a Linux system?  Or the UI in a browser on the Pi itself?  Any particular browser?

**Comment by HazardCreative** [comment]
Yes, I should have clarified. Front-end UI in a Linux desktop. Reports in both Chrome and FF. Behavior is that the HTML loads but the sockets do not. Attached is the only screen capture I have of the JS console. Reported in 1.1 as well.

![65308287_10206251012389952_4720960818345148416_n](https://user-images.githubusercontent.com/7169527/60478513-eda76c80-9c50-11e9-835a-d99c9b209397.jpg)

**Comment by Ryanf55** [comment]
Tag me if you need help testing code. I originally ran into the issue.

**Comment by Klaus-Michael** [comment]
I gave it a try on a fresh ubuntu LTS 18.04.2 installation running in a virtual machine.
The GUI showed no problems. I tried Firefox and Chrome.
For Firefox the MP3 tones did not work but the syntetic worked fine.
For Chrome it was the other way around, MP3 worked.
Voice Callout worked on both.

**Comment by HazardCreative** [comment]
@Ryanf55 what can you tell us about your system setup?

**Comment by ethomas997** [comment]
I tried running via a browser on the GUI-desktop of the Pi itself, but it failed with similar errors (Firefox and Chromium).

Running it via Firefox on Fedora 29 Linux seemed to work OK.

**Comment by HazardCreative** [comment]
@Ryanf55 is this still an issue?

**Comment by HazardCreative** [comment]
No updates reported and this doesn't seem to be bothering anyone.
