### ISSUE TITLE
can not add new raceformats

### ISSUE THREAD

**Issue by robschii** [RotorHazard/RotorHazard#137]
v2.0

can not add new raceformats
i can only delet ist

i need a race format for beginners with a higher dead time
and than i raceformat with lower deadtime for the faster guys

**Comment by HazardCreative** [comment]
I do not experience this issue. What steps can be used to reproduce it?

FYI, you cannot add blank formats. Choose one most like what you want and duplicate it. Then, in the new, copied format, change any or all of the values.

**Comment by robschii** [comment]
okay thanks

**Comment by robschii** [comment]
please open this issue again

i can not duplicate or copy any race format.   i have delet non used formats, now i have only one single format. races are delet. i chose the single format and press duplicate but i get no new format in the list

**Comment by HazardCreative** [comment]
Are you trying to duplicate an item that has already been duplicated once? It seems that the server can't add more if it tries to name the new copy the same as one that already exists. Otherwise, I still cannot reproduce this issue.
