### ISSUE TITLE
need to change pilots frequenzy when a problem exist

### ISSUE THREAD

**Issue by robschii** [RotorHazard/RotorHazard#138]
v2.0 

need to change pilots frequenzy when a problem exist without delet any race

**Comment by HazardCreative** [comment]
What is your issue? This is possible from the frequency setup panel on the Settings page. Heats, classes, and formats can become locked as you use them, but the frequency setup does not.

**Comment by robschii** [comment]
when i have done one race for one group  i can not change the  frequency for one pilot

**Comment by HazardCreative** [comment]
I'm not experiencing this. What steps will reproduce your issue?

**Comment by HazardCreative** [comment]
You cannot assign one pilot a specific frequency that will follow it as the heat changes. You may, however, change the frequency setup for the node any time you would like.
