### ISSUE TITLE
need to tunne the node for each pilot in several heats

### ISSUE THREAD

**Issue by robschii** [RotorHazard/RotorHazard#139]
when i have to groups or more, each pilot has a significant rssi history. when i tune for pilot a in group a, so he is tracked perfectly the option exists that this tune is not good for  pilot a in group b

**Comment by HazardCreative** [comment]
Typically you can find a calibration that works for all pilots using a given node as long as you do not change its frequency. You should first check that everyone's equipment is running properly. If one pilot is reading much higher or lower than others, that pilot may cause or experience video problems on the course.

However, if you absolutely must switch, you can use the Marshal page. Load a previous race with the pilot on the same node, then write the stored values to the node from that page. Follow the same process for each pilot that must switch.

**Comment by HazardCreative** [comment]
This is the same issue as being discussed in #151. While technically that one would be the duplicate, it has more a useful comment thread to keep as open.
