### ISSUE TITLE
add a "beep in first pass" option

### ISSUE THREAD

**Issue by ScorpionTDL** [RotorHazard/RotorHazard#14]
feature request to add a "beep on first pass" 
a short indication beep that the first pass was recorded is very usefull when running training sessions and the "administrator" of the system is participating.

**Comment by ethomas997** [comment]
Have you tried enabling the Indicator Beeps?  That can give you beeps on all passes through the start/finish gate.

**Comment by ScorpionTDL** [comment]
Seems github did not accept my earlier comment from yesterday :-(

the indicator beeps would not be limited to the first pass. I just would like to have a indication that the first pass was registered where no voice announcement happens.

**Comment by Klaus-Michael** [comment]
I added a implementation for this in my fork.
The exact sound of the tone might need to be adapted if you were following a specific pattern. I just chose one that sounded OK.
