### ISSUE TITLE
First staging tone sounds too closely to second tone

### ISSUE THREAD

**Issue by HazardCreative** [RotorHazard/RotorHazard#145]
Sometimes, the first two staging tones sound closely together. The rest of the tones and the actual start are then spaced normally. Could be related to #140.

**Comment by HazardCreative** [comment]
Has this been addressed by other changes? Please comment if you experience it.

**Comment by HazardCreative** [comment]
I have run events recently without this issue appearing. Reopen if new instances occur.

**Comment by szafranski** [comment]
I had it few times.

**Comment by HazardCreative** [comment]
Running latest dev code or an older release?

**Comment by szafranski** [comment]
202 stable

W dniu pt., 31.01.2020 o 04:10 Hazard Creative <notifications@github.com>
napisał(a):

**Comment by szafranski** [comment]
202 stable

**Comment by HazardCreative** [comment]
Yes, the 2.0.2 release will continue to exhibit the bug. A fix was attempted for the current development code to be released as 2.1.
