### ISSUE TITLE
Unneeded data recorded to history

### ISSUE THREAD

**Issue by HazardCreative** [RotorHazard/RotorHazard#148]
The history can sometimes record the same value three times in a row.

121: 48
122: 49
123: 49
124: 49
125: 51

While it is necessary to record the beginning an end of a peak, times in between them with the same value are never used. These do not need recorded.

Rather than search for these values to delete them, it would be better to understand why they can occur to begin with.

**Comment by pulquero** [comment]
The tests should help with this.

**Comment by HazardCreative** [comment]
Yep! Mostly just getting my various thoughts down into issues to investigate later when I'm able.

**Comment by ethomas997** [comment]
Fixed by https://github.com/RotorHazard/RotorHazard/commit/d67822752079c25c9756b333ea3488d0097259ee
