### ISSUE TITLE
Per-pilot LED signal colors

### ISSUE THREAD

**Issue by HazardCreative** [RotorHazard/RotorHazard#149]
Allow the LEDs to change based on pilot colors. When quads are set up with LEDs, this will allow them to match and improve the spectator experience. Also needed for team racing.

**Comment by BoLtWD** [comment]
Nicely thought out option, never liked the fixed colours per channels, is would be nice to designate colours to ether pilots or starting places.

**Comment by ethomas997** [comment]
I'm thinking that a way to do this will be to have color-selection options in the 'Heats' section on the 'Settings' page, so the color for each node in a given heat can be set or changed.

**Comment by HazardCreative** [comment]
I don't think that fully addresses this enhancement. Some groups want to assign a color to each pilot and have those colors follow them when they change channels. For example, quads may have this color of LED installed and not configurable.

Your per-heat option has some merit as compared to the current per-node system (which I always envisioned would remain as a selectable option). Maybe all three strategies should be selectable?

**Comment by ethomas997** [comment]
We could give each pilot entry a "preferred color" field that defaults to none.  When generating heats, pick these colors when available.

**Comment by CerberusVelvet** [comment]
There is a standard set of colours allocated by vtx channel in betaflight

`
Frequency range | Default color | Color index
<= 5672 | White | 1
> 5672 <= 5711 | Red | 2
> 5711 <= 5750 | Orange | 3
> 5750 <= 5789 | Yellow | 4
> 5789 <= 5829 | Green | 6
> 5829 <= 5867 | Blue | 10
> 5867 <= 5906 | Dark violet | 11
> 5906 | Deep pink | 13
`

Could RH use the frequency set on the pilots node to dictate the LED colour to match the colour designated by the vtx frequency as per betaflight?
