### ISSUE TITLE
results page collapse all tabs on refresh

### ISSUE THREAD

**Issue by ScorpionTDL** [RotorHazard/RotorHazard#15]
All tabs on the result page are automatically collapsed if the page is refreshed or new data is added due to a "save laps" event

**Comment by HazardCreative** [comment]
Python doesn't know the current state of the UI when the page is generated, and the front-end just replaces it. I'm considering rebuilding the front-end to keep a local copy of the database. This will significantly improve load times for the results page and should give us a simple method to check for whether a panel is open before its data is replaced.

**Comment by ScorpionTDL** [comment]
Yea sure the server does not have this information. But its the javascript on the client side that does the actual display. So either this needs to get the state prior to deleting the old content. Or the content could be split up into the different panels and you don't delete the complete page but just the content of the panel during the refresh.

having a local copy of the database will remove load from the pi for sure, but on the other hand it will add a lot of complexity.

**Comment by HazardCreative** [comment]
Yes, it will add complexity—but eliminating the slowdown in generating a results page when there are lot of saved races may be worth it. It's also a step toward making results available offline when a pilot goes home after an event. If we make that change, we'd be rewriting the logic for all of this at that time.

If we give up on offline—which is going to be a tricky one given the restrictions on when a browser will load a Service Worker—then another option is to have the pi cache the results when they are generated and serve those. Then we'd want JS to save and restore the 'opened' state of the panels as you suggest.

Either way, I'd like to determine the feasibility of offline mode before diving in so as to not duplicate effort.
