### ISSUE TITLE
opening the Marshal page resets Client Settings to default

### ISSUE THREAD

**Issue by Klaus-Michael** [RotorHazard/RotorHazard#153]
Opening the Marshal page resets client setting (audio etc..) to default.

steps to reproduce:
go to a page with client settings (Run Race for example)
Change Audio Settings
Open the Marshal Page
go back to the previous page and validate the Audio settings

**Comment by HazardCreative** [comment]
Good catch. I think this explains various things I was seeing but couldn't figure out where they were coming from. I'll probably do a point release with this fix.
