### ISSUE TITLE
Voltage Warning

### ISSUE THREAD

**Issue by BoLtWD** [RotorHazard/RotorHazard#155]
Now we have support for the INA219 device is it possible to have some kind of pop up warning you can set to say when the voltage is getting low?

**Comment by HazardCreative** [comment]
Yep, this is planned.

**Comment by BoLtWD** [comment]
I would love to see an alarm implemented or/and a bar of some kind for battery level indication referenced to min max levels set.

**Comment by BoLtWD** [comment]
Is this still an option being looked into, I am sure it would help race directors to know if there power unit powering the timer is going to last one more race.

**Comment by HazardCreative** [comment]
Yes, it's still something I'd like to have. I didn't personally have any additional sensor hardware until this month so I couldn't work on it myself.

**Comment by ethomas997** [comment]
I also planning on having voltage monitoring and alarming via S32_BPill board (still needs to be implemented in the S32_BPill node code).

**Comment by BoLtWD** [comment]
Would this also be back compatible with the current arduino setup as this is something I have?

**Comment by ethomas997** [comment]
I expect we'll look to implement something that is compatible with either type of hardware.

**Comment by BoLtWD** [comment]
Fantastic, thank you

**Comment by frizzle101101** [comment]
so it seems like this never came along fully?

**Comment by HazardCreative** [comment]
Nothing yet. So many things we can potentially work on, but only our free time available to do it.

**Comment by frizzle101101** [comment]
my plan is to just have a voltage divider on node one for a buzzer output for now so I can get my timer working for the season,... the gaol will eventually send the info up the pipe to the server i guess right?

**Comment by HazardCreative** [comment]
Plugin https://github.com/Aaronsss/RH-sensor-monitor exists.
