### ISSUE TITLE
Frequency Scanner mode

### ISSUE THREAD

**Issue by HazardCreative** [RotorHazard/RotorHazard#156]
Provide a mode that uses the receivers to scan the band and report back signal strength at each frequency.

**Comment by BoLtWD** [comment]
Basically a band scanner, that could be something useful

**Comment by ethomas997** [comment]
I implemented a band scanner in my [ArudVidRx project](http://www.etheli.com/ArduVidRx/index.html#app); it's a nice tool to have.  I could see doing something similar in the node code.  I don't know what we'd use to show the graph (essentially a constantly-refreshing bar chart) in the GUI.  On Android I used the [MPAndroidChart](https://github.com/PhilJay/MPAndroidChart) library.  Do we have a good way to generate the graph (bar chart) in the web GUI?
