### ISSUE TITLE
Add textboxes on the runpage to be spoken out 

### ISSUE THREAD

**Issue by KennyVDSypt** [RotorHazard/RotorHazard#161]
While running races it could be handy to have empty textboxes on the runpage. Racedirectors could type in text and have the timer read/speak it through the speaker. For example: This race is over, next pilots please; Judges please; Please hurry up;...

**Comment by pulquero** [comment]
Combo box with preconfigured list of phrases.

**Comment by HazardCreative** [comment]
If there were some preconfigured phrases, what would they be?
