### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by BoLtWD** [RotorHazard/RotorHazard#167]
Did a race at the track today, this issue is a pain but you can get round it by pressing ctrl + F5  after each page loads. The issue is the Data on the pages wont load in google Chrome, opera browser but on in Microsoft Microsoft Edge .

This is not related to one PC, Phone or laptop this is related to some browsers. Microsoft Edge works but I have another issue with that as I cannot use any other tone than MP3 Tones instead of synthetic, the next problem is MP3 skips a beat when starting a race. 

Michael Fpv dose know about this issue of missing dependencies.

**Comment by HazardCreative** [comment]
Steps to consistently reproduce the issue are needed.

**Comment by BoLtWD** [comment]
This is a constant for me when using any browser other than Edge also the same on tablet, Phone and two other laptops 2 using windows 10 and another using windows 7 pro all missing same missing dependencies. If I can provide any more info tell me what to do and I will try.

**Comment by BoLtWD** [comment]
Commenting this line on in js dose get it going but its not a fix.

//rotorhazard.voice_language = $().articulate('getVoices')[0].name; // set default voice

**Comment by HazardCreative** [comment]
That simply removes the ability to use text to speech. There should be a better check in place before this line brings the rest of the JS down—but I'd like to know why it isn't loading in the first place.

**Comment by BoLtWD** [comment]
May be me but when you say "ability to use text to speech" speech is working ok on all platform's with this line commented out.

**Comment by HazardCreative** [comment]
2.0.1 Now tests if articulate is available and can provide a name before trying to use it. This is not a true solution but should be a suitable stop-gap.

**Comment by BoLtWD** [comment]
Tested 2.0.1 for this issue, this seams to have fixed this issue as a suitable stop-gap for me on all platform's below.

- Google chrome

- Android chrome

- Opera

Microsoft edge never had this issue.

**Comment by HazardCreative** [comment]
That's great news. We'll call that a victory until more information becomes available.
