### ISSUE TITLE
RSSI Smoothing no longer needs editing

### ISSUE THREAD

**Issue by gdevin** [RotorHazard/RotorHazard#168]
Remove references in documentation and management web page to changing the value of RSSI Smoothing.  In version 2.0 this value no longer needs changing.

**Comment by HazardCreative** [comment]
Can you provide links for where yo found it?

**Comment by gdevin** [comment]
The first place I saw a reference to setting RSSI Smoothing was on the timers web management page, in the "Sensor Tuning" section.  When I searched the documentation for more details, I found this, https://github.com/RotorHazard/RotorHazard/blob/master/doc/Tuning%20Parameters.md (just above the sample RSSI graph).
