### ISSUE TITLE
Issues with Software Setup Guide

### ISSUE THREAD

**Issue by first-caveman** [RotorHazard/RotorHazard#175]
G'day folks - 

First, thanks for the work on such a great project. I have been trying to set it up on a RPI 3B+ running Raspian Buster Lite 4.19.

I found a couple of problems with the software setup guide.

1. In the step where we clone the release to the Pi:
```
cd ~
wget https://codeload.github.com/RotorHazard/RotorHazard/zip/v1.1.0 -O temp.zip
unzip temp.zip
mv RotorHazard-1.1.0 RotorHazard
rm temp.zip
```

Replacing the URL with the latest version number v2.0.1 produced a `404 - file not found` error. I was able to fix this by replacing the URL altogether with `https://github.com/RotorHazard/RotorHazard/archive/2.0.1.zip`

2. Installing Java was not possible with `sudo apt-get install oracle-java8-jdk`. This [forum post](https://www.raspberrypi.org/forums/viewtopic.php?t=101543#p1201433) suggests that Java is no longer in the Raspian repository. I followed most of the instructions in that thread, but no cigar. I have opted to start over with Raspian Desktop, which should include Java by default. 
UPDATE: it doesn't. But I did install eventually install Java with `sudo apt install openjdk-8-jdk` on Raspian Desktop

Cheers,
Mike

**Comment by Strangedave** [comment]
Thanks for the help Mike, Instructions are still not updated, but your info was spot on. I did change the to 2.0.2 though.

**Comment by Strangedave** [comment]
I was able to correct the setup html to work with raspberry pi 4 and can provide corrected text for pi3 if it would help.
