### ISSUE TITLE
Request for new feature to 'copy existing heat'.

### ISSUE THREAD

**Issue by RogerBFPV** [RotorHazard/RotorHazard#180]
Problem I'm trying to solve:
During race day, I usually set up at least 2 classes, a class for 'practice' and a class, or several classes for races.   I do this so the practice classes results to not affect the official race results. 

Often after practice has started, we need to re-arrange pilots to different heats to accommodate late arrivals etc. When practice is over, I want the race heats pilot arrangements to be the same as what I ended up with in the practice heats.  If I've pre-set up race classes, I have to make sure to make the changes in both places.  If I don't pre-setup the race classes, I'd spend a lot of time trying to duplicate the heats of the practice classes.  

Possible solution:
If I could copy an existing heat, and then modify its class that would greatly speed up this process and I could set up the race classes in a few seconds.

**Comment by HazardCreative** [comment]
Possible extension to this: duplicating a class also duplicates all heats within it.

**Comment by RogerBFPV** [comment]
Yep, that could work too. This is why I list the 'problem' statement as you may have an idea for a better solution. Feel free to update the issue description as you desire.

**Comment by Strangedave** [comment]
We would also love this.
