### ISSUE TITLE
Countdown Timer is broken in 2.0.1

### ISSUE THREAD

**Issue by Cuxx** [RotorHazard/RotorHazard#184]
After some heats I have the issue that the countdown timer goes crazy. For the first 5-10 heats everything is ok. But after that it goes totally crazy. Sometimes it's only 5 seconds, sometimes 30s or sometimes 10 minutes+. The annoying part is that it's not only the ui, it also beeps all the time.

**Comment by HazardCreative** [comment]
Can you please provide more detail? When exactly does it show issues? How does it respond to different inputs? How can I reproduce this? What, if anything, can you do to get it back to normal?

**Comment by Cuxx** [comment]
yeah I'll test some stuff next time.
Normally I reboot the machine when this happens or I just mute the sound. It tracks normally, but UI & Sound is strange.

**Comment by HazardCreative** [comment]
If it's tracking times okay, then the issue might be in the browser. Try closing and re-opening the browser tab, or the whole browser program, or opening a different browser, and see if any of those fix it.

**Comment by Cuxx** [comment]
I already tried that. Reopening the browser (clean cache/cookies) doesn't help. Had the issue with chrome (android & windows).

**Comment by HazardCreative** [comment]
So the issues crosses over to other devices when it happens? Definitely NOT a front-end issue then. That's already helpful. The lap times coming in, do they look to be correct?

**Comment by Cuxx** [comment]
Mhh idk if the issue crosses over. But atleast I have it on both devices. Will test it next time (saturday). The laptimes are correct

**Comment by HazardCreative** [comment]
Without more detail, we can't investigate further. However, work that Mark and ET have been doing should improve stability. If the issue occurs again after the release of 2.1, please report back.
