### ISSUE TITLE
add option show absolute timestamp (since race start) for each lap

### ISSUE THREAD

**Issue by ScorpionTDL** [RotorHazard/RotorHazard#19]
add a option to show the timestamp of each pass additional to the lap time (in the Run/current page and potentially in the results tap as well)
This gives a much better overview about who passed a gate first. 

If I remember correctly the data for this is already available in the database, it just needs to be displayed, maybe with a setting to have it customizable.

**Comment by ScorpionTDL** [comment]
moment.js offers a lot of options to convert miliseconds to a readable format.
I used this in my fork of the original version to add this information.

i comes down to a simple
document.write( moment({{ lap.lap_time_stamp }}).format("mm:ss.SS"))
 in the end. (+ getting the information from the python side)

I agree that screen real estate is an issue and that the user needs to have the option to enable/disable this information.

**Comment by HazardCreative** [comment]
Is there a use case for seeing the raw ms count in the results
leaderboards? It's available from the database page if the debug flag is on.
