### ISSUE TITLE
Settings page, Sensor Tuning, EnterAt & ExitAt BLANK in update Commits on Jan 4, 2020

### ISSUE THREAD

**Issue by BoLtWD** [RotorHazard/RotorHazard#196]
Settings page, Sensor Tuning, EnterAt & ExitAt BLANK in update Commits on Jan 4, 2020
The RSSI Graph on the settings page under Tuning is being affected by above.

Race page seams to be working ok

**Comment by BoLtWD** [comment]
I backdated to Commits on Dec 31, 2019 The RSSI works on on the Settings page, Sensor Tuning and EnterAt & ExitAt are populated with their values, so after this to the latest as stated above the Settings page, Sensor Tuning, has something up with the RSSI values and the Graph for each node.

**Comment by ethomas997** [comment]
What version of code are you running on the Arduino nodes (what is the API_level)?  If it's an older version I could try and reproduce it here.

I'm not seeing a problem running the latest 'master' code on everything.  I'd recommend flashing the nodes to at least the version in the 2.1.0-beta.1 release (API_level 19) -- in my testing that version works fine with the latest server code in 'master'.  If you're still having trouble after that, please post your log output.

**Comment by BoLtWD** [comment]
•	Version: 2.1.0-beta.1
•	Server API: 24
•	Node API: 19

Like you say above version works ok, 

I was doing a beta test as below version and it turns out after rolling back to above version and then re updating all worked ok. 
Don’t know what I did wrong but know its working ok now as below version so I will close this issue.

•	Version: 2.1.0 (dev 3)
•	Server API: 24
•	Node API: 21

Thank you for your time and help

**Comment by ethomas997** [comment]
Thanks for trying it out.
