### ISSUE TITLE
RSSI will not register a VTX after using SCANNER

### ISSUE THREAD

**Issue by BoLtWD** [RotorHazard/RotorHazard#197]
Version: 2.1.0 (dev 3)
Server API: 24
Node API: 21
2.1.0-beta.1

I don`t know if this is an issue, when you goto the scanner page and select SCAN, deselect then go back to Settings - sensor Tuning  the RSSI will not register a VTX for that preset channel. The only way I have found to reset this is by changing all node Frequencies then back to the Frequencies you require, you can then see the RSSI value change when a Quad passes.

**Comment by ethomas997** [comment]
Yeah, I think there's a bug in there where the node frequency is not restored after the scanner runs.

@pulquero I saw that you have some more scanner modifications on your fork (though when I tried them it seemed like the scanner became non-functional).  Would you be able to post a PR that fixes this issue and brings in any new changes you'd like to put it for the scanner?

**Comment by pulquero** [comment]
@ethomas997 sure, I'll look into it.

**Comment by BoLtWD** [comment]
May I ask why are the scanner windows so small, why not make the visual aspect in columns of two so you have a larger scanner window for each node example for an 8 node it would be 2 columns by 4 rows. 

Just a thought

**Comment by HazardCreative** [comment]
The UI is mostly my area and I haven't put any time into styling this feature yet.

**Comment by ethomas997** [comment]
@pulquero Thanks.  This and the other recent features you've contributed have been awesome.

**Comment by BoLtWD** [comment]
Agree, fantastic work by all

**Comment by pulquero** [comment]
The problem is caused by not unticking the scan box before returning to sensor turning, in effect, sensor tuning is still showing rssi in scan mode. We should be able to fix this by forcibly disabling scan mode when the settings page is loaded.

**Comment by BoLtWD** [comment]
I am sure I un ticked the scanners before returning to the tuning and got no RSSI when a VTX passed. I will have to retest.

**Comment by BoLtWD** [comment]
Just checked

- Powered Timer
- Went to sensor turning and checked RSSI using a whoop, It climbed up without issue
- Went to SCANNER page, Ticked all scanners and again checked RSSI
- Turned OFF using Tick box ALL nodes scanning
- Went back to sensor turning and checked RSSI using a whoop, no RSSI reading

I reset the channels for the nodes and the RSSI climbed up without issue again.

**Comment by ethomas997** [comment]
I have a probable [fix](https://github.com/ethomas997/RotorHazard/commit/9be0c58dbfcf31506212c7f42d0013bb5fd27af4) that seems to address the issue; if you want you can try it out here:  https://github.com/ethomas997/RotorHazard/tree/pulquero_scanner_20200125

**Comment by BoLtWD** [comment]
Ok I have given it a try and yes this corrects the issue stated above however, if someone leaves the scanner page without deselecting the nodes then again you get the issue of the tuning having no RSSI. I  think you know of this issue already but I have to repoint it out as someone will do it.
