### ISSUE TITLE
Race call outs

### ISSUE THREAD

**Issue by BoLtWD** [RotorHazard/RotorHazard#208]
This is a comment made by Brett Hollifield on FB, I am posting it as simple call outs would be good, examples below

- Next race pilots "NAMES" please prepare craft to race
- Pilots "NAMES" to the start line
- Race stopped False start pilots Land and prepare craft for restart
- Race stopped due to safety, pilots land and collect raft

And one or two user input call outs

---------------------------------------------------------------------------------------------------
"Brett Hollifield"

Am I missing something, or does the RH Web UI not have a way for the heat/pilots names to be announced out loud when getting ready to start a new heat? I've liked that feature when using LiveTime, would be cool to have an option in RH when selecting another heat to play the heat name as well as the participating pilots out loud. If this option exists and I have missed it, I apologize. I'll create an issue on Github if it's not a feature available yet once I know for sure. Thanks!

**Comment by WrathPak** [comment]
Yes! Thank you @BoLtWD !
I was hoping for it to say something along the lines of:

"Heat 3. Pilot 1, Pilot 2, Pilot 3, Pilot 4"

Even something as simple as a couple play buttons next to the heat selection drop down on the Run screen, that allows for certain things related to that heat to be said aloud through the speaker.

LiveTime has something similar our group has used a lot with the Immersion Timer, and it's the one feature that's missing from RH that will probably make me lose my voice at events haha.

Thanks all!

**Comment by HazardCreative** [comment]
Until something easier exists, you can use the voice test box on the settings page audio panel to type and announce arbitrary text.

**Comment by HazardCreative** [comment]
Related: #161
