### ISSUE TITLE
Voice Calls in Current Taps only offers None|All|Pilot2 (on a two node system)

### ISSUE THREAD

**Issue by ScorpionTDL** [RotorHazard/RotorHazard#21]
The voice call selection is missing Pilot 1 on my two node System. (see attached Screenshot)
![voice calls png](https://user-images.githubusercontent.com/38523288/51930187-46e94680-23fa-11e9-8fb1-da9da48f1f2a.jpg)

**Comment by HazardCreative** [comment]
This check is no longer required, because there is no null pilot in the database.
https://github.com/RotorHazard/RotorHazard/blob/067754248930b95c3834eca5983c4cd574afc324/src/delta5server/templates/racepublic.html#L211
