### ISSUE TITLE
Before update "Added node I2C communications monitor" GUI was working but not now

### ISSUE THREAD

**Issue by BoLtWD** [RotorHazard/RotorHazard#210]
I have been following your updates in the comments to help test.

Before update "Added node I2C communications monitor" I could access the GUI

After updating  
"Added node I2C communications monitor" & "Added log indicator for I2C vs Serial node " & updating nodes  
I can see on start up the LED`s on the nodes scanning across as each node is addressed.
I now cannot log into the GUI and the port cannot be found when using a port scanner.  

Going back to 2.0.2 this works ok so something in the last updates have seam to have stopped the server working.

**Comment by ethomas997** [comment]
@BoLtWD Are you using the latest Python server code in 'master' on GitHub?  While the server is compatible with older versions of the (Arduino) node code, older server versions will not work with newer node code.

**Comment by BoLtWD** [comment]
Yes I am using the latest code downloaded from in the master on GitHub and installed onto pi  copying replacing files over into the existing Rh location on the pi , I have also flashed the node code found in the master onto the Arduinos.  I have done it this way before without issues untill this update in the code.

**Comment by ethomas997** [comment]
Yes, your testing is definitely appreciated.  Please post the log output generated by the (Python) server.

**Comment by BoLtWD** [comment]
Thank you for your help and sorry if I am naive but I am lost to where to find or how I would invoke the log output, however as I know the server.py is not running I manually run the server to see the output as below. Sorry my experience and knowledge is basic but with basic commands and explanations I may be able to provide...


pi@RACE_TIMER:~/RotorHazard/src/server $ python server.py

Configuration file imported
Loaded module i2c_helper
Loaded module i2c_node
Loaded module serial_node
I2C node 1 found at address 8
I2C node 2 found at address 10
I2C node 3 found at address 12
I2C node 4 found at address 14
I2C node 5 found at address 16
I2C node 6 found at address 18
I2C node 7 found at address 20
I2C node 8 found at address 22
Node 1: API_level=21, Freq=5658, EnterAt=105, ExitAt=85
Node 2: API_level=21, Freq=5887, EnterAt=105, ExitAt=92
Node 3: API_level=21, Freq=5760, EnterAt=93, ExitAt=78
Node 4: API_level=21, Freq=5800, EnterAt=69, ExitAt=58
Node 5: API_level=21, Freq=5917, EnterAt=78, ExitAt=67
Node 6: API_level=21, Freq=5800, EnterAt=93, ExitAt=78
Node 7: API_level=21, Freq=5800, EnterAt=255, ExitAt=78
Node 8: API_level=21, Freq=5800, EnterAt=69, ExitAt=56
Loaded module bme280_sensor
Loaded module ina219_sensor
Loaded module pi_sensor
Traceback (most recent call last):
  File "server.py", line 125, in <module>
    INTERFACE = interfaceModule.get_hardware_interface(config=Config)
  File "../interface/RHInterface.py", line 439, in get_hardware_interface
    return RHInterface(*args, **kwargs)
  File "../interface/RHInterface.py", line 127, in __init__
    self.discover_sensors(config=kwargs['config'].get('SENSORS', {}), *args, **sensorKwargs)
  File "../interface/BaseHardwareInterface.py", line 58, in discover_sensors
    self.sensors.extend(discover_plugins('sensor', *args, **kwargs))
  File "../interface/BaseHardwareInterface.py", line 26, in discover_plugins
    plugins.extend(plugin_module.discover(len(plugins), *args, **kwargs))
TypeError: discover() got multiple values for keyword argument 'config'

**Comment by HazardCreative** [comment]
Yes, that output is the startup log. Can you provide the contents of your config.json file? Feel free to remove the admin username/password/secret key.

**Comment by BoLtWD** [comment]
{
	"GENERAL": {
		"HTTP_PORT": 5000,
		"SECRET_KEY": "secret!",
		"ADMIN_USERNAME": "admin",
		"ADMIN_PASSWORD": "Gameon",
		"DEBUG": false,
		"CORS_ALLOWED_HOSTS": "*"
	},
	"SENSORS": {
	},
	"SERIAL_PORTS": [],
	"LED": {
		"LED_COUNT": 150,
		"LED_PIN": 10,
		"LED_FREQ_HZ": 800000,
		"LED_DMA": 10,
		"LED_INVERT": false,
		"LED_CHANNEL": 0
	}
}

**Comment by BoLtWD** [comment]
Ok this is what I have attempted to see if it would fix the issue.

- Reverted to 2.1.0-beta.1
- Did system update and upgrade
- Flashed nodes to code found in 2.1.0-beta.1
- Retest 2.1.0-beta.1. If all still works it did without issue
- Deleted all code 2.1.0-beta.1 installed in RotorHazard on PI
- Copy files found in MASTER on Github from zip file into RotorHazard folder
- cd ~/RotorHazard/src/server
- sudo pip install --upgrade --no-cache-dir -r requirements.txt
- pi@RACE_TIMER:~/RotorHazard/src/server $ python server.py


No configuration file found, using defaults
Loaded module i2c_helper
Loaded module i2c_node
Loaded module serial_node
I2C node 1 found at address 8
I2C node 2 found at address 10
I2C node 3 found at address 12
I2C node 4 found at address 14
I2C node 5 found at address 16
I2C node 6 found at address 18
I2C node 7 found at address 20
I2C node 8 found at address 22
Node 1: API_level=21, Freq=5658, EnterAt=105, ExitAt=85
Node 2: API_level=21, Freq=5887, EnterAt=255, ExitAt=92
Node 3: API_level=21, Freq=5760, EnterAt=93, ExitAt=78
Node 4: API_level=21, Freq=5800, EnterAt=69, ExitAt=58
Node 5: API_level=21, Freq=5917, EnterAt=78, ExitAt=67
Node 6: API_level=21, Freq=5800, EnterAt=93, ExitAt=78
Node 7: API_level=21, Freq=5800, EnterAt=255, ExitAt=78
Node 8: API_level=21, Freq=5800, EnterAt=69, ExitAt=56
Loaded module bme280_sensor
Loaded module ina219_sensor
Loaded module pi_sensor
Traceback (most recent call last):
  File "server.py", line 125, in <module>
    INTERFACE = interfaceModule.get_hardware_interface(config=Config)
  File "../interface/RHInterface.py", line 439, in get_hardware_interface
    return RHInterface(*args, **kwargs)
  File "../interface/RHInterface.py", line 127, in __init__
    self.discover_sensors(config=kwargs['config'].get('SENSORS', {}), *args, **sensorKwargs)
  File "../interface/BaseHardwareInterface.py", line 58, in discover_sensors
    self.sensors.extend(discover_plugins('sensor', *args, **kwargs))
  File "../interface/BaseHardwareInterface.py", line 26, in discover_plugins
    plugins.extend(plugin_module.discover(len(plugins), *args, **kwargs))
TypeError: discover() got multiple values for keyword argument 'config'

**All files installed have not been changed and are as downloaded MASTER on Github 14/01/2020**
As sever not run no database made by sever and no config file except default  config-dist.json

{
	"GENERAL": {
		"HTTP_PORT": 5000,
		"SECRET_KEY": "secret!",
		"ADMIN_USERNAME": "admin",
		"ADMIN_PASSWORD": "rotorhazard",
		"DEBUG": false,
		"CORS_ALLOWED_HOSTS": "*"
	},
	"SENSORS": {
	},
	"SERIAL_PORTS": [],
	"LED": {
		"LED_COUNT": 150,
		"LED_PIN": 10,
		"LED_FREQ_HZ": 800000,
		"LED_DMA": 10,
		"LED_INVERT": false,
		"LED_CHANNEL": 0
	}
}

Totally stuck at this point............................

Thank you for any advice

**Comment by BoLtWD** [comment]
I don't think this is the issue but I have Rtc ds3231 as #134 to the 12C, let me know if you think this may be an issue.

**Comment by ethomas997** [comment]
@BoLtWD Thanks for testing and posting the log (helps us a lot).  Please try the latest version (with commit 095be8ff4b516d2617e39eb87f68dbbb441a968b).

**Comment by BoLtWD** [comment]
Fantastic work FIXED, thank you
