### ISSUE TITLE
Collect and link related resources

### ISSUE THREAD

**Issue by HazardCreative** [RotorHazard/RotorHazard#211]
This repo should promote user-generated content that relates to the timer. Specifically, tutorials and videos relating to installation, setup, and usage.

- [ ] Dean Fourie's tutorial: https://deanfourie.me/delta5-lap-timer/
- [ ] Klaus Michael Schneider's Marshaling demonstration video: https://www.youtube.com/watch?v=xLMa-gRObHI
- [ ] AcroBaix team video series: https://www.youtube.com/channel/UCLn014XZdAuH_ZFa6KC9ksw
- [ ] ErikBorra's tutorial (currently in a PR, but would prefer a link to this outside the repo): https://github.com/RotorHazard/RotorHazard/pull/162
- [ ] ET's pages: http://www.etheli.com/rotorhazard/index.html

What others should we include? I don't mind linking to Delta5 info as well where it matches. Is there something good for LED setup?

**Comment by ethomas997** [comment]
Should we use the [wiki](https://github.com/RotorHazard/RotorHazard/wiki) for this?

**Comment by HazardCreative** [comment]
Makes perfect sense to me.

**Comment by HazardCreative** [comment]
Resources loaded to the [Wiki](https://github.com/RotorHazard/RotorHazard/wiki), except ErikBorra's PR #162. I would still like that document as a separately linked page so that RH isn't directly associated with any particular retailer for sourcing parts.
