### ISSUE TITLE
LED light up and stays on without a race being run

### ISSUE THREAD

**Issue by BoLtWD** [RotorHazard/RotorHazard#212]
Ref MASTER download issue found downloaded 15/01/2020

Don't know if this is a fault but when in any page and a node detects a VTX on its channel the corresponding LED light up and stays on without a race being run.

**Comment by HazardCreative** [comment]
Behaving as expected. This offers useful feedback while testing a system or for exhibition. To date, LED feedback has largely been for spectator benefit and not for pilots.

However, we're aware that this is not always the ideal behavior and recent changes have improved usability for pilots as well. Additional mods are coming which will likely change how this is handled. See here: https://github.com/RotorHazard/RotorHazard/commit/47a959dcf5232aa7371e5db5a5a54c4e16927306#comments

**Comment by BoLtWD** [comment]
Thank you just had to check.
