### ISSUE TITLE
RACE DID NOT START after panel setup and trying to start a race.

### ISSUE THREAD

**Issue by BoLtWD** [RotorHazard/RotorHazard#214]
Ref MASTER download issue found downloaded on Jan 18, 2020

I know this is in BETA, I have been testing the installation of an LED panel, I don`t have the panel yet and just using LEDs I have for now and just setting up the code.

1. As commented by Michael  I first installed  cv2; using sudo apt-get install python-opencv

2. Then, copy the config info from the top of bitmap_led_handler.py into my LED section of the config file WITHOUT THE COMMA AFTER led count number.

3. Ran the timer and logged in

The LEDs did not indicate as LED strip dose on start up.
Tested LEDs in LED section by activating buttons and inspecting corresponding for colors, ALL OK
Running a race, Activated START, RACE DID NOT START AND NO LEDS, could not repress start so refreshed page only to see the start button return to normal (not grayed out) . Repeated pressing start to get same result. 

This may be something to do with my setup above or an issue.

Shot in the dark, could this be down to this needing installing?     import numpy as np   found in bitmap_led_handler.py  line 28 ?

Hope my testing helps.

**Comment by HazardCreative** [comment]
Run your timer from the console and see if there are any errors.

**Comment by BoLtWD** [comment]
There is an error **KeyError: 'PANEL_ROTATE'**  See below

pi@RACE_TIMER:~/RotorHazard/src/server $ python server.py


Configuration file imported
Loaded module i2c_helper
Loaded module i2c_node
Loaded module serial_node
I2C node 1 found at address 8
I2C node 2 found at address 10
I2C node 3 found at address 12
I2C node 4 found at address 14
I2C node 5 found at address 16
I2C node 6 found at address 18
I2C node 7 found at address 20
I2C node 8 found at address 22
Node 1: API_level=21, Freq=5658, EnterAt=99, ExitAt=88
Node 2: API_level=21, Freq=5695, EnterAt=94, ExitAt=84
Node 3: API_level=21, Freq=5760, EnterAt=81, ExitAt=70
Node 4: API_level=21, Freq=5800, EnterAt=94, ExitAt=84
Node 5: API_level=21, Freq=5917, EnterAt=60, ExitAt=49
Node 6: API_level=21, Freq=5800, EnterAt=86, ExitAt=76
Node 7: API_level=21, Freq=5800, EnterAt=85, ExitAt=75
Node 8: API_level=21, Freq=5800, EnterAt=60, ExitAt=51
Loaded module bme280_sensor
Loaded module ina219_sensor
Loaded module pi_sensor
BME280 found at address 118
No BME280 at address 119
INA219 found at address 64
No INA219 at address 65
No INA219 at address 68
No INA219 at address 69
Program started at 1579450042221.000000
Language file imported
Number of nodes found: 8
Release: 2.1.0 (dev 3) / Server API: 25 / Latest Node API: 21
Found installed:  java version "1.8.0_65"
Found installed:  IMDTabler Version 1.3
Database current laps reset
Set Profile to '3'
LED: selecting library "rpi_ws2812x"
LED: hardware GPIO enabled, count=256, pin=10, freqHz=800000, dma=10, invert=False, chan=0, strip=GRB/528384
Running http server at port 5000
Client connected
Heartbeat thread started
Interface: Starting background thread.
Client disconnected
Client connected
set race format to 'Open Practice' (5)
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 648, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 677, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 284, in _handler
    *args)
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 698, in _handle_event
    ret = handler(*args)
  File "server.py", line 1709, in on_stage_race
    led_handler.staging()
  File "/home/pi/RotorHazard/src/server/bitmap_led_handler.py", line 43, in render
    rotated = np.rot90(img, self.config['PANEL_ROTATE'])
KeyError: 'PANEL_ROTATE'
2020-01-19T16:08:11Z <Thread at 0x6c6af718: <bound method Server._handle_event_internal of <socketio.server.Server object at 0x7536c930>>(<socketio.server.Server object at 0x7536c930>, '23fb9b521c2748ee806d3292c3ed1ca1', [u'stage_race'], '/', None)> failed with KeyError

Client disconnected
Client connected
set race format to 'Open Practice' (5)

**Comment by BoLtWD** [comment]
This is my config.json


{
	"GENERAL": {
		"HTTP_PORT": 5000,
		"SECRET_KEY": "secret!",
		"ADMIN_USERNAME": "admin",
		"ADMIN_PASSWORD": "thiswayup",
		"DEBUG": false,
		"CORS_ALLOWED_HOSTS": "*"
	},
	"SENSORS": {},
	"SERIAL_PORTS": [],
	"LED": {
		"HANDLER": "bitmap",
		"BITMAPS": {
			"staging": [{
				"image": "static/image/LEDpanel-status-staging.png",
				"delay": 0
			}],
			"start": [{
				"image": "static/image/LEDpanel-status-start.png",
				"delay": 0
			}],
			"stop": [{
				"image": "static/image/LEDpanel-status-stop.png",
				"delay": 0
			}],
			"finished": [{
				"image": "static/image/LEDpanel-status-finished.png",
				"delay": 0
			}]
		},
		"LED_COUNT": 256
	}
}

**Comment by HazardCreative** [comment]
Thanks! Definitely a bug, but there's an easy fix.
As a workaround, you can add a PANEL_ROTATE key to your config within BITMAPS. Set it to 0 to start with.

**Comment by BoLtWD** [comment]
I think I did what you asked but in the GUI same issue, no problem as at least you know about it please see below to what I have done. I will revert my config to the standard so all will work as normal until fix. Let me know If I can test any fixes for you.


**config.json**

{
	"GENERAL": {
		"HTTP_PORT": 5000,
		"SECRET_KEY": "secret!",
		"ADMIN_USERNAME": "admin",
		"ADMIN_PASSWORD": "landed",
		"DEBUG": false,
		"CORS_ALLOWED_HOSTS": "*"
	},
	"SENSORS": {},
	"SERIAL_PORTS": [],
	"LED": {
		"HANDLER": "bitmap",
		"BITMAPS": {
			"staging": [{
				"image": "static/image/LEDpanel-status-staging.png",
				"delay": 0
			}],
			"start": [{
				"image": "static/image/LEDpanel-status-start.png",
				"delay": 0
			}],
			"stop": [{
				"image": "static/image/LEDpanel-status-stop.png",
				"delay": 0
			}],
			"finished": [{
				"image": "static/image/LEDpanel-status-finished.png",
				"delay": 0
			}]
		},
		"LED_COUNT": 256,
		"PANEL_ROTATE": 0
	}
}




**Console**

pi@RACE_TIMER:~/RotorHazard/src/server $ python server.py

Configuration file imported
Loaded module i2c_helper
Loaded module i2c_node
Loaded module serial_node
I2C node 1 found at address 8
I2C node 2 found at address 10
I2C node 3 found at address 12
I2C node 4 found at address 14
I2C node 5 found at address 16
I2C node 6 found at address 18
I2C node 7 found at address 20
I2C node 8 found at address 22
Node 1: API_level=21, Freq=5658, EnterAt=99, ExitAt=88
Node 2: API_level=21, Freq=5695, EnterAt=94, ExitAt=84
Node 3: API_level=21, Freq=5760, EnterAt=81, ExitAt=70
Node 4: API_level=21, Freq=5800, EnterAt=94, ExitAt=84
Node 5: API_level=21, Freq=5917, EnterAt=60, ExitAt=49
Node 6: API_level=21, Freq=5800, EnterAt=86, ExitAt=76
Node 7: API_level=21, Freq=5800, EnterAt=85, ExitAt=75
Node 8: API_level=21, Freq=5800, EnterAt=60, ExitAt=51
Loaded module bme280_sensor
Loaded module ina219_sensor
Loaded module pi_sensor
BME280 found at address 118
No BME280 at address 119
INA219 found at address 64
No INA219 at address 65
No INA219 at address 68
No INA219 at address 69
Program started at 1579456060890.000000
Language file imported
Number of nodes found: 8
Release: 2.1.0 (dev 3) / Server API: 25 / Latest Node API: 21
Found installed:  java version "1.8.0_65"
Found installed:  IMDTabler Version 1.3
Database current laps reset
Set Profile to '3'
LED: selecting library "rpi_ws2812x"
LED: hardware GPIO enabled, count=256, pin=10, freqHz=800000, dma=10, invert=False, chan=0, strip=GRB/528384
Running http server at port 5000
Client connected
Heartbeat thread started
Interface: Starting background thread.
Client disconnected
Client connected
set race format to 'Open Practice' (5)
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 648, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 677, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 284, in _handler
    *args)
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 698, in _handle_event
    ret = handler(*args)
  File "server.py", line 1709, in on_stage_race
    led_handler.staging()
  File "/home/pi/RotorHazard/src/server/bitmap_led_handler.py", line 43, in render
    rotated = np.rot90(img, self.config['PANEL_ROTATE'])
KeyError: 'PANEL_ROTATE'
2020-01-19T17:49:04Z <Thread at 0x6d202e88: <bound method Server._handle_event_internal of <socketio.server.Server object at 0x753af930>>(<socketio.server.Server object at 0x753af930>, '5639673068934c21a04d0b85254c860b', [u'stage_race'], '/', None)> failed with KeyError

**Comment by HazardCreative** [comment]
That key goes within BITMAPS, not outside of it.

**Comment by BoLtWD** [comment]
Story of my life, missed the gate again

**config.json**

{
	"GENERAL": {
		"HTTP_PORT": 5000,
		"SECRET_KEY": "secret!",
		"ADMIN_USERNAME": "admin",
		"ADMIN_PASSWORD": "wrongwayround",
		"DEBUG": false,
		"CORS_ALLOWED_HOSTS": "*"
	},
	"SENSORS": {},
	"SERIAL_PORTS": [],
	"LED": {
		"HANDLER": "bitmap",
		"BITMAPS": {
				"PANEL_ROTATE": 0,
			"staging": [{
				"image": "static/image/LEDpanel-status-staging.png",
				"delay": 0
			}],
			"start": [{
				"image": "static/image/LEDpanel-status-start.png",
				"delay": 0
			}],
			"stop": [{
				"image": "static/image/LEDpanel-status-stop.png",
				"delay": 0
			}],
			"finished": [{
				"image": "static/image/LEDpanel-status-finished.png",
				"delay": 0
			}]
		          },
		"LED_COUNT": 256

	}
}


**Console shortened**

File "/home/pi/RotorHazard/src/server/bitmap_led_handler.py", line 43, in render
    rotated = np.rot90(img, self.config['PANEL_ROTATE'])
KeyError: 'PANEL_ROTATE'

**Comment by HazardCreative** [comment]
I think you pasted the wrong log, but it looks like "INVERTED_PANEL_ROWS": false, is not optional yet as well. Put it after PANEL_ROTATE. But I should have a patch for this shortly.

**Comment by BoLtWD** [comment]
**config.json**

{
	"GENERAL": {
		"HTTP_PORT": 5000,
		"SECRET_KEY": "secret!",
		"ADMIN_USERNAME": "admin",
		"ADMIN_PASSWORD": "ilandintrees",
		"DEBUG": false,
		"CORS_ALLOWED_HOSTS": "*"
	},
	"SENSORS": {},
	"SERIAL_PORTS": [],
	"LED": {
		"HANDLER": "bitmap",
		"INVERTED_PANEL_ROWS": false, 
		"BITMAPS": {
				"PANEL_ROTATE": 0,
			"staging": [{
				"image": "static/image/LEDpanel-status-staging.png",
				"delay": 0
			}],
			"start": [{
				"image": "static/image/LEDpanel-status-start.png",
				"delay": 0
			}],
			"stop": [{
				"image": "static/image/LEDpanel-status-stop.png",
				"delay": 0
			}],
			"finished": [{
				"image": "static/image/LEDpanel-status-finished.png",
				"delay": 0
			}]
		          },
		"LED_COUNT": 256

	}
}

**Console** 

pi@RACE_TIMER:~/RotorHazard/src/server $ python server.py
Configuration file imported
Loaded module i2c_helper
Loaded module i2c_node
Loaded module serial_node
I2C node 1 found at address 8
I2C node 2 found at address 10
I2C node 3 found at address 12
I2C node 4 found at address 14
I2C node 5 found at address 16
I2C node 6 found at address 18
I2C node 7 found at address 20
I2C node 8 found at address 22
Node 1: API_level=21, Freq=5658, EnterAt=99, ExitAt=88
Node 2: API_level=21, Freq=5695, EnterAt=94, ExitAt=84
Node 3: API_level=21, Freq=5760, EnterAt=81, ExitAt=70
Node 4: API_level=21, Freq=5800, EnterAt=94, ExitAt=84
Node 5: API_level=21, Freq=5917, EnterAt=60, ExitAt=49
Node 6: API_level=21, Freq=5800, EnterAt=86, ExitAt=76
Node 7: API_level=21, Freq=5800, EnterAt=85, ExitAt=75
Node 8: API_level=21, Freq=5800, EnterAt=60, ExitAt=51
Loaded module bme280_sensor
Loaded module ina219_sensor
Loaded module pi_sensor
BME280 found at address 118
No BME280 at address 119
INA219 found at address 64
No INA219 at address 65
No INA219 at address 68
No INA219 at address 69
Program started at 1579461637428.000000
Language file imported
Number of nodes found: 8
Release: 2.1.0 (dev 3) / Server API: 25 / Latest Node API: 21
Found installed:  java version "1.8.0_65"
Found installed:  IMDTabler Version 1.3
Database current laps reset
Set Profile to '3'
LED: selecting library "rpi_ws2812x"
LED: hardware GPIO enabled, count=256, pin=10, freqHz=800000, dma=10, invert=False, chan=0, strip=GRB/528384
Running http server at port 5000
Client connected
Heartbeat thread started
Interface: Starting background thread.
Client disconnected
Client connected
set race format to 'Open Practice' (5)
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 648, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 677, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 284, in _handler
    *args)
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 698, in _handle_event
    ret = handler(*args)
  File "server.py", line 1709, in on_stage_race
    led_handler.staging()
  File "/home/pi/RotorHazard/src/server/bitmap_led_handler.py", line 45, in render
    self.setPixels(rotated)
  File "/home/pi/RotorHazard/src/server/bitmap_led_handler.py", line 58, in setPixels
    if self.config['INVERTED_PANEL_ROWS']:
KeyError: 'INVERTED_PANEL_ROWS'
2020-01-19T19:21:20Z <Thread at 0x6c7877a0: <bound method Server._handle_event_internal of <socketio.server.Server object at 0x75341930>>(<socketio.server.Server object at 0x75341930>, '93d4bb4fd4e745aeb9bac1bb800f2dbb', [u'stage_race'], '/', None)> failed with KeyError

**Comment by BoLtWD** [comment]
Not expecting a fix just testing anything you want me to, hopefully to help

**Comment by HazardCreative** [comment]
INVERTED_PANEL_ROWS goes within BITMAPS as well. But it shouldn't be necessary anymore, and neither should PANEL_ROTATE... or any of the rest of the BITMAPS section unless you want to change the defaults.

**Comment by BoLtWD** [comment]
Sorry not having a good night, at least you have a fix. Nice work
