### ISSUE TITLE
Indicator for finding pi sync

### ISSUE THREAD

**Issue by HazardCreative** [RotorHazard/RotorHazard#216]
Users should be made aware that the timer is searching for a good sync value. On a wireless (or unstable) network, sampling to obtain sync may take a short time and sync may not be immediately accurate. If a race is started before sync is gained, audio and LED/time signals will not match.

A 'sync loss' indicator appears when the timer detects its clock script isn't responding (such as switching to another tab and back) and remains until the clock can restore itself. Perhaps this indicator could be used for this purpose as well, but will need re-coded to account for multiple 'on' conditions.

**Comment by ethomas997** [comment]
In #198 (Indicators for node communication errors) I'm suggesting indicators for Pi-to-node comm errors, which are different, but maybe could go into the same GUI widget somehow.

**Comment by HazardCreative** [comment]
Yeah, that's why I added a new issue.
