### ISSUE TITLE
Panel LEDs wont change to Staging, Start and stop, Commits on Jan 20, 2020 (Updates to LED strip indicators )

### ISSUE THREAD

**Issue by BoLtWD** [RotorHazard/RotorHazard#217]
Ref Commits on Jan 20, 2020 (Updates to LED strip indicators )

Updated to above and found panel LEDs wont change to Staging, Start and stop.
When timer config set to strip all strip LEDs work ok.

Hope this helps

**Comment by ethomas997** [comment]
At this point I'm only implementing support for LED strips.  (I don't have an LED panel on hand.)  Michael may be working on necessary changes for panel support.

**Comment by BoLtWD** [comment]
Understand but wanted to bring this to light as this was working before the update to (Updates to LED strip indicators ) from (Switch to startup display to "startup" handler)

**Comment by ethomas997** [comment]
Might it be that previously your timer was configured for LED strip (the default)?

**Comment by BoLtWD** [comment]
No,


{
	"GENERAL": {
		"HTTP_PORT": 5000,
		"SECRET_KEY": "secret!",
		"ADMIN_USERNAME": "admin",
		"ADMIN_PASSWORD": "flyingtonight",
		"DEBUG": false,
		"CORS_ALLOWED_HOSTS": "*"
	},
	"SENSORS": {},
	"SERIAL_PORTS": [],
	"LED": {
		"HANDLER": "bitmap", 
		"BITMAPS": {
			"staging": [{
				"image": "static/image/LEDpanel-status-staging.png",
				"delay": 0
			}],
			"start": [{
				"image": "static/image/LEDpanel-status-start.png",
				"delay": 0
			}],
			"stop": [{
				"image": "static/image/LEDpanel-status-stop.png",
				"delay": 0
			}],
			"finished": [{
				"image": "static/image/LEDpanel-status-finished.png",
				"delay": 0
			}]
		          },
		"LED_COUNT": 256

	}
}

**Comment by BoLtWD** [comment]
I have also back dated 2 x with same config and works ok befor update.

**Comment by HazardCreative** [comment]
I think the handler system needs to change. Right now you choose between a handler for strip or bitmap, and that controls all of your events. But more likely, you will want one behavior for one event and something different for another. This is exactly the case here, where bitmap is appropriate for start/stage/stop, but showing a bitmap is not appropriate for gate crossings.

@BoLtWD ET is correct; the default handler is for a strip. You have changed handler to bitmap with this configuration. The bitmap handler has nothing defined for gate crossing events.

**Comment by BoLtWD** [comment]
Thank you.

**Comment by BoLtWD** [comment]
@HazardCreative Probably me misunderstanding sorry if so, my comment above was that the panel leds now don't indicate start/stage/stop I now the panel at this time wont indicate a pass. I agree that some setups may be better with a panel and others strip, using config files to change is not an easy solution from one setup to another.

**Comment by pulquero** [comment]
Maybe modify the bitmap handler to default to strip lighting effects instead of doing nothing if a bitmap is not defined for a particular event.

**Comment by BoLtWD** [comment]
@pulquero Good point at least a panel will work as a strip but a strip won't work as a bitmap.

**Comment by HazardCreative** [comment]
Oh, perhaps I misread this then. I haven't installed ET's latest to a timer.
