### ISSUE TITLE
Some Text's are not translated 

### ISSUE THREAD

**Issue by ScorpionTDL** [RotorHazard/RotorHazard#22]
Translation not working for the following Texts:
Start Page
-Current Event
-Actions

Current
-Voice Selection
--All
--None

Run
-Crossing
-Clear 
-Race Management
--In seconds
Settings
-Frequency Settings
--Frequency set IMD rating
--Sensor Tuning
---Sensor Crossing indicator Takes “Clear” value from “Run/Clear Laps” however the German meaning is totally different in this situation, there needs to be some distinction between the two “Clear” 
---Calibration (with all following points)
---Troubleshooting (with all following points)

**Comment by HazardCreative** [comment]
The string for Frequency set is actually: "Frequency set IMD rating (100=best)"
"Clear Laps" is now "Discard Laps"
