### ISSUE TITLE
Ref : history-calibration : indication to say it is set to manual or Adaptive on race page

### ISSUE THREAD

**Issue by BoLtWD** [RotorHazard/RotorHazard#222]
Ref : history-calibration

I have taken into consideration comment on FB " It will always show "manual" first. Changing the dropdown does activate the feature."

I have not had a chance to do field testing but one thing, it would also be good on the race page to have some indication it is set to manual or Adaptive.

**Comment by HazardCreative** [comment]
This was never intended behavior, it simply didn't get built out completely in the experimental branch.

**Comment by HazardCreative** [comment]
The behavior of calibration adjustments has changed. It now takes effect when you change heats, not when the race starts. You can now easily see when the feature is on because the enter/exit values on the graphs will update when you change heats. A separate indicator isn't needed.
