### ISSUE TITLE
Make logs more accessible

### ISSUE THREAD

**Issue by HazardCreative** [RotorHazard/RotorHazard#224]
The console log should be kept and made accessible through the front-end. This will help with debugging and providing support to users.

When the config debug flag is on, it should also be saved to a local file.

**Comment by pulquero** [comment]
We should just use a proper logging framework.

**Comment by pulquero** [comment]
Logging moved over to python logging framework: https://github.com/pulquero/RotorHazard/commit/baa4d0abe2224b5c8c54b8f4895ccb86cf1e3fc7

**Comment by HazardCreative** [comment]
Looks like a good start, but I didn't see any front-end changes? The purpose of this issue is mostly to expose that log without needing to run a terminal.
