### ISSUE TITLE
Setup rotorhazard with OBS. A way to disable the popups

### ISSUE THREAD

**Issue by BoLtWD** [RotorHazard/RotorHazard#225]
Ref FB 26.01.2020 @ 22:18 Quote BY Aaron Smith  "Trying to setup rotorhazard with OBS. Is there a way to disable the popups? If I schedule next round it breaks the OBS output with the popup "

As no one has entered this as an issue wanted to bring this across.

**Comment by HazardCreative** [comment]
A workaround (and perhaps preferred solution for some) is to extract fields using the JSON API and use them individually.

**Comment by HazardCreative** [comment]
I looked into OBS a little and I'm not sure this is true. OBS can't natively parse JSON. Closing this issue since the duplicate exists as well in #226.
