### ISSUE TITLE
LED Don`t turn off when Turn off selected also Recommend default button for led events

### ISSUE THREAD

**Issue by BoLtWD** [RotorHazard/RotorHazard#232]
Updated to Commits on Feb 2, 2020

- Server Shutdown, when leds set to Turn Off it does not seem to turn any leds off when the server is 
   shut down.
   Simulated by setting by setting the leds to a colour leds now on, checking Server Shutdown set to 
   Turn Off then selecting shut down, the leds stay the same colour after shut down and do not go off.

- Recommend that the led events could do with a reset to default button, (default set as 
   strip), users could get themselves into confusion when seeing leds indicating strangely due to any 
   led events have been set for using images.

**Comment by ethomas997** [comment]
Ah, good catch, I was shutting down the server by hitting Ctrl-C in its console window.  I just posted a commit that should fix it.

**Comment by BoLtWD** [comment]
Fixed by Commits on Feb 3, 2020
