### ISSUE TITLE
Custom/more LED options

### ISSUE THREAD

**Issue by szafranski** [RotorHazard/RotorHazard#233]
Hello, I have tried newest beta 4 release. Seems pretty cool but please add some more options for LED “states”. Eg. allow custom images and solid colors on EVERY “stage”. Now there is no “solid red” during staging etc. And please add an option for custom images so original images can stay with original names. I will be happy to provide more info if needed. 

Cheers

**Comment by HazardCreative** [comment]
More effects are definitely planned. For this release we're really trying to make sure the new system works well and retain the existing functionally within it (plus a little more).

However, you can expect that the predefined effects will encourage you to make selections that function equally well for colorblind users. Using only solid colors doesn't meet this standard.

**Comment by szafranski** [comment]
Ok, I get it. But for now I wanna make all leds red during staging and turn off when race starts - as it used to be in last stable release. I mean nice that more options are in the way. For now please give ability for same options during every “step”. Now it is artificially predefined. Thanks and great work!

**Comment by HazardCreative** [comment]
I'm not sure I understand. In previous releases, race stopped was solid red, race staging was solid orange, and race started was solid green. You can duplicate that now, except that the orange is a pattern instead of a solid.

You seem to be asking for solid red during staging and LEDs off when started. You can assign these effects to these events in the new panel on the Settings page. There's no need to use bitmap images.

**Comment by szafranski** [comment]
Got you, some predefined options are nice. For now, there is no option for any solid color during staging. RH 2.1.0 dev 4

![staging](https://user-images.githubusercontent.com/23621888/73708629-36e7ff00-46ff-11ea-8065-363953e7ecc2.png)

**Comment by szafranski** [comment]
Besides I think that it would be nice if you add options like "Image: Custom_1.png", "Image: Custom_2.png" etc. sp custom bitmaps could be added easily to the image folder.

**Comment by HazardCreative** [comment]
Take a look at the latest commits.

User-defined images will definitely be coming, though I'll probably go a different route that's a bit more flexible. For now, feel free to just rename/overwrite the supplied image files.

**Comment by szafranski** [comment]
Ok, thanks :)

**Comment by szafranski** [comment]
For me issue can be closed for now.

**Comment by HazardCreative** [comment]
Great. I hope the future expansions will get you what you're looking for.
