### ISSUE TITLE
Can't open settings in Google Chrome

### ISSUE THREAD

**Issue by szafranski** [RotorHazard/RotorHazard#234]
Can't open settings page of RH in Google Chrome. After entering login and password I can only see blank page. Checked with few versions of server firmware. 

Checked cleaning history and cookies - doesn't help.

Settings page works in incognito mode and Mozilla Firefox.

**Comment by HazardCreative** [comment]
Works here on Chrome 79/Win32 or Android 10. Steps to reproduce?

**Comment by szafranski** [comment]
I don't know if this will be useful but I made a video. Win64.
[IMG-6522.zip](https://github.com/RotorHazard/RotorHazard/files/4151160/IMG-6522.zip)

**Comment by HazardCreative** [comment]
I didn't follow you at first but I think I've caught up to you now. Check out the latest commits.

**Comment by szafranski** [comment]
Excuse me, I don'tunderstand. Can you explain?

**Comment by HazardCreative** [comment]
Anything odd happening in the server console/terminal output? How about the Chrome devtools (F12)?

**Comment by szafranski** [comment]
Console shows "Client disconnected" after clicking settings link in Chrome.

**Comment by szafranski** [comment]
Chrome F12 - IP and "failed to load"

**Comment by szafranski** [comment]
Restarting Chrome few times helped cause authentication prompt appeared again. Issue may be related to LastPass extension.

**Comment by szafranski** [comment]
Ok, checked with disabled LastPass - works.
