### ISSUE TITLE
Plan and Define Steps for Integration with ClearView

### ISSUE THREAD

**Issue by ryaniftron** [RotorHazard/RotorHazard#236]
This issue is to plan out how the ClearView Video Receivers. I have created a shared google doc[ here ](https://docs.google.com/document/d/1HrKh5Wo97TiZiQTbsgXI1NGb29_WqsKlPrzUyt27BQE/edit?usp=sharing)to detail it. Anyone can contribute. 

Once planning is complete, this issue can be closed.

**Comment by ryaniftron** [comment]
Due to the limitations with the OSD refresh rate and delays with 1.20 API, should initial implementation focus on more detection of receivers, configuring basic settings, and displaying non-critical time messages on the OSD like pilot names and race stats after the race is complete?

**Comment by HazardCreative** [comment]
If the refresh is 1Hz, I definitely don't think race start/finish signaling is a good idea. But that should be good enough for lap times and split times. Either way, the 'set OSD message' command coming from RH will probably be the same regardless of displaying a lap time or some other status.

**Comment by ryaniftron** [comment]
Correct on messages to "start" or "finish" the race, but I was referring to providing info after a racer finishes the race like this:

- Place: 2
- Lap 1: 12.2
- Lap 2: 16.3
- Lap 3: 13.6

Correct, when the RH want to use the 'set OSD message', it only needs to know how many characters it can set and which receivers it needs to send the message to.

**Comment by HazardCreative** [comment]
I don't think the OSD delays and lack of sync is an issue there, but I do worry that just having one line means the UI requires too much time and cognitive effort to use for that kind of data. And in this case, the race director will be wanting to move on quickly to prep the next race. Pilots should be vacating chairs and retrieving their quads, not sitting around for a full minute in the goggles. Perhaps we just pick the most relevant one-liner. Pilots can get their other lap data afterward from the results page.

**Comment by HazardCreative** [comment]
At least at this stage, that sounds like a good place to leave it. Changing the message that goes out is almost trivial after the rest of the API exists.

**Comment by ryaniftron** [comment]
Perfect. 

For the communication, it seems like there is two options. One uses two PI's. The other uses one PI and a bluetooth serial adapter. Thoughts?

Option 1: One PI
![image](https://user-images.githubusercontent.com/57248914/73899090-be8d5500-4848-11ea-99c9-8758108598e3.png)

Option 2: Dual PI's
![image](https://user-images.githubusercontent.com/57248914/73899108-d369e880-4848-11ea-8424-0baeaaaa1410.png)

**Comment by HazardCreative** [comment]
I don't think a Bluetooth link to the RH Pi is workable given the distances and terrain/environment possibilities. I couldn't get the pi's WiFi working at some of our race locations. I had to go with an external router and many mod the pi with external antennas or WiFi dongles. So, why have to solve that problem twice? Let's use WiFi. Maybe the CV controller could be lower cost, like an ESP32.

**Comment by ryaniftron** [comment]
Good to know. Ethernet between two PI's would be the most reliable. The wifi link could handle raw serial data (the CV scripts run on the RH PI), or the CV Controller could handle it. I don't know what would be better. 
 
One advantage of a rasberry Pi (even RPi zero) is it can run python. ESP32 only runs Micropython which I found pretty buggy last time I used it.

**Comment by szafranski** [comment]
There are always some problems with BT devices. AP commands not working, problem with pairing etc. Ethernet for sure! Btw if Raspberry Pi zero can be used - awesome. 10$ + maybe Ethernet adapter 3$

**Comment by ryaniftron** [comment]
Yes, a zero can be used - it has a built in hardware serial port just like the pi3.

**Comment by pulquero** [comment]
As a pilot, when my heat is announced I want to pick up my CV and gear from the pit area and take it to the pilot area, near race control. I want to take up my position and connect my CV to race control. At the end of the heat, I want to disconnect my CV from race control and return to the pits. I am happy to connect a dongle to my CV in order to connect it to race control if it's cheap and easy to purchase or if race control makes them freely available.

As race control, I would prefer not to have more cables all over the place - how many times do ppl trip over the timer cable and break that. I would prefer a wireless solution. If I am going to be handing out dongles, they need to be cheap and easy to construct.

=> pilot area is located near race control, so bluetooth is viable as a comm mechanism from that perspective.
=> pilot wants a no-faff/zero-config solution - most likely dongle/cable will be provided by race control. Pilot wont want to faff connecting their CV with some other pilots CV, want to connect own CV 'direct' to race control (topology shouldnt dictate user experience)
=> race control doesnt want to sink a disproportiate amount of money into providing this service to pilots.
=> next version of CV should probably include an esp32 or something (OTA firmware upgrades etc)!

**Comment by HazardCreative** [comment]
The other likely option here is that the receivers are club-owned. As a pilot, you walk to the CV and plug its AV into your goggles. A lot of higher-budget operations do it this way.

Bluetooth from a laptop or other device near the pilot area is fine, but I don't think it's reasonable direct to/from the timer. Seems to me that IP networking is the best solution as it could be wired or wireless as best follows the needs of the group. (But typically/primarily WiFi, I assume)

I would be fine if there was an option to use Bluetooth to a bridge. The other issue with Bluetooth is in multiple CV controllers. If the pilots bring the CV controller equipment it's likely that they will permanently attach them to the CV. In this instance, multiple CV controllers in one system are likely. Bluetooth doesn't like having multiple devices very much. I've seen this with many devices, even those built for the purpose. Having a Bluetooth hub with multiple controllers connected may not work well in practice.

Lots of questions coming to me now:
- How can RH address/discriminate the connected controllers?
- Do we need some way for RH to enable/disable them? 
- Can a pilot-owned controller be used as a read-only device (for spectating with OSD)? 
- Would a spectating controller have to connect or could it listen for commands RH is sending elsewhere and act on them without responding back?
- Should the controller set the node pairing or RH?
- Can multiple controllers be connected to the same node? (Between heats, one pilot turns his equipment on before the last one shuts down)
- Should the API have connect/disconnect events? (I think yes—if possible all the way from RH to CV and not just RH to controller)

**Comment by pulquero** [comment]
> 
> The other likely option here is that the receivers are club-owned. As a pilot, you walk to the CV and plug its AV into your goggles. A lot of higher-budget operations do it this way.

I would describe that as a possibility, but niche/uncommon.

> direct to/from the timer. 

This highlights an implicit assumption in my user story - race control has a laptop. There are three potential deployment scenarios then: club/adhoc (RH no laptop), "league" (RH, laptop), "pro" (CV provided). Ideally, we have something that works across all three well, but I don't think that's a must (initially).

It seems some sort of dongle is inevitable. Is daisy chaining achievable in a way transparent to the user? Would there be a "backbone" and each pilot connects to their "slot" in the chain? If a slot was unoccupied (pilot without CV), would there need to be some bypass switch to prevent a break in the chain? If you don't daisy chain then alot of comm ports are going to be required. Wifi/IP is looking very attractive, no shortage of virtual comm ports, and wifi-serial bridges are a "thing" - plenty of prior art to leverage.

**Comment by ryaniftron** [comment]
While I appreciate the discussion of the CV network architecture and use cases of what racers would expect bringing their own receivers vs using a club-managed system, a lot of these questions are out of the scope of both this issue and what RotorHazard as a system will need to do. I will take all this information and open up some relevant issues on the [ClearView Interface Github](https://github.com/ryaniftron/clearview_interface_public). 

That said, I think the following has been decided (correct me if I am wrong)
- The RH Pi will communicate with CV's or some CV Controller through WiFi
- The RH Pi does not need to know if the CV's are club managed or not. Perhaps it is a mix of club and personal units
- Pilots have very little time and the setup should not require any configuration
  - If a pilot brings their own CV, they will have to say what "seat number",1-8, they are
  - The RH server may tell all CV with seat 1 to perform an action. This would affect both the pilot who is configured their CV as seat 1 as well as any spectators. 
  - If a RH server wants to make a request of data for seat 1, only the active pilot's CV should respond. The RH server does not need to know if spectators have video lock

* race control doesnt want to sink a disproportiate amount of money into providing this service to pilots
>> Yes, the central controller can run on a rasberry pi zero and serial cable for $20. Each cable removal to a CV requires an ESP32. Whether the race control or pilot pays for the dongles doesn't matter to me, but all CV's not directly wired to the controller through serial will need a dongle.

*next version of CV should probably include an esp32 or something (OTA firmware upgrades etc)!
>They plan to sell a dongle (if they ever release it). Until then I have to make them. 


* How can RH address/discriminate the connected controllers?
>Inside the CV, the seat number can be 1-8, and that can be used to differentiate between racers, however there is no current plan for how to differentiate different pilots who share the same seat and spectators. It will have to be implemented in the CV_ESP32 or CV_Controller.

*Do we need some way for RH to enable/disable them?
> Yes, the RH needs to know who is the pilot in order to perform data requests. This will not be implemented in the cv's serial protocol, so it will have to be a layer above that (in the wifi protocol). I will put some thought into it. If the RH requests for data, the cv controller should know who the active pilot is and return the correct data.

*Would a spectating controller have to connect or could it listen for commands RH is sending elsewhere and act on them without responding back?
> Commands right now do not feature automatic response anyways. Listen only should be fine for spectators, but I plan to implement a robust mode for racing to ensure any commands set actually take affect by comparing the command with a subsequent report. This can be handled internally to the CV, so just know if the RH designates a CV as an active pilot, robust mode will be automatic and the ESP32/Controller could reply when successful over the wifi link

*Should the controller set the node pairing or RH?

> Please elaborate on what you mean by node pairing. 

*Can multiple controllers be connected to the same node? (Between heats, one pilot turns his equipment on before the last one shuts down)
>Depending on the architecture, yes. MQTT for example allows any publisher to publish to any subscriber. You could have two controllers in this method, but I don't see why there needs to be more than one controller if it's all on the same wifi network.

*Should the API have connect/disconnect events? (I think yes—if possible all the way from RH to CV and not just RH to controller)
>Yes, it already has a connectivity getter for CV-controller; I can implement these as pushed messages. If using MQTT, these connect/disconnect messages are automatic and the RH server just needs to listen for them.

**Comment by pulquero** [comment]
> a lot of these questions are out of the scope of both this issue and what RotorHazard as a system will need to do.

Personally, I like to understand the context in which a design sits, feel it out abit. Some aspects of this are more familiar to me than others.

> Yes, the central controller can run on a rasberry pi zero and serial cable for $20. Each cable removal to a CV requires an ESP32.

Would ESP32 be a better choice than a pi zero? AFAIK, ESP32 can support 3 serial ports (one is enough). I think for the pi zero you need to add an SD card plus a serial pi zero board.

> Inside the CV, the seat number can be 1-8, and that can be used to differentiate between racers, however there is no current plan for how to differentiate different pilots who share the same seat and spectators. It will have to be implemented in the CV_ESP32 or CV_Controller.

I think it would be better for the CV_controller to be dumb, and RH maintains the mapping of (controller/IP addr, comm port, cv address) to (seat, role=active pilot/pilot/spectator).

> 
> *Do we need some way for RH to enable/disable them?
> 
> > Yes, the RH needs to know who is the pilot in order to perform data requests. This will not be implemented in the cv's serial protocol, so it will have to be a layer above that (in the wifi protocol). I will put some thought into it. If the RH requests for data, the cv controller should know who the active pilot is and return the correct data.

See above, RH can directly address the active pilot rather than via the cv controller.

> robust mode will be automatic and the ESP32/Controller could reply when successful over the wifi link

Could robust mode just be the default/standard behaviour?

> but I don't see why there needs to be more than one controller if it's all on the same wifi network.

There would be more than one controller if dongles are being used.

**Comment by ryaniftron** [comment]
Personally, I like to understand the context in which a design sits, feel it out abit. Some aspects of this are more familiar to me than others.
>Fair. I was more wanting to say I didn't want to burden the RH team with solving all of those problems when they are specific to ClearViews, may be too much of a bite to chew for initial release, and I was planning on solving them later if Iftron doesn't release their own version.

Would ESP32 be a better choice than a pi zero? AFAIK, ESP32 can support 3 serial ports (one is enough). I think for the pi zero you need to add an SD card plus a serial pi zero board.
> Both are good. The Pi runs full python which means the module I wrote is drop-in. It already has extensive error checks and fully implements. True on the SD card, but it doesn't look like you need a board for the[ serial port](https://www.abelectronics.co.uk/kb/article/1035/raspberry-pi-3--4-and-zero-w-serial-port-usage). You only need one anyways. 

I think it would be better for the CV_controller to be dumb, and RH maintains the mapping of (controller/IP addr, comm port, cv address) to (seat, role=active pilot/pilot/spectator).
> It can be done either way, but the smarter the CV_controller is, the less burdened the network is. The logic needs to be written in somewhere, so I will start establishing some of it now. One reason I thought we wanted it the former way was so the RH API is receiver-manufacturer-agnostic. TBS fusion and Rapidfire also have external control capabilites. TBS is WiFi and RapidFire is SPI.

See above, RH can directly address the active pilot rather than via the cv controller.
> Yes, it could

Could robust mode just be the default/standard behaviour?
> Absolutely. The only reason I didn't yet was because not all commands have working responses yet due to some bugs in the CV. 

There would be more than one controller if dongles are being used.
>We should establish a clear definition for the controller. If there isn't a central unit computing messages for the ClearViews, ie the ClearView's dongle's and the RH PI are the only hardware, then there is no physical controller. I propose the following definitions:
 **Controller:** The higher level clearview  code that translates info from the RH api into commands for ClearViews. There is only one. It may speak to the RH directly if running on the RH API, but it always outputs commands directly to CV's through WIFI or Serial.
**Dongle:** The device that translates WiFi messages to serial data to control the CV 
**CV Hub** A physical device that talks to multiple CV's through serial. It may have more intelligence than a dongle.

**Comment by pulquero** [comment]
> I propose the following definitions:
> **CV_Controller:** The higher level clearview  code that translates info from the RH api into commands for ClearViews. There is only one. It may speak to the RH directly if running on the RH API, but it always outputs commands directly to CV's through WIFI or Serial.

I imagine then that this would take the form of a RH plugin, bit like the race timer interface or sensors or led handlers. RH would say talk to that in terms of (seat,role,command). Multiple controller plugins maybe active to support multiple receivers makes, e.g. CV, rapidfire, TBS.  Simple implementation would then just be a controller that talked to a CV connected directly to the timer PI via USB serial, say. 

> **CV_Dongle:** The device that translates WiFi messages to serial data to control the CV
> **CV_Hub** A physical device that talks to multiple CV's through serial. It may have more intelligence than a dongle.

These two are then an implementation detail of how the controller processes API calls from RH.

> **RH-Video-Receiver API** The code that RH runs to issue commands to control receivers and request for status. This info could be sent over WiFi to Dongles or a controller, OR only pass through software to the CV_Controller

This would be (seat,role,command) in my example.

**Comment by ryaniftron** [comment]
> > robust mode will be automatic and the ESP32/Controller could reply when successful over the wifi link
> 
> Could robust mode just be the default/standard behaviour?

`https://github.com/ryaniftron/clearview_interface_public/commit/c6f0b25bdfb06a594fe4ed5721512b23b5556b05` in the cv code. 

I am doing some research into the wireless communication method we will use to exchange data at the application layer. I put some more thoughts on the google doc. Initial candidates are MQTT and the json_api that is already implemented. It would be smart to look at more.

 I also realized an easy way to handle the addressing problem of knowing who the active pilot is to pair a mac address of the wifi chip with either the race organizer's name or pilot name. If they have multiple cv's or dongles on the net, the identifying name can include in integer. This will make it easy for the timing system to associate which receivers are used by which pilots and automatically enable and disable who the active pilot is.

**Comment by ryaniftron** [comment]
> > I propose the following definitions:
> > **CV_Controller:** The higher level clearview  code that translates info from the RH api into commands for ClearViews. There is only one. It may speak to the RH directly if running on the RH API, but it always outputs commands directly to CV's through WIFI or Serial.
> 
> I imagine then that this would take the form of a RH plugin, bit like the race timer interface or sensors or led handlers. RH would say talk to that in terms of (seat,role,command). Multiple controller plugins maybe active to support multiple receivers makes, e.g. CV, rapidfire, TBS. Simple implementation would then just be a controller that talked to a CV connected directly to the timer PI via USB serial, say.
> 
That sounds ideal for flexibility. We do only get 3-5m with USB, and the CV runs at a pretty quick 57k serial, so I see WiFi or Ethernet being mandatory as part of the system. Do you think the MVP should include that thought? We can simulate the data exchange by putting the data into JSON objects between the scripts. 

> > **CV_Dongle:** The device that translates WiFi messages to serial data to control the CV
> > **CV_Hub** A physical device that talks to multiple CV's through serial. It may have more intelligence than a dongle.
> 
> These two are then an implementation detail of how the controller processes API calls from RH.
> 

Yes - the RH shouldn't know about it if it wants to be platform agnostic.
> > **RH-Video-Receiver API** The code that RH runs to issue commands to control receivers and request for status. This info could be sent over WiFi to Dongles or a controller, OR only pass through software to the CV_Controller
> 
> This would be (seat,role,command) in my example.

Yes, however based on our discussion of pilot vs spectator earlier, (seat,role) is not descriptive enough to differentiate between a pilot in seat 1 and a few spectators watching seat 1's feed. 

Assuming the RH keeps a table of `mac_address:assigned_human_readable_unique_name`, the command would be formatted as follows:
(assigned_human_readable_unique_name:command). 
For any dongle device, the dongle doesn't actually need to know the seat name because the dongle can broadcast. 

A hub will need to consume multiple CV's commands, so it will also keep the same table I just described, but only needs units connected via serial to distribute seat commands to. The only purpose of the seat name is for the daisy chained serial commands to target one receiver.

**Comment by pulquero** [comment]
> Do you think the MVP should include that thought?

I think it would be an easier first step/prototype on the way to MVP.

> Yes, however based on our discussion of pilot vs spectator earlier, (seat,role) is not descriptive enough to differentiate between a pilot in seat 1 and a few spectators watching seat 1's feed.

I was imagining it would be sufficient, as your example would be differentiated as (1,pilot) vs (1,spectator).

> Assuming the RH keeps a table of mac_address:assigned_human_readable_unique_name

To be precise, I was imagining "pure" RH would only know about (seat,role), say. The controller plugin would contain the mapping of (seat,role) to (ip address) or whatever receiver addressing system the controller wants to implement. But yes, RH as a program/process would keep the table.

**Comment by ryaniftron** [comment]
> > Do you think the MVP should include that thought?
> 
> I think it would be an easier first step/prototype on the way to MVP.
> 
Good let's do that

> > Yes, however based on our discussion of pilot vs spectator earlier, (seat,role) is not descriptive enough to differentiate between a pilot in seat 1 and a few spectators watching seat 1's feed.
> 
> I was imagining it would be sufficient, as your example would be differentiated as (1,pilot) vs (1,spectator).
> 
There needs to be some way to promote a specific spectator to the active pilot. Not sure who keeps track of this. I can see it being a mess unless there is an easy way for the GUI. People should give up their personal ClearView's to race organizer for the day IMO. 
> > Assuming the RH keeps a table of mac_address:assigned_human_readable_unique_name
> 
> To be precise, I was imagining "pure" RH would only know about (seat,role), say. The controller plugin would contain the mapping of (seat,role) to (ip address) or whatever receiver addressing system the controller wants to implement. But yes, RH as a program/process would keep the table.

This is a way to do it, but again, if a pilot changes which receiver they want to use for a race, then I can see it getting confusing unless the GUI also has a way to change it.

**Comment by pulquero** [comment]
> There needs to be some way to promote a specific spectator to the active pilot...
> ...if a pilot changes which receiver they want to use for a race

I guess we need to distinguish between CV with a static role, like a CV provided by the race organiser, and a dynamic role, like personal (active pilot <-> unactive pilot/spectator). RH knows which pilot is in which heat, so probably we can join it all up. Maybe it needs to be based on pilot name if role is pilot, RH knows what seat that pilot has and when the pilot is flying. Maybe closer to what we need is (role, identifier) where the meaning of identifier depends on the role.

**Comment by ryaniftron** [comment]
> I guess we need to distinguish between CV with a static role, like a CV provided by the race organiser, and a dynamic role, like personal (active pilot <-> unactive pilot/spectator). RH knows which pilot is in which heat, so probably we can join it all up. Maybe it needs to be based on pilot name if role is pilot, RH knows what seat that pilot has and when the pilot is flying. Maybe closer to what we need is (role, identifier) where the meaning of identifier depends on the role.

Yea - let's try to draft up how this is going to work in the google doc and give it a sanity check for all the weird scenarios. Should we require each wireless receiver can provide a unique key for identification to be compatible with the RH system? I know ESP32's can do it. 

Side note:  I don't have a timeline, but when the next ClearView API is released, setting PAL video type will work and the OSD will allow a much faster and quick refresh rate without blanking out. This means we should plan on there being support for time-critical messages. The 12 character limit will still be in effect.

**Comment by ryaniftron** [comment]
Because it doesn't appear anyone has a bunch of extra ClearView 2.0's lying around, I'll whip out a software simulator of the ClearView for you all to test with.

**Comment by szafranski** [comment]
awesome!

niedz., 9 lut 2020 o 19:39 ryaniftron <notifications@github.com> napisał(a):

**Comment by ryaniftron** [comment]
The simulator is making good progress. I was curious if you all had thoughts on if the simulator should be dependent on the ClearView API or if I should make run as a virtual serial port. The advantage of running in conjunction with ClearView API is it's quicker to get running and the limit checking and sanity checking don't need to be twice. 

The simulator right now emulates a pyserial serial port with the same methods but behind the scenes is just interacting with a database of receiver settings. As it gets sent commands or requests, the database updates as needed. 

It seems there's a few ways to slice the cake on where the simulator runs and what it talks to, but I don't know what makes the most sense for people who don't have a CV that want to develop rotorhazard code to support it.

**Comment by ryaniftron** [comment]
Simulator is done for setters. It will open up the receivers with default settings. You can then change settings. When closed down, it saves all settings to a text file in the same directory. The settings are persistent across restarts. I uploaded instructions to the clearview [README](https://github.com/ryaniftron/clearview_interface_public/blob/master/README.md) if you are curious.


The getters (getting settings fromt the cv) are not yet working, but I'll keep at it. Regardless, this should be enough for any contributors here to test code on the RH side. Let's start planning out the UI for the ClearViews and how it will work on the RH back end.

**Comment by realhuno** [comment]
Hello, i have another idea without Clearview.
why not use the OSD from the Aircraft?

Just use the Aircraft Name "craftname" as Placeholder for the laptime ;-)
I use the Trainerport to feed in the laptimes as PPM values.... not finished but principle working. 

Here is my project
https://github.com/realhuno/taranis_trainer_OSD

**Comment by HazardCreative** [comment]
That's really interesting! This is another example of why we need a decoupled architecture. A device like this could talk to RH's API and receive/respond to the same text/OSD commands that we send to the CV receivers. Ryan is developing this for CV2 and that's really great, but the potential for other integrated systems (this and RapidFIRE SPI come to mind) is something we're considering. I'd love to have you developing radio telemetry link to work with the video messaging API that develops out of this CV work.

**Comment by ryaniftron** [comment]
Yes, using the aircraft's OSD is also a good option. In my testing, I found the bandwidth pretty limiting for sending character data. It was also difficult to interface with the radio without extra hardware. Certainly the RH API could be built to support any of them. 

Speaking of, can we start creating some items to design in support of the MVP. I can help with the back end system in the timer.

**Comment by realhuno** [comment]
Hi, i can confirm...... working ;-)  

![image](https://user-images.githubusercontent.com/9394139/75099466-4d78cc00-55c2-11ea-819c-3be32064fa8e.png)
A Simple Test.

![image](https://user-images.githubusercontent.com/9394139/75099487-7e590100-55c2-11ea-9672-8d01f1bdbb00.png)
Esp32 democode on the top...
background.lua betaflight script ... codes to change

![image](https://user-images.githubusercontent.com/9394139/75099505-afd1cc80-55c2-11ea-8b99-7e1c268a878c.png)
Hardware Mod

**Comment by HazardCreative** [comment]
This is super interesting and leads me to believe the API needs a hardware descriptor that tell RH about device capabilities. I started to rough in the high level RH API in the shared document. My portion of this is likely to be the closest to the RH side of things, where the code is device-agnostic and makes the requests that go through the events and handlers—such as when RH gets/sets the data and what exactly it sends out for messages.

If someone else wants to pick up how the system locates new devices, keeps track of what's connected, and actually gets the messages pushed out to them, that would be a helpful complement to where my own expertise lies.

**Comment by ryaniftron** [comment]
Nice - we can get both to work. Agree on the hardware descriptor. 

I can do device location and messaging - if you make some super general function stubs I can implement discovery and messaging.

**Comment by HazardCreative** [comment]
I'm focusing on getting 2.1 stable out the door, but after that I'll get things moving here on my end.

**Comment by HazardCreative** [comment]
Getting the precursor code underway with #273.

**Comment by ryaniftron** [comment]
Can anyone with ESP32 experience help me out? I'm using the ESP32 IDF and need to add some libraries.
[ESP32 code commit](https://github.com/ryaniftron/clearview_interface_public/commit/aa25678608da2d690a69f994193d42dd378bfd44)

VRxManager is on it's way to RH shortly. We will be using MQTT communication with video receivers.

**Comment by pulquero** [comment]
Unfortunately I use the esp32 arduino libs.

**Comment by ryaniftron** [comment]
It was painful, but I found a way... Here's a screenshot of the web server that each ESP32 generates before it connects to a network.

![image](https://user-images.githubusercontent.com/57248914/77150683-0d3e2980-6a5a-11ea-82eb-1c4fd18df9ef.png)

 Anyways, I'll be back to the RH integration shortly because the painful part of the ESP32 is almost done.

**Comment by ryaniftron** [comment]
Can you add a field of "Camera Type", default of "Auto", with selection between "Auto","NTSC", and "PAL"? Eventually I would like the pilots to be able to change this in case they switch out aircraft. 

![image](https://user-images.githubusercontent.com/57248914/77812503-564c3a00-7067-11ea-8aca-64f6896b5046.png)

**Comment by ryaniftron** [comment]
Because #285 , the MVP implementation is started, and the planning is largely over, I will close this issue. Thanks!

**Comment by HazardCreative** [comment]
> Hi, i can confirm...... working ;-)

@realhuno Can you please provide more information and code on this most recent method you posted about? I'm interested in moving it forward within RH.

**Comment by realhuno** [comment]
Here is the code from the Chorus. 
https://github.com/realhuno/Chorus-RF-Laptimer

lua script for the transmitter
The background.lua -> protocol.mspWrite(11, valsTemp) this replace the craftname with an fake telementry sensor value. (like the laptime)

Whats new?
Callback ;-) to Laptimer. Change the frequency via the transmitter. 
![image](https://user-images.githubusercontent.com/9394139/80823830-93af6480-8bdd-11ea-8ebb-53bd2e3d4153.png)

Methode 1
now we have to fake an frsky sensor and send via s.port.  like the modul bay or an second receiver.
check the examples... 
https://github.com/RealTadango/FrSky

Methode 2
my very first try was to using the trainer port to send the craftname. 
But i failed to convert like the laptime to ppm value like -2500 +2500. And the Values are jittering.
Old Project with two team points https://github.com/realhuno/taranis_trainer_OSD

Methode 3
Serial Port... In the Transmitter 
but custom opentx firmware needed because of the the serialread ability.
