### ISSUE TITLE
After Save/Discard laps option to have leds default to a preselected state

### ISSUE THREAD

**Issue by BoLtWD** [RotorHazard/RotorHazard#239]
After Save/Discard laps is it possible to have an option to have leds default to a preselected state saved in settings, example RotorHazard logo or image or color pattern.

**Comment by HazardCreative** [comment]
The 'save race' button actually runs the code for both 'save' and 'discard' so it's not a drop-in addition of an event. (Thought it shouldn't be a big deal to split them.) However, I'd like to know what other timer events the community is interested in having LED effects for.

**Comment by BoLtWD** [comment]
I don't think I am explaining correctly. At this time when you select save or discard the led panel or led strip turns off and nothing is displayed without manual intervention. Just wondering if it's possible to have leds default to a preselected state saved in settings, example RotorHazard logo or image or color pattern or nothing (off). This is the same for when the server is running and finished displaying STARTUP leds, the pannel goes off. 

Again sorry if I am not explaning correctly.

I like the idea of a panel or strip on the bases it could help hard of hearing pilots and act as a visual aid to all.

As for events Tiny Whoops are fantastic in winter times and leds for these are a must,  due to the crappy cameras on them the images like the pause is unclear. I have been playing with a  orange standby symbol and this is a bit more defined for the low quality cameras. 
There is starting to be a big push by Jesse P to get Tiny Whoop more into the uk.

**Comment by HazardCreative** [comment]
No, I get what you're asking and it makes sense. I think you've just misunderstood the terminology. Here, an event is an action or system state. An effect is any LED change. Here, the "event" would be "Save Laps" or "Discard Laps". The currently applied "effect" is "Turn Off". 

The system is still in active development. If there are other events where an effect is desired I'd like to understand what they are.

As an aside, though connected services are possible, RotorHazard will *never* require an active internet connection to use. I have a strong opinion about that. I'm interested in your experiments on the specifics of the staging signal. You already know I am going to be fairly particular about it, but I'm not 100% sold on the current option. But that's a topic for another issue.

**Comment by BoLtWD** [comment]
For me I believe you have covered all the events needed as all other would be outside of the timer and race operations. The only thing I can think of would be some indication of change of heats example below (I will leave the real look up to your wisdom). This could be the image when you select save or discard that is defaults to and when you change a heat the number and possibly color of the number changes for each heat.
 
![Untitleda](https://user-images.githubusercontent.com/25492262/74091580-f1398680-4ab0-11ea-8558-bea376d3218f.jpg)


As for the image experiment I am trying see below, this is not something I would want to take away from the pause as this works well for better camaras, I am just looking for something that is clear with a crappy camera, something that is normally found on a whoop. 
This is what it look like and I find this is nice and clear for a whoop.
![Untitled](https://user-images.githubusercontent.com/25492262/74091357-71aab800-4aae-11ea-81f5-5bc3875ac35c.jpg)
 
This is the actual image
![LEDpanel-16x16-standby](https://user-images.githubusercontent.com/25492262/74091372-a159c000-4aae-11ea-91b8-96b2bedebc17.png)

This is why I also like the idea of having presets for LED Events in settings someone can save what they like for the type of race they are running example Outdoor, indoor and Whoops (possibly dark with leds)

**Comment by HazardCreative** [comment]
I'll definitely be exploring numeric displays in the future. I don't want to pre-generate them as image files, but the image library in place should be able to print arbitrary characters. 

Your exploration for staging display is helpful and I'll take it into consideration.

**Comment by HazardCreative** [comment]
Save/Discard event added in e0f7e00. (These are not yet separate events.)

**Comment by BoLtWD** [comment]
Fantastic... Do I need to open a new issue in regard to led indication of change of hearts that can be selected in events?

**Comment by HazardCreative** [comment]
Each GitHub issue should contain only one item. It helps with managing conversations and tracking progress.
