### ISSUE TITLE
Add an option for restart and shutdown the server without rebooting raspberry

### ISSUE THREAD

**Issue by szafranski** [RotorHazard/RotorHazard#242]
Thanks for addition the button for rebooting raspberry. Very nice. 
It would be nice if there will be an option just for restarting just the server (and maybe even for stopping it). I saw one of those in some beta version. It's a good idea I think - just add clear distinction between restarting and rebooting etc. Cheers, nice work!!

**Comment by szafranski** [comment]
Added this as an answer to previous issue

**Comment by HazardCreative** [comment]
The server restart function exists in this branch: https://github.com/RotorHazard/RotorHazard/tree/restart-self

However, it's not quite working right. The restart keeps a hold of your browser session so while a new browser can connect quickly, reloading the same browser takes a long time. I haven't sorted this out yet so I don't think the feature is release-ready.

**Comment by szafranski** [comment]
ok, sorry for writing same issue 2 times - my mistake. As we are speaking - what about implementing the "notes" site?
