### ISSUE TITLE
USB nodes requirements

### ISSUE THREAD

**Issue by szafranski** [RotorHazard/RotorHazard#247]
Consider adding additional instructions about connecting nodes directly to usb, like requirements (eg. py-serial).

**Comment by ethomas997** [comment]
I think we'll add py-serial to the requirements.txt file.

**Comment by szafranski** [comment]
Nice,

**Comment by HazardCreative** [comment]
Does it make sense to maintain a separate text file with the optional modules?

**Comment by ethomas997** [comment]
In this particular case I think the py-serial support is quite generic and should be included by default.  Also, I can envision next-generation RotorHazard hardware using serial instead of I2C, even inside the timer box.

**Comment by szafranski** [comment]
Are there any benefits of using serial instead of I2C?

czw., 13 lut 2020 o 23:04 E Thomas <notifications@github.com> napisał(a):

**Comment by ethomas997** [comment]
If we replace the 4 (or 8) Arduinos with a single 32-bit processor connected via serial link, I believe the internal communications would be faster and have fewer errors.

**Comment by szafranski** [comment]
Replacing the chip is quite a big step. That actually mean the project
would be forked.

W dniu pt., 14.02.2020 o 11:58 E Thomas <notifications@github.com>
napisał(a):

**Comment by HazardCreative** [comment]
Not necessarily; we already have serial node support.

**Comment by szafranski** [comment]
So it would be like raspberry pie and 32 bit processor right?

W dniu pt., 14.02.2020 o 13:05 Hazard Creative <notifications@github.com>
napisał(a):

**Comment by ethomas997** [comment]
> So it would be like raspberry pie and 32 bit processor right?
Yes -- thinking about improving the PCB board hardware (running basically the same software).

**Comment by szafranski** [comment]
I think that new pcb design should be published for existing 4 node setup regardless of future hardware changes. There are some issues with existing PCB design.

**Comment by HazardCreative** [comment]
Resolved in 3ea9a45
