### ISSUE TITLE
Panel Indication for change of heat in numeric

### ISSUE THREAD

**Issue by BoLtWD** [RotorHazard/RotorHazard#248]
Indication for change of heat in numeric value that is displayed on a Led panel, this could be selected in events for Save/Clear Laps and manual selection to display in LED Control Effect.

**Comment by HazardCreative** [comment]
There are a number of features which come close to this and may already solve your use case. If not, RH4 supports plugins which extend its feature capabilities. This function should be added via plugin instead of to core.
