### ISSUE TITLE
Node auto-numbering

### ISSUE THREAD

**Issue by HazardCreative** [RotorHazard/RotorHazard#252]
Now that PCB projects are moving forward in earnest, I'm considering the hardware spec for node address auto-selection. The existing spec was taken from a proposal to the delta5 project that hasn't been implemented and no PCB yet exists under that spec. It appears to me that the spec could be reduced to just 3 pins, and perhaps moved closer to GND on the board.

Please weigh in on whether this change should be made and any additional considerations.

**Comment by sl33pydog** [comment]
I like the idea.  Less to configure and a smaller foot print to trace to on the pcbs.

**Comment by HazardCreative** [comment]
Should this be binary, such as:
Node 1 = None
Node 2 = 1st pin
Node 3 = 2nd pin
Node 4 = 1st pin + 2nd pin
Node 5 = 3rd pin
Node 6 = 1st pin + 3rd pin
Node 7 = 2nd pin + 3rd pin
Node 8 = 1st pin + 2nd pin + 3rd pin

As for which pins to use, D4, 7, and 8 are the least capable (no PWM, no interrupts, no analog, no other functions).

These overlap the legacy spec, so they couldn't co-exist. The node code could contain a define for 'legacy addressing'. I don't feel too bad about that since only DIY types would have enabled hardware addressing so far.

**Comment by sl33pydog** [comment]
The binary is exactly how I was hoping it would be.  Pin 1 denotes even or odd and pin 2 and 3 cycle through the particular node.  For szafranski's board you could set board 1 with zero jumper pad soldering and the second board you would solder all pin3 jumper pads.  Makes it really simple.  Mine would be harder but it cuts down the solder pads significantly.  Plus by adding one more pin you could make it easily do 16 total nodes but I doubt we'd get to that point.

**Comment by sl33pydog** [comment]
![IMG_20200302_215420](https://user-images.githubusercontent.com/61440555/75783293-f2fc1000-5d25-11ea-8d83-258c3fa0b851.jpg)
I only need two pins to configure each node side.  The lower has pin 2 open for odd numbers and the upper is for even numbers since pin 2 is closed.  Thoughts?

**Comment by HazardCreative** [comment]
What pins are these? I'd suggested D4 / 7 / 8 above. Did you match that or are you suggesting something different? And which pin is the most/least significant?

As an aside, I would do the instructions in a table like so:
| Node # | 1 | 3 | 5 | 7 |
|--------|---|---|---|---|
| P4   | ▢ | ▢ | ▣ | ▣ |
| P3   | ▢ | ▣ | ▢ | ▣ |

**Comment by sl33pydog** [comment]
> What pins are these? I'd suggested D4 / 7 / 8 above. Did you match that or are you suggesting something different? And which pin is the most/least significant?
> 
> As an aside, I would do the instructions in a table like so:
> 
> Node #	1	3	5	7
> P4	▢	▢	▣	▣
> P3	▢	▣	▢	▣

I went with pins d2, d3 and d4.  It made the routings cleaner and a bit easier since they are next to the ground pin.  I can change them back to 4,5,6 if needed.  It'll look more like this revision I did.  
![IMG_20200224_221915](https://user-images.githubusercontent.com/61440555/75795504-07e19f00-5d38-11ea-8327-3dfdbfd03a13.jpg)

I'll change the silkscreen to make it more like the table.  It makes more sense to non technical users. I'll change the p to a j for jumper and explain it in the manual.

**Comment by HazardCreative** [comment]
These pins take up the Arduino's I2C bus. It's probably unlikely that we will use that before migrating to another chip, but I'd be interested to hear if there are any opinions on that. 

Assuming we keep D2/3/4, Let's make D4 the most significant (+4 to node number when grounded) so that it has the same function on the legacy vs. newer auto-numbering format. It would follow to have D2 be least significant (+1) and D3 be in between (+2). I think that's what you have.

This might even make it possible to have both schemes usable in the node code without configuring an option.

**Comment by sl33pydog** [comment]
> These pins take up the Arduino's I2C bus. It's probably unlikely that we will use that before migrating to another chip, but I'd be interested to hear if there are any opinions on that.
> 
> Assuming we keep D2/3/4, Let's make D4 the most significant (+4 to node number when grounded) so that it has the same function on the legacy vs. newer auto-numbering format. It would follow to have D2 be least significant (+1) and D3 be in between (+2). I think that's what you have.
> 
> This might even make it possible to have both schemes usable in the node code without configuring an option.

So the first picture is configured that way.  Sorry I was thinking about it in terms of upper vs lower and got confused.

**Comment by HazardCreative** [comment]
Okay, so new node hardware selection spec will be:

If any of D5-D8 are tied to ground on startup, use legacy hardware selection. Otherwise:

Node number defaults to 0 (Node 1) and is modified as follows:
+1 if D2 grounded
+2 if D3 grounded
+4 if D4 grounded

Legacy hardware selection is considered deprecated, but will continue to be supported for now. In the event that RH ever expands to support 16 nodes, support will likely be removed and D5 may be repurposed. I don't think this is likely, so legacy selection may continue indefinitely. Hardware/PCBs should NOT be designed with the legacy spec.

Any final objections?

**Comment by sl33pydog** [comment]
No objections from me

**Comment by HazardCreative** [comment]
Published in https://github.com/RotorHazard/RotorHazard/wiki/Specification:-Node-hardware-addressing

**Comment by HazardCreative** [comment]
(I suppose the issue should sty open until implemented in code)

**Comment by szafranski** [comment]
To be clear, If pin D2 is grounded - node number is set to 2
If D2 and D3 is grounded - number is set to 4
If D3 is grounded and D2 is foloating - nmber 3 - right?

**Comment by just-david** [comment]
Is anyone working on a version 2.0 board in the same 100x100mm format as the current board?

**Comment by szafranski** [comment]
Yes, me :)


W dniu pon., 16.03.2020 o 15:17 just-david <notifications@github.com>
napisał(a):

**Comment by szafranski** [comment]
Yes, me :)

Check this out: https://github.com/RotorHazard/RotorHazard/issues/91

**Comment by HazardCreative** [comment]
> To be clear, If pin D2 is grounded - node number is set to 2
> If D2 and D3 is grounded - number is set to 4
> If D3 is grounded and D2 is floating - number 3 - right?

Node 1 = None
Node 2 = D2
Node 3 = D3
Node 4 = D2 + D3
Node 5 = D4
Node 6 = D2 + D4
Node 7 = D3 + D4
Node 8 = D2 + D3 + D4

**Comment by szafranski** [comment]
Thanks for example

W dniu wt., 17.03.2020 o 00:04 Hazard Creative <notifications@github.com>
napisał(a):

**Comment by HazardCreative** [comment]
> 
> 
> Is anyone working on a version 2.0 board in the same 100x100mm format as the current board?

See #91. The existing board is already the "Delta5 V2", so we will likely call the new one in this format something like "RotorHazard Classic PCB (v1)".

**Comment by HazardCreative** [comment]
Implementation in #277 should resolve this issue but requires testing.

**Comment by szafranski** [comment]
Have you tested that new autonumbering? I see this for now:

![image](https://user-images.githubusercontent.com/23621888/78422883-e8a19e80-7662-11ea-8e8f-a486033f97b9.png)
