### ISSUE TITLE
Support for RGBW, GRBW, etc. LED strips

### ISSUE THREAD

**Issue by yorb** [RotorHazard/RotorHazard#269]
I used my existing LED strip to make a start/finish whoop gate, but it's a GRBW strip ([this one](https://www.banggood.com/1M-5M-WS2812B-5-Pins-RGBW-RGBWW-4-IN-1-LED-Strip-Light-Non-Waterproof-DC5V-p-1211152.html?rmmds=myorder&ID=51619044707&cur_warehouse=CN), in fact) and there's no support for this in RotorHazard (the colors and length come out all wrong if you use GRB, since it assume 3 LEDS per pixel when there's actually 4).

The LED library supports these strips, so it's just a matter of adding the options to `ws281x_leds.py`, e.g.:

```py
    elif led_strip_config == 'GRBW':
        led_strip = 0x18081000
````
Other variations (such as RGBW, RBGW, etc.) can be found in [this file](https://github.com/jgarff/rpi_ws281x/blob/master/ws2811.h).

I was going to do this PR myself, but after updating to 2.1.0 I noticed that some of the new LED commands don't seem to work with my GRBW strip. In particular, the custom color selector always comes out white. I haven't done much testing so I think that may be the only issue, but I wanted to stick this up as an issue first since someone else probably has a better understanding of what all needs to change to support these strips.

**Comment by HazardCreative** [comment]
It looks like there might be an issue with the custom color selector, so that may be unrelated. Do the other effects (such as the 8 static color buttons) all work as expected?

**Comment by yorb** [comment]
Yep, the static colors, rainbow, etc all seem to work. I only tested a race with Node 1, which lit up green at the start and then blue for each lap. Couldn’t figure out where to set node color, but I’m guessing node 1 is set to blue?

If everything else works, maybe this is easier than I thought :)

**Comment by HazardCreative** [comment]
Node colors aren't user-settable yet. I'm hoping to get this in for 2.2. The current colors are the same as these controls, in the same order:

![image](https://user-images.githubusercontent.com/7169527/76154065-056aa680-60a4-11ea-944f-92b97e9ad469.png)

**Comment by HazardCreative** [comment]
Does this work with your strip? https://github.com/RotorHazard/RotorHazard/pull/274
