### ISSUE TITLE
Idea of easy logging and uploading log files of RotorHazard

### ISSUE THREAD

**Issue by szafranski** [RotorHazard/RotorHazard#278]
Hello, I just implemented some simple logging with auto uploading log files in my OTA software. I was thinking that it may be implemented same way to RotorHazard itself. Of course I can log RotorHazard files as well but maybe you as devs want to do it. My idea of doing that:

script like:

log_me()
{
cd ~/RH-ota
mkdir log_data
rm log_data/log.txt > /dev/null 2>&1
echo > ./log_data/log.txt
echo FILE /boot/config.txt | tee -a  ./log_data/log.txt
echo -------------------------------------------- | tee -a  ./log_data/log.txt
echo | tee -a  ./log_data/log.txt
cat /boot/config.txt | tee -a  ./log_data/log.txt
echo | tee -a  ./log_data/log.txt
echo FILE /boot/cmdline.txt | tee -a  ./log_data/log.txt
echo -------------------------------------------- | tee -a  ./log_data/log.txt
echo | tee -a  ./log_data/log.txt
cat /boot/cmdline.txt | tee -a  ./log_data/log.txt
echo | tee -a  ./log_data/log.txt
echo FILE updater-config.json | tee -a  ./log_data/log.txt
echo -------------------------------------------- | tee -a  ./log_data/log.txt
echo | tee -a  ./log_data/log.txt
cat ~/RH-ota/updater-config.json | tee -a  ./log_data/log.txt
echo | tee -a  ./log_data/log.txt
echo FILE ~/.ota_markers/ota_config.txt | tee -a  ./log_data/log.txt
echo -------------------------------------------- | tee -a  ./log_data/log.txt
echo | tee -a  ./log_data/log.txt
cat ~/.ota_markers/ota_config.txt | tee -a ./log_data/log.txt
echo | tee -a  ./log_data/log.txt
} 

Than, in python program itself:

def log_send():
	selection = str(raw_input("\n\n\tDo you want to send a log file for a review to the developer? [y/n] "))
	if selection=='y' or selection =='yes':
		if parser.getint('added_functions','curl_installed') == 0:
			if not os.system("sudo apt install curl"):
				parser.set('added_functions','curl_installed','1')
				parser_write()
		log_name = str(raw_input("\n\tPlease enter your name so we know who sent a log file: "))
		print("\n\tPlease wait, file is being uploaded...\n")
		os.system("rm ./log_data/log_code.txt > /dev/null 2>&1")
		os.system("curl --upload-file ./log_data/log.txt https://transfer.sh/"+log_name+"_log.txt > ./log_data/log_code.txt")
		os.system("sed -i 's/https:\/\/transfer.sh\///g' ./log_data/log_code.txt")
		os.system("sed -i 's/\/"+log_name+"_log.txt//g' ./log_data/log_code.txt")
		print("\n\n___________________________\n") 
		print("\nTell your favourite developer those:\n")
		print("User name: "+log_name)
		f = open("./log_data/log_code.txt","r")
		for line in f:
			code = line
		print("\nUser code: "+code)
		print("\n___________________________\n") 
		raw_input("\n\nHit 'enter' to continue\n\n")
		main_menu()
	if selection=='n' or selection =='no':
		print("\n\n\tOK - you log file is stored under 'log.txt' name in RH-ota directory.")
		raw_input("\n\n\tHit 'Enter' to continue\n\n")
		main_menu()
	else:
		log_send()

Basically script dumps contents of the files to one log file and that that file can be uploaded automatically to the cloud. User inputs his/her name and after upload code is generated - is is a part of the web address.

Than developer can just type appropriate address with generated code into the browser or use simple downloading python script to download log file. Tested today with Casey Pinochi - works.
I am sure that there are better/dedicated logging libraries (real time etc) but that way works for me - at least now. 

Developer's "client" program:

import os
import sys

print("\n")
user_name = str(raw_input("User name: "))
print("\n")
user_code = str(raw_input("User code: "))
print("\n")

os.system("rm "+user_name+"_log_old.txt > /dev/null 2>&1")
os.system("cp "+user_name+"_log.txt "+user_name+"_log_old.txt > /dev/null 2>&1")

os.system("curl https://transfer.sh/"+user_code+"/"+user_name+"_log.txt -o "+user_name+"_log.txt")

while True:
	print("\n")
	sel = str(raw_input("Open file now? [y/n]"))
	if sel == 'y':
		os.system("less "+user_name+"_log.txt")
		break
	if sel == 'n':
		break
	else:
		continue

Thought that you may be interested in something like this. It cut out this "show me conent of your config file": discussion.

Cheers

**Comment by HazardCreative** [comment]
See #224

**Comment by szafranski** [comment]
Cool. especially that curl based uploading may be helpful - I assume that there are more proper ways to just log anything.

**Comment by HazardCreative** [comment]
At this time there is no plan for RotorHazard to connect to a central server, so there's no good location to send log files to.
