### ISSUE TITLE
After updating to Commits on Mar 21, 2020 : Does not register laps

### ISSUE THREAD

**Issue by BoLtWD** [RotorHazard/RotorHazard#281]
Version: 2.2.0 (dev 0)
Server API: 27
Node API: 22
Commits on Mar 21, 2020
Windows 10 using Chrome as browser

Issue: 
After updating to comments above the race page does not register laps during a VTX pass also can't add a lap manually

**Comment by HazardCreative** [comment]
Did you have a pilot defined in the heat for that channel? The default is "none" (which won't allow registering laps against) and the existing code doesn't yet carry over heat assignments from an existing database.

**Comment by BoLtWD** [comment]
Dho!  Yep thats what it was
