### ISSUE TITLE
Streaming overlay

### ISSUE THREAD

**Issue by JannikFK** [RotorHazard/RotorHazard#282]
It would be nice with a dedicated page or setup to use as a stream overlay.
As a start I compiled a list based off of running LiveTime and using its streaming overlay in our league for 2 years now.

Before the race:
- List of pilots
- Pictures?
- Current fastest / rank

During race:
- The pilot areas should be static to match the underlying DVR feed. 3x2 or 2x2 view. LiveTime lets you chose specify this in the URL which works good enough.
- The second way people set up streams is to create individual scenes for each pilot, and crop the dvr + overlay so that you can only see the pilot you want. Then assemble them all in a new/seperate race view.
- Should be simple to see the race progress both by pilot and an overall list.
    - Pilot position
    - Laps / fastest lap

After the race:
- Short summary with placements, laps and times

This is a sample of how our current stream is setup. For inspiration.
![stream_rfl](https://user-images.githubusercontent.com/18471533/77232973-9f524900-6ba4-11ea-8727-b160c11322b8.png)

**Comment by WrathPak** [comment]
I really like this idea. I don't have much to add at this point, but have been building up the components necessary to live stream from the field. I'll think on this and see if there is anything else we may want to add.

**Comment by fpvMarkS** [comment]
This is great .. exactly what I need ...
So how is this overlay implemented ?
Is there a script or file I need to get going ? Once I learn I can put together how to  document... ﻿

**Comment by WrathPak** [comment]
I think having a page in the RH interface dedicated to streaming could work with Option #1 proposed above. Items in static placements on the RH interface, set as a scene in OBS. DVR feeds aligned as separate scenes to that.
