### ISSUE TITLE
No speech call on iOS

### ISSUE THREAD

**Issue by HazardCreative** [RotorHazard/RotorHazard#29]
Per commenter on Facebook. I don't have access to an iOS device, so I can't reproduce.

**Comment by HazardCreative** [comment]
I expect this is related: https://github.com/scottgchin/delta5_race_timer/issues/82

**Comment by ethomas997** [comment]
Hmm, I wonder if this will start to become an issue on Firefox?:

https://news.slashdot.org/story/19/02/04/1945230/firefox-to-block-auto-playing-audio-starting-march-2019
> Starting with Firefox 66 -- scheduled for release on March 19, 2019 -- Mozilla plans to block auto-playing audio on both desktop and mobile -- a feature it began to test on Nightly builds last year. The new rule will apply to any website that plays audio without user interaction in advance -- such as a user clicking a button. The audio autoplay ban will apply to both HTML5 audio and video elements used for media playback in modern browsers, meaning Firefox will block sound coming from both ads and video players, the most common sources of such abuse. Mozilla's move comes almost a year after Chrome took a similar decision to block all auto-playing sound by default with the release of Chrome 66 in April 2018. Microsoft similarly announced plans to block auto-playing sounds in Edge, but the feature never made it to production.

**Comment by HazardCreative** [comment]
Probably depends on implementation. We're not using audio or video elements in the HTML sense. Speech synthesis and generated tones might continue to fly under the radar.

One of the last bugs fixed before launching as RotorHazard was Chrome/Android failing to play race end tones. My best guess is that after a full minute, audio was being prohibited again until there was some interactivity. Switching to generated tones prevented that issue.

**Comment by HazardCreative** [comment]
Does adding globalAudioCtx.resume(); make any difference to iOS?  0f9ffd3

**Comment by DevnathNair** [comment]
@HazardCreative I believe this issue can be closed as it has been resolved for me (iOS 12.1.2) as of the latest stable release (v2.0.0)

**Comment by HazardCreative** [comment]
Closing for lack of new reports.
