### ISSUE TITLE
Commits on Apr 1, 2020 error on starting server

### ISSUE THREAD

**Issue by BoLtWD** [RotorHazard/RotorHazard#290]
Commits on Apr 1, 2020

After updating to above when I run the server I get this error
![Untitled](https://user-images.githubusercontent.com/25492262/78178676-ed463700-7457-11ea-88d6-8a9a56cb23bc.jpg)

**Comment by BoLtWD** [comment]
Note I have the RTC fitted

**Comment by BoLtWD** [comment]
I re attempted updating the files again without database or config files changes, still the same issue as above. As its referring to a module still wondering if this is connected to the RTC I have fitted.

**Comment by HazardCreative** [comment]
#292 will probably fix this.

**Comment by BoLtWD** [comment]
Thank you

**Comment by BoLtWD** [comment]
Fixed thank you
