### ISSUE TITLE
Rounding error - leaderboard vs laps list

### ISSUE THREAD

**Issue by ethomas997** [RotorHazard/RotorHazard#312]
There seems to be a difference in how lap-time values are rounded on the leaderboard vs in the laps list.  In the attached PDF, the fastest lap on the leaderboard is displayed as 0:35.608, whereas in the laps list it is displayed as 0:35.609 (ET lap 42).  The attached database file can be used to generate the issue.

[RH_Results_20200425.pdf](https://github.com/RotorHazard/RotorHazard/files/4537511/RH_Results_20200425.pdf)

[RH_database_db_20200425.zip](https://github.com/RotorHazard/RotorHazard/files/4537515/RH_database_db_20200425.zip)

**Comment by HazardCreative** [comment]
I've seen this when recalculating a race also.

For that database row:
lap_time is 35608.74371049926
lap_time_formatted is 0:35.608

So 35.608 is wrong.

I think we need to look for potential flooring rather than rounding in any conversion from lap_time to lap_time_formatted.
