### ISSUE TITLE
Per-pilot attributes

### ISSUE THREAD

**Issue by HazardCreative** [RotorHazard/RotorHazard#317]
Originally suggested by RogerBFPV.

> Race directors can define attributes for a pilot such as 'Registered' , or passed tech, paid to help with bookeeping, The attribute named 'Registered' is special as only 'Registered' pilots will appear in the pilots list of heat pulldowns.
>
> To 'un-Register' all pilots, specify Registered in text field and press the Delete Attribute button.

Suggested code exists in PR #259

**Comment by RogerBFPV** [comment]
We need a way to only show a subset of pilots in the 'heats' pulldown when assigning channels. 

I used my branch for the last race, where I have about 40 pilots in my database.  It was so much easier to look in MultiGP, and simply clicking a checkbox that the pilot is registered, for the 19 pilots that were actually registered for the race.

Then the 'heats' the pilot pulldowns only had the 19 pilots to choose from and not 40..

**Comment by HazardCreative** [comment]
Yes, that's probably the most important part of the original—so much so that perhaps an 'active' flag might be reasonable as a separate feature instead of rolled into more generic attributes.

**Comment by RogerBFPV** [comment]
:)  however you want to merge it in is fine.   The generic attributes are useful for me, (I use attributes to mark which pilots have paid, and which ones have passed tech inspection)..

**Comment by HazardCreative** [comment]
Added with [7f27446](https://github.com/RotorHazard/RotorHazard/pull/721/commits/7f27446c3d472d4700d360f0a82300dc186eaf46)
