### ISSUE TITLE
Rotorhazard GUI on iOS safari is missing navigation section

### ISSUE THREAD

**Issue by DavidJJ** [RotorHazard/RotorHazard#325]
When using iPhone to run Rotorhazard, there is no navigation panel/bar to allow you to jump between run / marshal / admin.   The only want to navigate between sections is to go back to the welcome page.   

It also uses so much CPU that it overheats an iPhone 6s.

**Comment by HazardCreative** [comment]
The menu visibility should be fixed as of 4024957. Can someone with an actual device please confirm?

CPU load should be tracked as a separate issue.

**Comment by HazardCreative** [comment]
Closing with no dissenting information in ~30 days.
