### ISSUE TITLE
RaceBand1 not working

### ISSUE THREAD

**Issue by Cuxx** [RotorHazard/RotorHazard#328]
Everything is working except RaceBand 1. At first I thought the node died or I forgot to update the arduino of node 1, but I also tested RB1 on node 2,4,6 & 8, same issue. The value changes a bit, sometimes it's in the ~100 area, sometimes in the 80s. But it's always +/- 5 and you can't see any spikes during a real run.

I also reflashed the nodes again, but didn't solved the issue.
Same hardware on 2.0.2 was ok. Will downgrade to verify the hardware.

I made two videos about it:
2.1.0: https://www.youtube.com/watch?v=6tqgL1GbUJM 
2.1.1: https://www.youtube.com/watch?v=env9QyYf4fU

**Comment by HazardCreative** [comment]
This data is far less noisy than I would expect; RSSI is generally very messy. Can you provide more information about the setup of your race environment and how your timer is constructed?

**Comment by Cuxx** [comment]
Pi4 with a prototype board from philip seidel.
8 nodes + 8 arduino pro micro (fun to upgrade with external FTDI ;))
The nodes have an extra stepdown with 3.3v
the housing is completly shielded (except the lid).

https://imgur.com/a/0Ak1dbR

**Comment by HazardCreative** [comment]
RH doesn't change its operation based on frequency at all. Different RSSI levels on different frequencies is normal, but it's a little unusual that R1 is much higher. Is it possible that something else nearby is broadcasting on R1? WiFi operates in this range for example. Have you taken the timer to other physical locations?

**Comment by Cuxx** [comment]
Tested it on 3 different locations and also had this issue. Downgraded to version 2.0.2 and there it was ok. But I noticed some strange behavior on rx2 (random highs for several seconds). Swapped it with rx3 and then both were strange, but mostly the original rx2 (rx3 now). after that I put it on position 8 and had these issues on rx7 & rx8 (original rx2). After removing rx2 entirely, everything is ok. Even on 2.1.1. Also tried to resolder the pins worked for rx2.

**Comment by HazardCreative** [comment]
So removing a problematic RX module resolved the issue? It sounds like something in that RX5808 is faulty and it's causing noise in the system when tuned low. Please report back if replacing the hardware resolves it.

**Comment by Cuxx** [comment]
Hi, I had an awesome training session today with 40 heats & 4 pilots (node 1-4 with RB 1,3,5,7). The system had only 7 nodes (without the original rx2). RX 5-7 were disabled (no frequency). 

I just inserted a new rx and everything is still fine, even after one hour of idleing. I never expected that a dead rx5808 could cause such problems. Thanks for your time & help ❤️

**Comment by HazardCreative** [comment]
Awesome. Glad we got it solved!
