### ISSUE TITLE
Heat generator input/output class selectors do not update on class renaming

### ISSUE THREAD

**Issue by RogerBFPV** [RotorHazard/RotorHazard#332]
In events and classes:  create class 1, and name it MyClass1. 

Then goto heats, -> heat generator.. The Input (Class) pulldowns does not show the name MyClass1..

In events and classes: create class 2 and name it MyClass2
Then goto heats, -> heat generator.. The Input (Class) pulldowns now shows the name MyClass1 but does not show MyClass2 (only Class 2)..

workaround:  create 1 extra class to get your name to show in the heat generator.

**Comment by HazardCreative** [comment]
Thanks for the clear report.

**Comment by HazardCreative** [comment]
Bug is actually that any heat name changes are not immediately reflected in class input and output dropdowns since a global class refresh isn't triggered back to the active client on the name change events.
