### ISSUE TITLE
Must allow for class 'win condition' to be changed after race data for a race format that has been saved

### ISSUE THREAD

**Issue by RogerBFPV** [RotorHazard/RotorHazard#333]
It is too limiting to force the user to know ahead of time the exact win condition that they may want to use for the heat generator..  

For example, I had set a practice class, with 'open practice' as the race format.   It defaulted to a 'none' win condition..  

After practice, I decided I wanted to create heats based on how those pilots practiced.. BUT, I could not change the win condition..

This is also very limiting because some directors may use the same race format for everything. but now the heat generator is tied to race format definition.. 

There are 2 possible solutions:
a. in heat generator, allow the race director to select the win condition.. (like I had originally coded).
OR
b. In race format: allow for the win condition to be changed at any time.

**Comment by HazardCreative** [comment]
Setting the condition before running races is good practice. This gives pilots an understanding of what's important to focus on while flying. Leaderboards are generated which pilots will use to understand their position relative to others and how hard they must push to make a difference in that rank. OSD messages are also built based on current race format options. It's better for the pilots to have an accurate understanding as the event occurs. (Previously RH simply displayed all available leaderboards, but as of the latest code, the primary ranking condition is always displayed first.)

I do prefer that organizers maintain complete control over their events, so I'm thinking that this might be made available through a marshaling option similar to what's intended with #141. It should be possible—but with the understanding that it's an alteration of rules and results.
