### ISSUE TITLE
Disable Heats

### ISSUE THREAD

**Issue by Cuxx** [RotorHazard/RotorHazard#337]
It would be super awesome, if it's possible to disable old heats. For example if you have 2 Heats but wanna swap one pilot from one to the other heat. In that case you have to copy both heats and swap the pilot. It would be nice to disable the old/wrong/deprecated heats, so they wouldn't be accessible anymore in the "run" view. 

In that regard it could be helpful to create a function to sort the heats, so you don't have to duplicate all heats to remain in the old sequence.

**Comment by HazardCreative** [comment]
Opened #351 as a separate issue.
