### ISSUE TITLE
Results Calculation broken after first calculation. Migrated from 2.0.2 up to 2.2.0beta2

### ISSUE THREAD

**Issue by Cuxx** [RotorHazard/RotorHazard#338]
I migrated my installation & database from 2.0.2 to 2.2.0beta2. I had basically every version between these two versions. I only deleted Races & Heats after the training sessions. But today with 2.2.0beta2 I had the issue that the results worked just one time. When I opened it again, after something has changed (new races or deleted laps) there were no results. I had to reboot to get results again.

Link to the db: [https://drive.google.com/file/d/1raZR1o27ANY9VzJ1H0icFYVdxkbrwCJn/view?usp=sharing](url)
Link to a video to show the issue: [https://www.youtube.com/watch?v=dGPB-u9Zh_I](url) (Maybe I shouldn't do videos at 2am in the night :D )

**Comment by HazardCreative** [comment]
Do you have the log file as well? /src/server/logs

**Comment by Cuxx** [comment]
sure: 
[alllogs.zip](https://github.com/RotorHazard/RotorHazard/files/4773784/alllogs.zip)

**Comment by HazardCreative** [comment]
I can't seem to download your database file; looks like permissions are off.
(Also, FYI, your links don't click through. In the markdown, you put the text in [ ] brackets and the URL in ( ) parentheses).

**Comment by Cuxx** [comment]
Sry, thanks for the info. I changed the permissions. 

BTW today with a fresh DB and ~35 Heats I didn't had the issue at all.

**Comment by HazardCreative** [comment]
Thanks for the information.

- Loaded the attached database
- Loaded results page (OK)
- Started new race, added some laps
- Stopped race
- Saved race
- Loaded results page (OK)
![image](https://user-images.githubusercontent.com/7169527/84578875-1b6cbf00-ad97-11ea-96a7-7bd62f1b51de.png)


Are any other steps needed to reproduce the issue?

**Comment by Cuxx** [comment]
Yes that's correct. I planned to try it again. But before I reinstalled 2.2.0beta2 again (2 be sure it's a clean install) and copied the settings and the new database (which worked the whole day today). But the migrated db had the same issue. 

Are there any other temporary files that can cause this issue? I mean I migrated settings & db from 2.2.0-beta.2 to 2.2.0-beta.2 now

**Comment by HazardCreative** [comment]
You triggered the issue using the same database as above?

**Comment by Cuxx** [comment]
Yeah I triggered it with the one above (migrated from 2.0.2 up to 2.2.0-beta2
and with the clean DB I cleaned two days ago migrated from 2.2.0-beta2 to 2.2.0-beta2.

But when I clean the db completely after migration and create everything new it's ok.

**Comment by HazardCreative** [comment]
The DB above already has race 50 in it. It looked like your video triggered it while adding race 50.

Interesting that moving from 2.2.0-beta.2 could trigger it. The system doesn't see copying from one 2.2.0-beta.2 install to another as a migration; the DB would pass all of the consistency and API level checks. There aren't any temporary or state files generated by RH (beyond logs and python's own .pyc).

**Comment by Cuxx** [comment]
Updated to lateste 2.2.0 but still have the issues sometimes. It appears randomly. But I still have to reinstall my pi. Hopefully I have the time next week, so I can report if I still have the issue with a clean install.

**Comment by Cuxx** [comment]
Had it again several sessions. Also built another Tracker and there I have the same issue.
In this case: Latest Raspbian, Pi3b, RH-OTA installation

**Comment by HazardCreative** [comment]
I would love to track this down, but I need some reproduction steps that work consistently.

**Comment by Cuxx** [comment]
OK with this backup I can trigger the issue on both trackers all the time (ok only tested it 6 times in a row :D)

1. open results page
2. go to marshal and edit Heat 1 - Round 31 - Cuxx (add or delete one of the laps)
3. open results page again and wait forever for the recalculation ;)


[Database](https://drive.google.com/file/d/1fxVYzdai6CqdtGD8JRs4zyS-wjf-f2CQ/view?usp=sharing)

**Comment by HazardCreative** [comment]
Thank you for this test case. I have now reproduced and isolated this issue. Working on a fix.
