### ISSUE TITLE
Connected and active VRx device reports "connection: 0"

### ISSUE THREAD

**Issue by HazardCreative** [RotorHazard/RotorHazard#340]
Further investigation is needed to determine the cause.

**Comment by ryaniftron** [comment]
Any steps to reproduce?

**Comment by HazardCreative** [comment]
All I have to do is connect the VRx I have on hand.
```
Found MQTT device: CV_D40D7A286F24 => 1
Device CV_D40D7A286F24 is not yet configured by the server after a successful connection. Conducting some config now
Receiver Reply CV_D40D7A286F24 => 91LFNAU%
Receiver Data Updated: {'connection': '0', 'cam_forced_or_auto': 'A', 'needs_config': True, 'lock_status': 'U', 'chosen_camera_type': 'N', 'valid_rx': True}
status_static data: CV_D40D7A286F24 => {"dev":"rx",  "ver":"TODO_VER",  "fw":"TODO_FW",  "nn":"Hazard%252BCV"}
No node number available for CV_D40D7A286F24 yet
status_variable data: CV_D40D7A286F24 => {"node_number":"1"}
Performing initial configuration for CV_D40D7A286F24
Set frequency for CV_D40D7A286F24 to 5732
```

![image](https://user-images.githubusercontent.com/7169527/85488011-973ae880-b59b-11ea-888d-bcf60913e456.png)

**Comment by HazardCreative** [comment]
@ryaniftron what information do you need to further debug?

**Comment by ryaniftron** [comment]
I believe this is no longer an issue and cannot replicate the issue. There is a chance, when things are first connecting, it will show this, but as the data fields get updated after a few seconds, it should go away.

**Comment by HazardCreative** [comment]
Closing unless new information becomes available.
