### ISSUE TITLE
Add the ability to use the websockets API to run a race with virtual nodes

### ISSUE THREAD

**Issue by skyfpv** [RotorHazard/RotorHazard#343]
It would be useful for Rotor Hazard to allow clients to act as timing hardware and communicate lap times via a webSocket or other network API. Currently it seems like most of this could already be done by someone implementing the existing webSocket API. The main change would be that lap time timestamps could be recorded on the client so the network jitter of the webSocket doesn't affect race outcomes.  

Here are some things this would let us do.
- Host simulator races managed by RotorHazard
- Host mix reality races where real quads and sim quads compete with each other
- Host multi-site races where we have two real life events synced with each other. This would possibly let us do 16+ pilots at a time (just thinking into the future here). 

I'm curious what your thoughts are and how difficult this would be to implement

**Comment by pulquero** [comment]
Support for this exists in the guise of writing your own hardware interface impl and using the RH_INTERFACE environment variable to point to it. In fact the existing interface supports recording of node data to file, which can then be played back using the MockInterface.

I would encourage you to take the MockInterface as a starting point and see where the blockers are.

**Comment by HazardCreative** [comment]
Extending RH past 8 nodes will carry some added work as many data structures are fixed, but an initial implementation can occur on a mock (or live) node set to an unused channel. (I've wanted to look into those fixed structures anyway.)

Using external sources carries a few caveats:
* RH will be unable to reconstruct laps from external sources (even if they provide RSSI)
* RH will be unable to announce winners in real time
