### ISSUE TITLE
RHInterface requires sequential node numbers

### ISSUE THREAD

**Issue by HazardCreative** [RotorHazard/RotorHazard#345]
Ran timer with node number 1, 2, 3, 4, and 6 (missing 5). Got the following frequently:

```
2020-06-17 22:35:31.062: RHInterface [ERROR] Exception in RHInterface update_loop():
Traceback (most recent call last):
  File "../interface/RHInterface.py", line 164, in update_loop
    self.update()
  File "../interface/RHInterface.py", line 296, in update
    data_logger = self.data_loggers[node.index]
IndexError: list index out of range
```

Timer should run with nodes at any valid address.

**Comment by ryaniftron** [comment]
I'll take this one

**Comment by ryaniftron** [comment]
Thanks for the reminder. Does it need to support a changing number of sparsity of nodes on runtime or only on boot?

**Comment by HazardCreative** [comment]
On startup only. There are many internal assumptions that the number and ordering of nodes will not change. There is no intent to allow hot-swapping in the future. Misaligning an Arduino by one pin can fry it (ask me how I know) so it's best done with more care; taking the system offline helps facilitate this,

**Comment by ryaniftron** [comment]
Is there a way, using the simulator, to get sparse nodes to reproduce this?
