### ISSUE TITLE
Need Undo for delete laps

### ISSUE THREAD

**Issue by HazardCreative** [RotorHazard/RotorHazard#35]
When laps are coming in quickly and someone is trying to maintain the integrity of the list, it's easy to accidentally delete a lap you wanted to save. An option to restore them would be very helpful.

This will probably mean either keeping the laps stored in the CurrentLaps table with a 'valid' flag, or creating a function that allows manually inserting laps by time.

**Comment by Klaus-Michael** [comment]
The most convenient way would probably be to just flag the lap as deleted and keep it in the current table but ignore it for all calculations. When transferring the data to the saved table those laps can be omitted.

**Comment by HazardCreative** [comment]
Yes, I agree. However, adding the option for a manual lap insert could have other utility. For example, one race management software I used previously allowed the operator to split a lap into two. This was a very useful operation for managing results that I certainly would not mind having available.

**Comment by HazardCreative** [comment]
Deleted laps can now be recovered by the marshaling feature.
