### ISSUE TITLE
Upgrade does not copy custom images

### ISSUE THREAD

**Issue by ErikBorra** [RotorHazard/RotorHazard#356]
When upgrading, custom images in src/server/static/image/ are not copied from RotorHazard.old to RotorHazard

**Comment by HazardCreative** [comment]
I was just thinking about this yesterday and I want to explore if there's a standard practice here that should be followed.

**Comment by ErikBorra** [comment]
Either make a dedicated folder, such as ext or res, or compare expected folder structure with old folder structure in ota update.
