### ISSUE TITLE
S32 BPill Schematic

### ISSUE THREAD

**Issue by ethomas997** [RotorHazard/RotorHazard#357]
I've been working with a friend on a new PCB design that will use a single STM32 processor instead of multiple Arduinos.  See the [attached initial schematic](https://github.com/RotorHazard/RotorHazard/files/4876465/RotorHazard_S32_BPill_schematic_v0.1.pdf) for this "S32 BPill" board.  Here is a features summary:

RotorHazard S32 BPill Board

* Instead of multiple Arduinos, the board has a single STM32 processor

* Board size and mounting will be the same as the "standard" Delta5 PCBs

* Supports 1 to 8 RX5808 modules.  (We're planning on seeing if we can mount the RX5808 modules vertically using small sub-boards, and get up to eight of them in there.  A layout with four of the modules mounted flat can also be an option.)

* Communication between the STM32 processor and the Raspberry Pi is via serial-port link, running at 921600 baud.  The S32 board can also be connected directly to a computer (via USB-to-Serial/FTDI dongle)

* The STM32 processor is on a 40-pin module, attached to the board via sockets.  These are commonly known as "Blue Pill" modules, and are readily available and inexpensive

* The board has a 40-pin (2x20) header for connecting to the Raspberry Pi, via a ribbon cable with female ends

* The STM32 processor is in-circuit programmable, able to be flashed using the Raspberry Pi

* The same node source code will support both the S32 and the (existing) multi-Arduino boards

* Supports power/battery monitoring and a buzzer (low-battery alarm)

* Mounting locations for (optional) INA219 and BME280 modules, connected to the Raspberry Pi I2C bus

* Optional "extra" LED

* Connector pads for LED-strips -- one to Raspberry Pi, one to STM32 processor

The same RotorHazard source code (server and node) will work with both the Arduino and S32 boards; I have a v2.2.0 devel branch here:  https://github.com/RotorHazard/RotorHazard/tree/BPill_2.2.0

I've got the code running on a test rig with two RX5808 modules attached.  If anyone wants to wire up something similar and needs help, let me know.  Our next step is to do the PCB layout.

Any feedback is welcome; feel free to chime in.

--ET

Attachment: [RotorHazard_S32_BPill_schematic_v0.1.pdf](https://github.com/RotorHazard/RotorHazard/files/4876465/RotorHazard_S32_BPill_schematic_v0.1.pdf)

**Comment by pulquero** [comment]
Could an old fc be hijacked for this, essentially it's just an stm32?

**Comment by ethomas997** [comment]
@pulquero You could probably do it with an old flight-controller board, but given that "Blue Pill" boards [can be had for less than $10](https://www.ebay.com/sch/i.html?_from=R40&_trksid=m570.l1313&_nkw=blue+pill+STM32F103C8T6&_sacat=0&LH_TitleDesc=0&_osacat=0&_odkw=STM32+blue+pill) I wouldn't see it as worth the effort to re-purpose.

**Comment by ethomas997** [comment]
A functional test rig can be built by attaching one or two RX5808 modules and an FTDI to an STM32F103C8T6 Blue Pill module, following the connections on the schematic for those components (except connect the RX5808 "+5V" to the "5V_PILL" wire on the FTDI).  The attached "[BPill_v2.2.0_node.bin](https://github.com/RotorHazard/RotorHazard/files/4876901/BPill_v2.2.0_node.bin.zip)" file can be flashed to the Blue Pill module using a program like [stm32flash](https://sourceforge.net/p/stm32flash/wiki/Home).  Connect the FTDI to a PC and run the [BPill branch](https://github.com/RotorHazard/RotorHazard/tree/BPill_2.2.0) of the server, configured to the serial port for the FTDI.

![BlackPillNode_testRig_20200223_2_s](https://user-images.githubusercontent.com/3822131/86558395-3611fe00-bf27-11ea-8ec2-3a33c598931e.jpg)
[BPill_v2.2.0_node.bin.zip](https://github.com/RotorHazard/RotorHazard/files/4876901/BPill_v2.2.0_node.bin.zip)

**Comment by GoingForGold13** [comment]
Hi there, this is awesome!

if I may, I have some questions regarding this schematic :)

1. why are the RX5808s (on all the boards) powered with 3.3V instead of 5V?
2. why do you think you need a subboard for the vertical mounting of the RX5808s? With 90° pin headers, that would be easy. Or are you looking at connecting the two GND pins on the antenna side?
3. What is the idea for the Blue Pill LED Strip header?

Thanks!

**Comment by ethomas997** [comment]
@GoingForGold13 Thanks; happy to answer.
1. The current PCB also powers the RX5808 modules at 3.3V. The idea is to let them run a bit cooler, and they seem to operate fine at 3.3V.
2. The thinking is that with a sub-board it will be easier to assemble/disassemble, will be sturdier, and there will be a ground plane under each module.
3. This will allow for LED-strip support when there is no RPi in the system, and potentially a separate LED strip.  Also, any I/O pin that's broken out could be re-purposed to other uses.

**Comment by sl33pydog** [comment]
So @ethomas997 the led strip for no raspberry pi in the system could be for visual effects or gate activated events that don't report data back to the main nodes?

Why not use an esp32 for this instead and have wifi connectivity built in?  The wifi and bt could be turned off in code, with a switch or remotely if needed.

**Comment by ethomas997** [comment]
@sl33pydog LED-strip support is not yet coded in the nodes, so it could be anything we can dream up. :]

I expect it could use an ESP32 board instead.  At this point it would require reworking the schematic and the node code.

--ET

**Comment by sl33pydog** [comment]
@ethomas997 instead what about adding lines for an external esp8266 like in this document?  

https://circuitdigest.com/microcontroller-projects/interfacing-esp8266-with-stm32f103c8-stm32-to-create-a-webserver

Might not require much code rewrite or schematic changes.

I think with the other issue I wrote about having a remote node for Video capture and your plan for the Arduino replacement/expansion board we could have a remote device trigger board or maybe a cheaper multi node.  I always thought it would be cool to have gates that physically alter either remotely triggered by the race organizer or by rssi.

**Comment by ethomas997** [comment]
@sl33pydog I'm not against the idea of supporting an esp8266, but at this point we have basically every I/O pin on the BPill committed.  If there's something like that but 5V tolerant, it could plug in to the FTDI-Link connector on the board.

**Comment by sl33pydog** [comment]
@ethomas997 I could make something for that or just bake in a 3.3V reg forking the schematic you have.  For the moment then I'll see if I can make an esp32 work with michaelfpv and the VRX protocol that's out there for the CV2.

**Comment by ethomas997** [comment]
I've posted branches with the changes for S32 BPill applied to the current master (I plan on updating them as needed).  There's one for server (python code) and one for node, separated to make it easier to update:

BPill_dev_server:  https://github.com/RotorHazard/RotorHazard/tree/BPill_dev_server
BPill_dev_node:  https://github.com/RotorHazard/RotorHazard/tree/BPill_dev_node

When the PCB becomes a reality we'll look to apply these changes to the master branch.  The new code will support both the current boards (with Arduinos) and the new design (single STM32 processor).

**Comment by ethomas997** [comment]
Support for S32_BPill has been merged in and resource info on the PCB has been [posted](https://github.com/RotorHazard/RotorHazard/tree/master/resources/S32_BPill_PCB).
