### ISSUE TITLE
Warnings and notifications should disappear after a few seconds

### ISSUE THREAD

**Issue by ErikBorra** [RotorHazard/RotorHazard#358]
When using the (awesome) Marshall page, a notification pops up after clicking add to node. The notification does not disappear by itself, you need to click x. Pretty annoying when tuning multiple nodes.

**Comment by HazardCreative** [comment]
Until there is a UI control to pause or adjust the amount of time that messages remain, adding an auto-dismiss delay would cause the UI to fail WCAG 2 (web accessibility). See https://www.w3.org/WAI/WCAG21/quickref/#enough-time . Maintaining level AA compliance is important as that's the legal standard in most places.

You can also dismiss messages with the ESC key.

**Comment by ErikBorra** [comment]
I guess a three to five second delay would suffice, but I guess we can disagree here without a fight :) The ESC tip is a good one, thx.

**Comment by HazardCreative** [comment]
I'm not disagreeing, just adding some context. Adding a UI control as described could be a good idea.

**Comment by DavidJJ** [comment]
Another option/ suggestion would be to make the notification bar 2-3 notifications high and auto-scroll to see the latest notifications.  Then add a "dismiss all" button.   This should still pass accessibility standards and not require clicking esc / x multiple times.
