### ISSUE TITLE
The current page should clearly indicate which heat is on

### ISSUE THREAD

**Issue by ErikBorra** [RotorHazard/RotorHazard#359]
The 'current' page currently does not show clearly which heat is in progress and which heat is next. For pilots wanting to know when they are on, this would be good information to have.

**Comment by HazardCreative** [comment]
Current heat is in the top-most blue bar. RH doesn't know what heat is next.

**Comment by ErikBorra** [comment]
I guess that's then my main gripe with the system at the moment. It works absolutely great as a tracker! But could use some work for event management: scheduling rounds and heats per round (apart from the one next up), adding count-downs between races and announcing which race is next.

**Comment by HazardCreative** [comment]
Sounds good. I'm closing this item since the spectator page does show the information, but feel free to open a separate issue to discuss whole-event scheduling.
