### ISSUE TITLE
/decoder does not have a need for audio control

### ISSUE THREAD

**Issue by ErikBorra** [RotorHazard/RotorHazard#364]
When using Livetime and /decoder, you are using Livetime as the event manager and RH as a standalone timer. There is thus no need for audio on the /decoder page. Livetime already announces pilot names, etc.

**Comment by HazardCreative** [comment]
The decoder page does not have voice controls and does not make voice announcements nor start/end tones, it only provides tones during enter/exit events.

**Comment by ErikBorra** [comment]
Sorry for not being clear enough. Crossing tones are already provided by Livetime. Not sure whether there still is a need on the /decoder page for its own notifications.

**Comment by HazardCreative** [comment]
Does it provide tones both for gate entrance and gate exit events? Is there an option for forcing a first-crossing tone?

**Comment by ErikBorra** [comment]
No, just crossing.

**Comment by HazardCreative** [comment]
I think I will leave them in place then as they are useful tools for understanding if the timer is functioning properly. They default off and shouldn't bother anyone.

**Comment by ErikBorra** [comment]
OK, feel free to close the issue.
