### ISSUE TITLE
Canceling a scheduled race does not stop count-down and announcements

### ISSUE THREAD

**Issue by ErikBorra** [RotorHazard/RotorHazard#366]
When clicking 'cancel' next to schedule race in /race, the count-down timer and the announcements about the time continue. When the timer reaches 0, the race is not started (the latter is desired behaviour).

**Comment by ErikBorra** [comment]
Added this as a quik fix in race.html:
```$('#cancel_schedule_race').click(function (event) {
     /* Quick fix */
     var data = {
          m: 0,
          s: 0
     };
     socket.emit('schedule_race', data);
     /* End quick fix */
     socket.emit('cancel_schedule_race');
})
```

**Comment by HazardCreative** [comment]
Thanks! This was working before so I expect there's another solution, but this will definitely help track it down.
