### ISSUE TITLE
Max Laptime for Trainint mode

### ISSUE THREAD

**Issue by Cuxx** [RotorHazard/RotorHazard#368]
It would be awesome to define a max laptime or the possibility to delete laps (without adding the time to the next lap). This could be usefull for a training mode. Start the tracker and run multiple packs without screwing up the average laptime. Only problem could be the 3lap consecutive time :)

**Comment by ErikBorra** [comment]
@Cuxx yeah, running into something similar with training sessions, as described in #370

**Comment by HazardCreative** [comment]
Similar functionality now exists by plugin: https://github.com/HazardCreative/RotorHazard-Idle-Race_Handler
