### ISSUE TITLE
Voice announcements on mobile only work when phone is not asleep

### ISSUE THREAD

**Issue by ErikBorra** [RotorHazard/RotorHazard#371]
I had a problem with voice announcements when running a race/session using my phone. While beeps would work, voice announcements would not. I figured out that when the screen is active (not asleep), voice announcements will work just fine. Maybe this is information that could be added to https://github.com/RotorHazard/RotorHazard/blob/master/doc/User%20Guide.md#audio-control

**Comment by HazardCreative** [comment]
Browsers are very picky and inconsistent about what they do and do not allow when it comes to audio. Going to idle mode/sleep often triggers a shutdown of the browser audio system. I have sent feedback about this to the developers of Chrome, Firefox, and Safari. If anyone knows of a way to keep the audio running more consistently I will be happy to hear it.

**Comment by ErikBorra** [comment]
I now just use the display settings on my phone to not let the screen fall asleep.On Jul 20, 2020 15:32, Hazard Creative <notifications@github.com> wrote:
Browsers are very picky and inconsistent about what they do and do not allow when it comes to audio. Going to idle mode/sleep often triggers a shutdown of the browser audio system. I have sent feedback about this to the developers of Chrome, Firefox, and Safari. If anyone knows of a way to keep the audio running more consistently I will be happy to hear it.

**Comment by HazardCreative** [comment]
This is likely the best workaround. There's little RH can do to affect the browser's behavior on this. (And it already tries.)
