### ISSUE TITLE
Master-Slave do not communicate with each other

### ISSUE THREAD

**Issue by rodcar125** [RotorHazard/RotorHazard#374]
Hi!

I just did fresh intsalls with stable version 2.2.0 on both systems with new PCBs. All working fine but the coms between master/slave.

When i start a race on master, nothing happens in slave. Also, in Settings-> System, the slave address is shown but time since last contact is increasing eery second.

On the master log file, line 37, it says connected to slave but this line is always shown, with or without a slave timer on the network.
Same file, line 37, "reads requests package is not installed" which i believe this might be the issue

In zip you can find server logs for master and slave, screenshot of timers running at same time during a race on master and the config file for master

Thanks!!

[SplitTimeIssue.zip](https://github.com/RotorHazard/RotorHazard/files/4966226/SplitTimeIssue.zip)

**Comment by rodcar125** [comment]
Just noticed I forgot to add the port number on this reported case but i have added it now and still same behaviour is seen. Also i have installed on both systems requests package with `pip install requests` and `pip install --upgrade requests`. after install and reboot same log entry "requests package is not installed" is shown

**Comment by rodcar125** [comment]
I have now installed `sudo apt-get install python-requests` and communication is established although with errors and the log file is growing really quick (please have a look at logfile attached: rh_20200723_120951.log), still no knowledge from slave that race has begun.

then i saw on log file about a warning of websocket not installed and went ahead and installed `sudo apt-get install python-websocket`. Seems like communication is now well established (please have a look at logfile attached: rh_20200723_122207.log), although still, no knowledge from slave that race has begun. or at least i think that since i cannot simulate a pass on the slave one. (image attached: Capture.JPG)


[rh_20200723_122207.log](https://github.com/RotorHazard/RotorHazard/files/4967810/rh_20200723_122207.log)
![Capture](https://user-images.githubusercontent.com/11842419/88319155-64425c80-cce1-11ea-80c5-149f8471715f.JPG)
[rh_20200723_120951.log](https://github.com/RotorHazard/RotorHazard/files/4967811/rh_20200723_120951.log)

**Comment by HazardCreative** [comment]
Thanks for the detailed work here. I think at minimum the log level needs changed to debug. Assigning MH to address these.
