### ISSUE TITLE
VRX Control - Add ability to change camera type and OSD position of a receiver

### ISSUE THREAD

**Issue by ryaniftron** [RotorHazard/RotorHazard#376]
As a race organizer, I want to be able to change the camera type and OSD position of a video receiver receiver. Pilots want the OSD in different locations and faster lock times. 

While it would be fine for this to be controllable manually, it would be great if this data is linked to the pilot so a pilot can set their preference before a race and it loads automatically each heat

**Comment by ryaniftron** [comment]
@HazardCreative VRx code is ready to go for you to implement the UI and plumbing to VRxC. I don't have a way to test till that's done, so let's be sure to test all 8 getters and setters before closing.

**Comment by HazardCreative** [comment]
RH isn't really ready for pilot-level control yet. Are seat-level settings even appropriate here? Or would this be a unit-level setting?

**Comment by HazardCreative** [comment]
Feature is no longer in core.
