### ISSUE TITLE
Most Laps - Win awarded to fastest pilot to break the tie.

### ISSUE THREAD

**Issue by CerberusVelvet** [RotorHazard/RotorHazard#379]
Would it be possible to have an additional race type added. Which uses the 'most laps' format but does not allow a tied race. By allocating the race win to the pilot who competed the laps in the fastest time (as in livetime).

Would it also be possible to add a post race 'grace' timer. Duration to be set by user. When the race timer has elapsed the pilots then have <x> number of seconds to complete the lap that they are on and it be counted. With the race auto moving to the 'stop' stage after the grace period. Any laps completed after the grace period are not counted.

**Comment by HazardCreative** [comment]
I've actually been working on this in #339.

The 'grace time' sounds like a feature to be wrapped into an event scheduler?

**Comment by CerberusVelvet** [comment]
My bad! Didn't find #339 

Not sure if the grace time belongs in the scheduler or not. I think I will say not. Because if you are as a race director not using the scheduling (for some reason). Then the race would still need that grace period set up to try to complete the lap.

The grace will vary by track setup. I think it would be better as part of the race format settings. You would be setting the race duration time there. Making that decision on duration, considering your track for the day and how many laps the lipos will last. So it would make sense to me to have the grace period set alongside race duration as part of that setup decision.
