### ISSUE TITLE
Win Condition: Chase the Ace

### ISSUE THREAD

**Issue by rodcar125** [RotorHazard/RotorHazard#382]
Here in Mexico (and I believe last multiGP championship) its becoming more and more popular to have the qualifier rounds then the double bracket elimination and the winner round to be Chase the Ace, That in which the last x number of pilots (mainly 4 or 5), race against each other and the first to win two 1st places becomes the champion. 

I know i can set it up right now as first to complete X laps, which in my case is 3 but for chase the ace I need to keep track of who won which race. It would be awesome if there would be a checkbox that would enable chase the ace tracking mode for lets say first to complete X laps or most laps in X time (multiGP format, or whatever)

Could this be taken as a feature request maybe?
All the best RH team!

**Comment by HazardCreative** [comment]
We don't have class ranking conditions yet. I'd like to see class ranking that allows the leaderboard to adjust for things like 'rank best X rounds' (closely analogous to 'drop worst X rounds'). "Chase the Ace" is really the same thing as a class condition of "first to 2 wins" (sometimes run with the special "ironman" exception of top qualifier getting a 1-race lead that applies only to the first race). 

When that gets written, this should be part of it.

**Comment by HazardCreative** [comment]
The plugin system now supports custom class ranking systems.

It's possible that I may develop this myself, but it would be made available somewhere outside the RH core.
