### ISSUE TITLE
Start Line Camera

### ISSUE THREAD

**Issue by martinglass** [RotorHazard/RotorHazard#383]
I don't know if anyone has suggested it before, but it'd be really neat to have a Camera at the Start Line that could take photo snapshots or live stream video of the quads flying past.
I can think of several uses, especially for System Testers and for Marshallers, as well as the pilots themselves. I'm sure others will have more. Imagine being able to view an action replay of a neck-to-neck finish :)
The easiest way is to use a Pi camera. Anyone with Octoprint will know how useful the OctoPi camera is on a 3D printer, so what about a Pi Camera (or other) on the RotorHazard timer?  But there are plenty of alternatives too.
The main problem for coding would be synchronising the camera shots (and videos) with the RotorHazard timer.

**Comment by JannikFK** [comment]
I agree! Simply a way for the timer to tell OBS a quad is passing would be cool, and you could switch scenes to a goal cam on the fly. 

For what it's worth - If you use a DVR when streaming you already have sort of a solution for this, just connect a seperate camera to an available input. The DVR handles the recording part when it detects movement, just as it does for all the other feeds, and lets you see all the feeds from whatever time period for when you need to deal with situations that calls for it. In OBS just make a scene called "VAR" or "Review" and put that feed in there.

**Comment by Aaronsss** [comment]
A few thoughts on this:
1. You can use any USB webcam with a pi and the right software, so doesnt have to be a pi camera. I have set up a timer to stream video from the pi to OBS in the past and it worked pretty well but bandwidth can be an issue if you want a high resolution image.
2. When racing you have usually hit the next gate before your time gets called out I suspect it would be almost impossible to trigger the camera as you are approching the gate

One alternative I like the option of is switching to the start camera during staging and keeping it on for the first 10 seconds of a race before switching to the onboard camera view. Then people on the live stream get a good view of the carnage through the start gate :)

**Comment by HazardCreative** [comment]
This is a good candidate for a plugin instead of building into the RH core. Signaling to other hardware during any standard timer event is now possible.
