### ISSUE TITLE
Callouts are playing only on the device they was triggered

### ISSUE THREAD

**Issue by kestux75** [RotorHazard/RotorHazard#385]
If you have multiple devices connected to RotorHazard server, callouts are playing only on the device they was triggered. It would be nice if they would be announced on all connected devices, as it is with race announcements.

**Comment by HazardCreative** [comment]
Callouts are announced on all devices. However, the device (browser) decides whether to play them. Browsers have restrictions on when sound is allowed to play, which usually requires recent user interaction.

You can contact the browser manufacturers and ask for a method to loosen these restrictions, but there's very little RH can do as long as the web browser is the interface.
