### ISSUE TITLE
Link RF Profiles to Heats

### ISSUE THREAD

**Issue by kwboost** [RotorHazard/RotorHazard#391]
Would it be possible to link frequency profiles to heats? I've been trying to figure a way to hold analog and hd races together.....while limiting the chance of hd to analog interference. . My answer has been running seperate hd and analog heats. Format...Most laps/lowest time, combined over (x) rounds. Dji times seem easier to calibrate at 200mw.....but we run analog at 25mw also the raceband and dji ch are slightly off.

**Comment by HazardCreative** [comment]
With #963, RHAPI now has enough reach for this to be built as a plugin.
