### ISSUE TITLE
Generate and run brackets

### ISSUE THREAD

**Issue by JannikFK** [RotorHazard/RotorHazard#393]
I might have missed something as we've only ran RH in a real race scenario once. It would be great if RH could generate the finals/mains heats after running qualification rounds. Coming from LiveTime we usually run either double elimination finals or letter finals. To do that currently in RH we need to involve spreadsheets (as far as I could see). It would also be nice to be able to view the brackets for the pilots as they progress through it.

Added bad picture of a double elimination bracket for reference.
![IMG_20200814_005441](https://user-images.githubusercontent.com/18471533/90195036-d7169300-ddc8-11ea-8b46-5c700310e069.jpg)

**Comment by HazardCreative** [comment]
On the Settings page is a heat generator. This will take an input class and fill out a set of output heats based on their ranking within that class according to the selected win condition, or you can select no input class to assign pilots randomly. To set up letter (ladder) mains, add a qualifier class and run it. Add your mains class. Choose your qualifier class as the input for the generator. If you allow one pilot to advance each ladder, reduce the number of pilots in each heat by one. This will attempt to preserve frequency assignments as much as possible when filling in the new heats.

RotorHazard does not currently support brackets.

**Comment by JannikFK** [comment]
Yea, I guess supporting brackets is the short version of what I was trying to say.

**Comment by lundyfpv** [comment]
I would very much appreciate the ability to run brackets natively. I would also appreciate the ability to run double, triple and greater mains. Having a race conclude on a single race is boring a lot of the time and doesn't favor pilot consistency.
