### ISSUE TITLE
Enhancement selectable audible indication for Save & discard race

### ISSUE THREAD

**Issue by BoLtWD** [RotorHazard/RotorHazard#396]
Suggested enhancement selectable audible indication for Save & discard race, for race directors.

I have found sometimes when the sun is hitting the screen of the laptop it would be nice to have some audible indication to know an action has been undertaken by the GUI. This would only need to apply for the race director as the public would not need this.
Possible indications could be a beep or selectable range of indications.

**Comment by HazardCreative** [comment]
Feature not expected to be developed in core, but now possible to build as plugin.
