### ISSUE TITLE
Split times not working: always same speed and no showing on results

### ISSUE THREAD

**Issue by rodcar125** [RotorHazard/RotorHazard#400]
Hi all!

Last race I finally set up a race with two systems for split timing. Mainly i want to calculate speed on a sprint as part of the track I flew. Gate 1 is start/finish with master timer and 20m later is gate 2 with timer 2 on a straight. Config file attached and configured with the 20m and slave ip address. Comms were up between timers as they were showing the splits on the current race. The issue is that all the split times seem to be the same with a calculated speed of 0.06 which is not correct. every round that we ran was the same. Also, although it would show the split times on the current race page, it does not save it on the results page.

Passes were always Gate 1 then gate 2 and recorded correctly on  master timer as you can see as an example on picture last2series.png with the race start time and on the log file started at the same time at 17:33:01 and 17:42:56

attached config, database, log and picture from the last run recorded with OBS.
Thanks guys!!

[SplitTimes_Issue.zip](https://github.com/RotorHazard/RotorHazard/files/5120857/SplitTimes_Issue.zip)

**Comment by ethomas997** [comment]
I've recently posted a PR (#399) that may help.  I've not done any testing with the speed feature, so if you'd like to try it out and report back, that'd be great.

**Comment by rodcar125** [comment]
this was run with 2.3.0 dev-1 but cant remember when did I do the update so i cannot tell if your PR is on the tested SW. Ill install master on both timers now and retest over the weekend and report back. Thanks for the prompt reply (:

**Comment by ethomas997** [comment]
The PR is separate from the 'master' branch, so you wouldn't have run it via the 'master' before.  However I just merged PR #399 into the 'master' branch and updated the version to "2.3.0-dev.3", so if you're running that version then you'll be running with those split-timer updates.

**Comment by rodcar125** [comment]
Ohh ok, didn’t know that hehe, still learning the github ways, it’s kind of confusing for me /:

Yesterday I upgraded both timers to 2.3.0-dev.2 and seemed to me that was already working (with simulated passes) but I’m not sure about the innards so I will update again later today and report back. Thanks so much for letting me know (: 
Best regards!

Rodrigo C

**Comment by rodcar125** [comment]
Hi!

Just installed 2.3.0-dev.3 on both timers. I always start the slave first so when the master starts and starts looking for the salaves, they are already there ready to connect.

Somethings happening on the slave side that it fails with the following error...
![2 3 0-dev 3_slaveIssue](https://user-images.githubusercontent.com/11842419/91364713-ff3cc380-e7c4-11ea-830a-b1ba0341beed.PNG)
Logs from master and slave:
[rh_20200826_174628_Master.log](https://github.com/RotorHazard/RotorHazard/files/5133055/rh_20200826_174628_Master.log)
[rh_20200826_174608_Slave.log](https://github.com/RotorHazard/RotorHazard/files/5133056/rh_20200826_174608_Slave.log)

Best regards!
RC

**Comment by ethomas997** [comment]
@rodcar125 Good catch there; thanks for testing and reporting.  I've updated the 'master' branch to have a check for that (so there should be a log.info message in that case and not an error), and the update for PR #402 is also in there.

**Comment by rodcar125** [comment]
@ethomas997 glad i can help out in some minor way (:
So, this check should also be done when trying to set up the frequency from the frequency setup tab, right? I mean, if I change the frequency of node 5-8 on master, it shouldn't send the update to the slave since it is a 4 node system, right?

**Comment by ethomas997** [comment]
@rodcar125 In that case the master will still send the frequency update to the slave, and the slave will send a message to the log file saying the node index is out of range, and do nothing else.

**Comment by rodcar125** [comment]
@ethomas997 just tested the starting thread on the updated master and I think is working all right. I might have a couple hours left today and test it out with an actual drone for speed and frequency changes and callouts. Ill let you know how it went.
here are the new logs from the starup with the updated master.

[rh_20200828_155359_master.log](https://github.com/RotorHazard/RotorHazard/files/5144191/rh_20200828_155359_master.log)
[rh_20200828_155339_slave.log](https://github.com/RotorHazard/RotorHazard/files/5144192/rh_20200828_155339_slave.log)

**Comment by HazardCreative** [comment]
Can we confirm this issue is resolved?
