### ISSUE TITLE
Support CVCM v1.21.a4

### ISSUE THREAD

**Issue by ryaniftron** [RotorHazard/RotorHazard#408]
In CVCV 1.21, there have been a few changes to the API like lock status. 
a4 version also changed from "node" to "seat", which affects the MQTT protocol topics as well as some of the JSON data. 

On top of these changes, a4 also implements a JSON API so RH would not need to install the ClearView module in order to talk to receivers, but this API is not yet linked to MQTT. Thus, it is not within the scope of this issue to utilize the json MQTT API until it is released in a5. 

- Change topic names referencing node to seat

- Change variable status to accept "seat_number" key instead of "node_number" key

**Comment by ryaniftron** [comment]
Branch for work: 
https://github.com/RotorHazard/RotorHazard/tree/dev/issue408

**Comment by ryaniftron** [comment]
Still facing a bug about the UI not reporting lock status for the receiver. Let me know if you have any clues:
![image](https://user-images.githubusercontent.com/57248914/92542436-ffe24a80-f205-11ea-9fa0-b52f29771530.png)

![image](https://user-images.githubusercontent.com/57248914/92542448-096bb280-f206-11ea-9321-69dc2af2dbb5.png)

![image](https://user-images.githubusercontent.com/57248914/92542467-12f51a80-f206-11ea-96ad-ec3687f4883f.png)

**Comment by ryaniftron** [comment]
The last commits address the bug commented about before; the PR has no known bugs that I could find and is ready for review.

**Comment by HazardCreative** [comment]
Closing as #412 merged.
