### ISSUE TITLE
VRxController: NotImplemented Error for setting frequency that isn't supported

### ISSUE THREAD

**Issue by ryaniftron** [RotorHazard/RotorHazard#413]
When you try to set to DJI channels and have a ClearView receiver hooked up, it generates an exception error. Instead of generating an error in the log, send a warning to the UI to let the user know those channels aren't possible for the video receiver.

**Comment by ryaniftron** [comment]
Looking into this, an exception is no longer created, however I don't know the method to bring a warning back to the server if the frequency change occurred from an event. Any recommendation for this, as VRxC is already handling this behind the scenes.

**Comment by HazardCreative** [comment]
I can add a 'caller' property to events that contains the socket.io session ID of the user who caused the event. This may at times be null. We may also need to expose RH's messaging function to provide the appropriate routing to that user's UI. It doesn't accept a particular socket destination right now, but it can be amended.

**Comment by HazardCreative** [comment]
Feature no longer in core.
