### ISSUE TITLE
No Speech/Callout on iOS Devices

### ISSUE THREAD

**Issue by patrick131184** [RotorHazard/RotorHazard#419]
Hi,
I have problems  with the Callouts/Speech on iOS Devices.

When i test the Callouts on My Desktop (Win 10) i can hear the sounds, but when trying the same with my iPhone or iPad the sound does not work (only beep indicators, but no speech).

Testes with Chrome/Firefox and Safari.
iOS Version 13.7.
RH 2.2.0

Anyone else had this issue before?

Any help would be appriciated

**Comment by HazardCreative** [comment]
Unfortunately, RotorHazard is following the letter of the specification but browsers place many restrictions on when they will allow a site to produce sounds. You may wish to file feedback with the browser manufacturers. Let them know you'd like to allow your browser to 'trust' a site and always play its audio, even while the display is asleep or without direct interaction.

https://support.google.com/chrome/answer/95315?co=GENIE.Platform%3DDesktop&hl=en
https://www.apple.com/feedback/safari.html
https://qsurvey.mozilla.com/s3/FirefoxInput/

Related: #371

**Comment by patrick131184** [comment]
Thank you for your feedback, but why is this demo working on my iOS devices then?

https://www.chromestatus.com/feature/5687444770914304

**Comment by HazardCreative** [comment]
A user who has access to iOS device will be looking into this further. (I have taken it as far as I can since I do not have any.)

**Comment by chibaron** [comment]
Hi,
On my IOS device, the voice test is successful.
Setting->AudioControl->VoceTest
But, 'Current' and 'Run' is no speech.

**Comment by chibaron** [comment]
Hi,
I added a voice button to layout.html and checked it out.
After pressing the voice button, the voice is activated.
It looks like it needs to be activated by the user.

layout.html

```
<script type="text/javascript" charset="utf-8">
    window.onload = function(){
    	$(document).ready(function () {
    		$('#voice_enable').click(function (event) {
                	$('<div class="speech">voice enable</div>').articulate('speak');
    			return false;
    		});
    	});
    }
</script>
<!DOCTYPE html>
<html lang="en">

<head>
.........

<body>
	<div id="banner-msg">
		<div class="message"></div>
		<button id="banner-dismiss" class="no-style">×<span class="screen-reader-text"> Close</span></button>
	</div>
	<header>
		<div id="timer-name"><img src="../static/image/RotorHazard Icon.svg"> <a href="/">{{ getOption("timerName") }}</a></div>
		<nav id="nav-main">
			<ul>
                		<button class="button" id="voice_enable">&#9658;&#65038;</button>   <-----add
				<li><a href="/event">{{ __("Event") }}</a></li>
				<li><a href="/results">{{ __("Results") }}</a></li>
				<li><a href="/current">{{ __("Current") }}</a></li>
				<li class="admin-hide"><a href="/run">{{ __("Run") }}</a></li>
				<li class="admin-hide"><a href="/marshal">{{ __("Marshal") }}</a></li>

```

**Comment by HazardCreative** [comment]
This should be set to appear only when needed.

I'm not really a fan of browser sniffing—it would be better to tie it to a feature detection of some kind. Maybe we can test if the audio context is still inactive?

**Comment by chibaron** [comment]
I can't find any other way to do it except to actually try to vocalize it.

layout.html
```
<script type="text/javascript" charset="utf-8">
    window.onload = function(){
    	$(document).ready(function () {
    		$('#voice_enable2').click(function (event) {
            	speak_check();
    			return false;
    		});
    	});
    	speak_check();
    }
	function speak_check() {
        $('<div class="speech">.</div>').articulate('speak');
        var speaking = $().articulate('isSpeaking');
        document.getElementById("voice_enable2").disabled = speaking;
	};
</script>

```
