### ISSUE TITLE
Enhancement: Starting Condition 1st Lap Counting

### ISSUE THREAD

**Issue by sl33pydog** [RotorHazard/RotorHazard#424]
People may not run races this way but is there a way to run a race where you don't fly through the timer to start the race?  We ran a race where the start platform was off on the side of the start gate.  Pilots ran through their first lap and Rotorhazard would see that as a hole shot.  This made it so that all pilots had 1 less lap then they should have.

Live time has it where you either count the 1st lap and disregard the hole shot or that it needs the first lap for hole shot to keep the laps consistent.

I understand the need for both and I understand both have consiquences.  On one side forcing pilots through the start gate needs a good line and decent pilots so they don't crash on the start gate.  The other insures pilots get on their lines faster but messes up the fastest lap since that first lap might be their slowest.  I know people will not do it this way generally but would love to have this as an option.

So I propose that there should be two start conditions:

1. Start Gate: Passing through the start gate produces a hole shot and starts the 1st lap.  This is currently the way Rotorhazard is set up.

2. Shotgun Start: As soon as the timer starts, the 1st lap has initiated and when pilots go through the track over the timer the 1st lap is counted.  Hole shot is disabled.  Pilots don't go through the start gate but on a parallel path that with the correct layout ensures even beginners a chance to get through gates or flags.  This can be viewed like a street race or nascar.

**Comment by HazardCreative** [comment]
My biggest question is: why is the current behavior an issue for you? You're still collecting that first crossing time. Since RH doesn't yet support staggered start, that time is added to the pilot's total race time. Is it just a terminology issue ('hole shot' vs 'lap 0')?

When a course is set up this way, that first lap is necessarily not the same as others. I'd argue that there's good reason it should not be considered for many of the stats like fastest lap and 3 consecutive laps.

**Comment by sl33pydog** [comment]
The current behavior isn't an issue with me.  It's with the many groups I've flown with.  Way back in the day I started with using the timing gate as the first gate to fly through but the groups noticed a trend.  With experienced pilots we saw too many mid air collisions either before or in the timing gate.  With novice pilots we saw them either take 2 minutes to figure out going through the timer or crashing into it without running into others.  When the groups started to switch to this new way where a side track paralleled the start gate we saw very few if not any mid airs from pilots unless they grouped themselves in the race and novice pilots finally got some momentum (even though they would crash later on a flag or another gate if we put them there).  So when we ran the race with fastest three consecutive laps I didn't match with live time with some of the pro pilots who would go full throttle and kill their batteries after 3 laps.  Rotorhazard only saw 2 laps.  And for our A mains for first to three laps it did the same.  Live time would tell them to land where Rotorhazard said they had 1 more lap.  A reason why I didn't use the audio from Rotorhazard.

I would agree and disagree with that.  I agree that yes the first lap isn't the same but I disagree that doesn't also happen using it in the default way.  I definitely want to test which way is more consistent.  In our race with the pro pilots they were showing a 4 second difference between that first lap and last lap but it was also showing that each lap they did got faster.  I reckon we would see similar results to the default method.

Really what happened was the system gave them a practice lap that didn't add to their lap count but added a full lap worth of time to their total time.  This would be fine for shorter tracks but we tend to make courses for novice pilots that are 3 laps long in 2 minutes and for pro guys they only go three laps just so they don't destroy the battery.

**Comment by HazardCreative** [comment]
Essentially what you're looking for is to have the system record a hole shot of 0:00 for all when a race begins. Is that correct?

Not trying to be difficult here, but every additional option adds cognitive overhead to the system and erodes how simple it is to use and manage. The race organizer's experience is more important to me than having every possible option. So for each new option I take a hard look at whether it will provide a significant benefit or if there's a better way to approach it that doesn't mess with the UI as much. It's not about how difficult it is to add the feature (which it probably wouldn't be).

With the start position just before the gate, it's true that the first lap is often slower. But I don't think anyone would argue that it should not count as a lap—the pilot has definitely completed the entire course. When the pilots do not complete the start gate, they have not run the entire course line. You're no longer comparing apples to apples. 

If the first-lap course is shorter/faster, this weights the first lap heavier than others. You'll reward a very aggressive start, and probably cause more crashes and collisions. I'm not sure all race directors would recognize this? The pilot's experience might weigh in this as well.

If you look at the MultiGP global qualifier course, particularly 2019, you'll see a good in-between way to handle this: The launch happens one or two corners before the gate, as a lead-in to the first crossing. Pilots without experience to complete a timing gate won't be solved by moving it later in the course.

**Comment by sl33pydog** [comment]
Lol you're not being difficult at all.  It's necessary to discuss things in order for the product to have it's best income whatever direction it needs to take.  I'm with you on not complicating things.  Livetime is like android you can tweak everything you want but can get overwhelmed easily in the start.  Rotorhazard is like apple, a lot of it is behind the scenes and the UI creates a straight forward experience that even beginners can pick up with out too many issues.

Essentially what I was looking for was the the system to count the first lap as a lap.  Hot shot doesn't matter here, just that the first time a pilot goes over the timer that the lap be counted as 1 completed lap.  The length of the course is the same just the start is offset to the side.  Yes it does reward more aggressive starts but it does help the novice pilots too.  Generally the tracks have flags after the start gate where we are allowing groups to generally thin out.  People go high, low, wide, or short around flags as opposed to going through a 6'x6' opening where people try to go through the center.

So I like the idea of having the start somewhere 1 to two steps back but again if it's gates we get the same issues.

I do realize the importance of the first recorded spike. I used it in the race to see if someone switched their quads so I could spot them during the race.  Usually indicated by a lower rssi.

This change really benefits large tracks.  Compact tracks don't have the benefit of a runway or offset track.

Also to your point about spectator involvement wouldn't a more aggressive start turn more heads 😉.
