### ISSUE TITLE
I2C related error on Bananapi - solved

### ISSUE THREAD

**Issue by szafranski** [RotorHazard/RotorHazard#429]
![120550634_10214025510991079_1325264596159518074_o](https://user-images.githubusercontent.com/23621888/94742347-d6848c80-0375-11eb-9a29-1432647e3560.jpg)

That error maybe caused by wrong I2C bus number in "i2c_helper.py" file.

**Comment by szafranski** [comment]
Way to check "sudo i2cdetect -y 1" and "sudo i2cdetect -y 0" - nodes should be found using one of those.

**Comment by szafranski** [comment]
That "bus number" is used in:
~/RotorHazard/src/interface/i2c_helper.py file, here:

class I2CBus(object):
    def __init__(self):
        self.i2c = smbus.SMBus(1) # Start i2c bus

numer in a (X)

for sure. 
Idk if anywhere else too in RotorHazard repo. 

Changing it to 0 for example make RH work on Bananapi etc. 

Happy to help if needed.

**Comment by HazardCreative** [comment]
I think this should be easy to add a config option for and we should get it into the next release.

**Comment by szafranski** [comment]
Awesome
