### ISSUE TITLE
Stream Displays - Current Class

### ISSUE THREAD

**Issue by CerberusVelvet** [RotorHazard/RotorHazard#441]
Using 2.3 Beta 1

Stream Displays - Current class. Page doesn't show race data. Gives message "There is no saved race data available to view."

![Screenshot 2020-10-11 155411](https://user-images.githubusercontent.com/29674976/95681936-747c2080-0bda-11eb-955e-bd768f6fac72.png)

**Comment by HazardCreative** [comment]
Working for me. Do you have a heat selected that has saved race data? This display follows the currently selected heat.

**Comment by HazardCreative** [comment]
Closing with no recent updates. Please let us know if more information becomes available.
