### ISSUE TITLE
VRxController: Switch to JSON OSD

### ISSUE THREAD

**Issue by ryaniftron** [RotorHazard/RotorHazard#444]
Right now, RH formats the entire OSD messages are [formatted in RH](https://github.com/RotorHazard/RotorHazard/blob/f24f680776ae918858cbafb8d45e3ccb945bf40b/src/server/VRxController.py#L326-L380). 

Now, we want the devices to format their own messages. 

- Send the win condition

- Send all the osd keys

- Send all the osd_next_split and osd_next_rank and osd_first_split

Check the payload size isn't larger than max MQTT payload

If the payload needs to be split, you'll need to handle waiting the data to arrive

Add in Wiki for the race keys and associated documentation

**Comment by HazardCreative** [comment]
Feature no longer in core. (Also, has been implemented)
