### ISSUE TITLE
VRxController: Implement turn_off_osd

### ISSUE THREAD

**Issue by ryaniftron** [RotorHazard/RotorHazard#453]
The CVCM will support turning off all osd elements except the user message. Re-implement this in VRxController so when a receiver is connected, all the osd elements get turned on

**Comment by HazardCreative** [comment]
Is there a corresponding osd_restore? Is there even an appropriate time to trigger it if there is? Might need to be handled by the CVCM.

**Comment by ryaniftron** [comment]
I will add it.

I don't believe there is a time to trigger because people unplug their ClearView's at any and all times. There will be UI in the CVCM to change it back after a race. Is there some method in the race to shut down and tell external devices to go back to their non-race settings?

**Comment by HazardCreative** [comment]
The SHUTDOWN event seems appropriate.

**Comment by ryaniftron** [comment]
Ok - I added the capabilities for show/hide and added a PR. Added an issue to support SHUTDOWN event
