### ISSUE TITLE
Issue with transitioning from a disabled node

### ISSUE THREAD

**Issue by frizzle101101** [RotorHazard/RotorHazard#459]
if you have a node disabled then change the channel on that node, the rx5808 module will not be tuned into the right channel(dont know where it is actully tuned) but there will be an rssi reported on that node which is not actually representing the right channel. To work around change to another channel or back and the node will work fine.

**Comment by HazardCreative** [comment]
Thanks for the report.

This is interesting because the process for disabling the node is setting its frequency to a special value (1111). So it sounds like a hardware issue. Is it worth writing a workaround to set it twice? @ethomas997

**Comment by ethomas997** [comment]
@frizzle101101 I ran some tests and I was not able to reproduce your issue.  We were also not able to reproduce your other issue about switching nodes -- I think you may have hardware issues that are specific to your setup.  I'd recommend doing some debugging by verifying the operation of each node with a VTX source, etc.

**Comment by frizzle101101** [comment]
im using the 20120322 modules, they all perform this way, if u attach an antenna it is much more prevalent

**Comment by frizzle101101** [comment]
though this just seems to happen in operation aswell without coming from disabled so i dont think its an issue unless u start in the gate

**Comment by HazardCreative** [comment]
Closing old issue; use workaround provided in #460. Reopen if new information/reproducible case is available.
