### ISSUE TITLE
Add a scheduling mechanism to start a race in X seconds

### ISSUE THREAD

**Issue by Klaus-Michael** [RotorHazard/RotorHazard#46]
add some kind of a scheduling mechanism to schedule a race to start in X seconds.
Play announcements that announce that the race will start in Y Seconds
For example:
"race will start in 1 minute"
"race will start in 30 seconds"
"race will start in 10 seconds"
"get ready" 
"beep" 
"beep" 
"beep"
"beeeeeeeep"
start the beeper countdown after the scheduling timer reached 0

A similar functionality is possible by setting the min and max delay to a high value but its hard to anticipate how much time already passed and the continuous beeping is a bit annoying.

**Comment by HazardCreative** [comment]
A rewrite is needed for the front-end timer. It currently relies heavily on setInterval, which is a really inaccurate method. I'd like to do this (or at least provision for it) when that rewrite is tackled.

**Comment by Klaus-Michael** [comment]
Ok sounds like a more complicated tasks that might take some time.
For the time being I added the functionality to the current System to have a quick solution that can be used till you got the front-end timer rewritten.

**Comment by HazardCreative** [comment]
Added with merge of experimental branch @ 220bf6f.
