### ISSUE TITLE
opinions about an android app

### ISSUE THREAD

**Issue by frizzle101101** [RotorHazard/RotorHazard#461]
i was wondering if anyone would be interested in an android app for this, culd be simple because of the web interface, idea is a way to run races with **audio, or bluetooth audio, and all without having to keep a browser open on your phone** and thus your phone s screen doesn't always need to be on, with this run as an app no more need for a laptop, then when you get home upload results to multi gp ":) this is the dream and if i can help with it that would be cool too. (its like when u wanna listen to a youtube mix but have to keep your phone on to listen for longe periods of time, how annoying lol)

**Comment by HazardCreative** [comment]
I'm not personally interested in maintaining several separate native apps. If others would like to develop this they are welcome to do so.

**Comment by frizzle101101** [comment]
so ive been looking at this and my best idea was to use webview in an application to make it so no recoding of the ui is needed, but im running into issues with the javascript not working in webview

**Comment by frizzle101101** [comment]
it seems as right now the webview does not support the web speech api, https://bugs.chromium.org/p/chromium/issues/detail?id=487255 
-currently this approach is being blocked by the webview devlopment to include the web speach api
-there may also be issues with jquery and the socket io js, as the function socket.emit is not being recognized in the webview application, it seems webview also does not support websockets, so the following guide can be used to add that support, https://www.programmersought.com/article/24751810995/

**Comment by HazardCreative** [comment]
Closing as this is a discussion solicitation and not a specific issue.
