### ISSUE TITLE
Add "back" button in a "server log" page.

### ISSUE THREAD

**Issue by szafranski** [RotorHazard/RotorHazard#462]
As stated in a title :) No a big issue - but could be handy.

**Comment by HazardCreative** [comment]
Doesn't this just duplicate the browser's built-in functionality?

**Comment by szafranski** [comment]
In a way - yes, it does. But if we consider this as a "GUI" and not as a "web page" it makes sense - imo :)

**Comment by HazardCreative** [comment]
But it's a UI within a web page, so the browser's functionality will be available. I don't think there's a good case for expanding the UI here.
