### ISSUE TITLE
Userdatabase, Teams, etc.

### ISSUE THREAD

**Issue by husky-koglhof** [RotorHazard/RotorHazard#463]
Current i'm playing around with some new features.

Our Teammembers wanna have a self register portal, so they can drive any time on our RC track.

I've locally implemented 'flask-security' for user management.
![image](https://user-images.githubusercontent.com/4559313/99278218-0f49c980-282f-11eb-9e9f-d2c910c63797.png)
If starting from a new browser window, it's possible to login / signup to rotorhazard:
![image](https://user-images.githubusercontent.com/4559313/99278317-2e485b80-282f-11eb-99f0-38d2b796913b.png)
After signup, users must be confirmed from an administrator:
![image](https://user-images.githubusercontent.com/4559313/99278596-897a4e00-282f-11eb-8530-a399bc75492d.png)
![image](https://user-images.githubusercontent.com/4559313/99279141-2dfc9000-2830-11eb-8041-d422c46cde8c.png)

At these moment, team "Guest" is locked, so every new user will become it as the default team
![image](https://user-images.githubusercontent.com/4559313/99279475-8fbcfa00-2830-11eb-9009-fbe41a36569f.png)

![image](https://user-images.githubusercontent.com/4559313/99279617-b3804000-2830-11eb-915c-ce5354a1fc1a.png)

What are the next steps?
.) Testing and updating "self register"
![image](https://user-images.githubusercontent.com/4559313/99279715-d6aaef80-2830-11eb-8a29-79377cc53b00.png)
.) Each User (Pilot) will see only it's own heats
.) Create a possible user/role/permission set, current i've only guest, user, pilot, admin
.) Create a workflow, so new user are quick confirmed from an existing admistrator
.) Upload a useful branch on my fork, so each user can test it

**Comment by HazardCreative** [comment]
Looks like you're doing great work! Let's please combine this discussion with #264.
