### ISSUE TITLE
Cluster data messing up UI

### ISSUE THREAD

**Issue by rodcar125** [RotorHazard/RotorHazard#465]
Hi guys!

I've been testing the cluster with 2.3.0-beta.2 and the info displayed does not play nice with the UI.
Could it be done that maybe its displayed different or with a horizontal scroll bar? specially annoying on my smartphone since you can move around to the top right the grey area.

Please see below pictures,
Thanks and best regards from Mexico!!
Rodrigo

![IMG-3152](https://user-images.githubusercontent.com/11842419/100386077-08b71100-2fea-11eb-8cbb-44748e0fccbb.PNG)
![IMG-3153](https://user-images.githubusercontent.com/11842419/100386083-09e83e00-2fea-11eb-80dc-421a55863db2.PNG)

**Comment by HazardCreative** [comment]
Data tables are notoriously bad for responsive layouts. Is there are reason the data needs to be tabled for direct comparisons? Can this be grouped boxes like what's used for VRx Control?
