### ISSUE TITLE
Stream node text doesnt clear when node is empty in next heat

### ISSUE THREAD

**Issue by Aaronsss** [RotorHazard/RotorHazard#466]
If you have multiple heats, one with more pilots in it than the other. The node stream text (pilot name) remains populated when changing from the larger heat to the smaller one on the nodes that are not in use in the smaller heat.

This makes it look like someone is flying when in reality its just stale text from the previous heat

**Comment by HazardCreative** [comment]
Confirming as reproducible. Thanks for the clear report.
