### ISSUE TITLE
Java reported to not being found (and IMD table not working) despite java presence

### ISSUE THREAD

**Issue by szafranski** [RotorHazard/RotorHazard#475]
Tested on:
Ubuntu (WSL) - on PC
server opened with "python3"

Java is installed, yet not recognized by the server.

![image](https://user-images.githubusercontent.com/23621888/103487663-54d64c00-4e07-11eb-97fe-eb29d1f5cedf.png)

**Comment by ethomas997** [comment]
If you enter 'java' in terminal window, does it find the program (and respond with a "Usage..." message)?  If not then you need to configure your system so that java is on the command 'PATH'.

**Comment by szafranski** [comment]
But I was testing it in WSL, not in native cmd.

W dniu niedz., 3.01.2021 o 22:26 E Thomas <notifications@github.com>
napisał(a):

**Comment by szafranski** [comment]
Nevertheless - it shows that "Usage" output.

![image](https://user-images.githubusercontent.com/23621888/103489559-b1d8fe80-4e15-11eb-88c4-d16002be076b.png)

**Comment by ethomas997** [comment]
How are you running the RotorHazard server?  (In that same type of terminal window, or something else?)

The RH server performs a system call using the 'java' keyword, which is similar to running it in a terminal window.

**Comment by szafranski** [comment]
Exact same way I use

W dniu niedz., 3.01.2021 o 22:58 E Thomas <notifications@github.com>
napisał(a):

**Comment by ethomas997** [comment]
Have you tried installing Java via the WSL terminal window?  With a command like:  sudo apt-get install openjdk-11-jdk

Pretty much any version of Java should work OK.

**Comment by szafranski** [comment]
Yes. I tried headless and "normal" java. I also found that line in server.py and I am experimenting with it. 

No idea why that issue occurs:
![image](https://user-images.githubusercontent.com/23621888/103490731-18fab100-4e1e-11eb-8fa6-abd99fa46fa6.png)

**Comment by szafranski** [comment]
I think I found something. I made some simple test script:
![image](https://user-images.githubusercontent.com/23621888/103490944-b4405600-4e1f-11eb-8c49-183c49360ea3.png)

And the output is:
![image](https://user-images.githubusercontent.com/23621888/103490950-c4f0cc00-4e1f-11eb-8ebb-4f953e002274.png)

Looks like this java_ver variable is bytes type not string - that's why U cannot perform split so the try is not working 
so expect is being performed. At least that's my undersanding.

**Comment by szafranski** [comment]
![image](https://user-images.githubusercontent.com/23621888/103491015-42b4d780-4e20-11eb-8751-8e12a26d73cb.png)
gives:
![image](https://user-images.githubusercontent.com/23621888/103491025-5102f380-4e20-11eb-8b47-07353998cfa7.png)

**Comment by phobos-** [comment]
Looks like it needs proper decoding, this works for me:
`>>> ver = subprocess.check_output(['java -version'], stderr=subprocess.STDOUT, shell=True)
>>> ver.decode('UTF-8').split('\n')[0].strip()
'openjdk version "11.0.7" 2020-04-14'
>>>`

**Comment by szafranski** [comment]
I tried this as well as str(var) etc - that way it gives no java-related info at all during server boot (and IMDTabler is not working still).

![image](https://user-images.githubusercontent.com/23621888/103566445-5153cb00-4ec2-11eb-9d16-05e17126726b.png)

![image](https://user-images.githubusercontent.com/23621888/103566465-587ad900-4ec2-11eb-86a9-9dbd27aae9e7.png)

**Comment by ethomas997** [comment]
Looks like the issue is that the Java detect is failing with Python 3.8+.  I'll post a fix.  Thanks for finding and reporting this.

**Comment by szafranski** [comment]
Cool. Awesome it was some generał issue, not an edge case.

W dniu czw., 7.01.2021 o 09:13 E Thomas <notifications@github.com>
napisał(a):

**Comment by szafranski** [comment]
Happy to report is now works (with newest dev release) on python 3.8.5 on WSL and on python 3.7.3 on Raspbian - Banana Pi. Good job.

![image](https://user-images.githubusercontent.com/23621888/104525636-d0eb4380-5600-11eb-94b5-adfe663d471a.png)
