### ISSUE TITLE
Java installation command - change proposition

### ISSUE THREAD

**Issue by szafranski** [RotorHazard/RotorHazard#481]
Can it be changed to:
`sudo apt install default-jdk-headless`
instead of:
`sudo apt-get install openjdk-8-jdk`
so it would be the newest version all the time?

Seems to work just fine with e.g. java 11

**Comment by szafranski** [comment]
Andd btw. "headless" version is much smaller so I sugget it.

**Comment by ethomas997** [comment]
Good idea; thanks.
