### ISSUE TITLE
Secondary time sync issues

### ISSUE THREAD

**Issue by HazardCreative** [RotorHazard/RotorHazard#490]
The secondary race clock is not in sync with the primary, even when running on the same local machine.

```
Secondary 1 clock synchronized OK with primary, timeDiff=0ms
Race started at 34812.181000000004 (1611393672673)
```

```
Race started at 34810.196 (1611393670678)
```

**Comment by ethomas997** [comment]
If I remember correctly, the timestamps sent from the split timer are absolute-time 'epoch' values, so they will be unaffected by the race-start time.

**Comment by HazardCreative** [comment]
Would this be an issue for LED controllers? (I had this set as a split instead of a mirror, not sure if the behavior changes)

**Comment by ethomas997** [comment]
When I've run mirror timers they seemed to operate fine in terms of responsiveness.
