### ISSUE TITLE
Update installation notes to update and run with python3

### ISSUE THREAD

**Issue by Aaronsss** [RotorHazard/RotorHazard#496]
Given that python 3 is now supported it would make sense to have people upgrade and run using python3 and pip3 on the update notes and Software Setup.md

**Comment by HazardCreative** [comment]
Py 2 is still supported in 2.3, but this is a good suggestion for going forward.

**Comment by ethomas997** [comment]
The other approach would be to have instructions for reconfiguring the Pi to use Python 3 by default -- make it the version of Python that is run via the 'python' and 'pip' commands (are there other Python commands to worry about?).

**Comment by ethomas997** [comment]
The Software Setup now includes instructions for making Python 3 the default, so closing this issue.
