### ISSUE TITLE
Auto-stop race after grace period

### ISSUE THREAD

**Issue by HazardCreative** [RotorHazard/RotorHazard#500]
Provide a method to automatically trigger the 'stop race' function after a user-defined period of time has elapsed.

One component of #428

**Comment by Aaronsss** [comment]
Would it be possible to finish a race similar to livetime? 

So after the race timer elapses you have 30 seconds to finish your current lap and then it ends the race?

**Comment by HazardCreative** [comment]
This is one part of it. #502 is also necessary as #500 alone will not prevent pilots from counting multiple laps during the grace period.
