### ISSUE TITLE
Disable node does not work

### ISSUE THREAD

**Issue by Aaronsss** [RotorHazard/RotorHazard#507]
I am uncertain if this is stm32 related or if it's just an issue with the 3.0.0 Dev 2 branch

In the set frequency menu the disable option does not appear to disable nodes. Current draw remains the same and when refreshing the page the setting goes back to the previous frequency setting instead of disabled.

**Comment by HazardCreative** [comment]
Confirmed. 3.0 issue. Will get a fix in.
