### ISSUE TITLE
Sensor tab on run page buggy

### ISSUE THREAD

**Issue by Aaronsss** [RotorHazard/RotorHazard#508]
I have the INA219 installed and am running 3.0.0 dev 2

When loading the run page you have to open one of the other tabs before the sensor tab will open. Once you have opened another tab it works normally.

This happened to in both Chrome on Android and Firefox on desktop

**Comment by ethomas997** [comment]
By "sensor tab" do you mean the 'Status' section that opens up when you click on the blue bar?

Is there any issue viewing the 'Status' on the 'Settings' page?

Are there any error messages in the Server Log?  (Providing the '.zip' file created via the 'Download Logs' button is often helpful.)

**Comment by Aaronsss** [comment]
Yes sorry I mean status section when you click the bar (mines purple :) )

The settings page seems to work properly. There is no messages given out in the terminal when the problem occurs.

To get the problem:
Click Run on the menu bar at the top
Click status section - observe that it doesnt open
Open one of the other sections and click status a couple more times (I guess to close and open it) for it to appear

The problem is seen using firefox 85.0.2 (64-bit)

**Comment by ethomas997** [comment]
Should be fixed now; thanks for reporting it.
