### ISSUE TITLE
Warn for python2 and recommend python3

### ISSUE THREAD

**Issue by ryaniftron** [RotorHazard/RotorHazard#511]
Python2 is now deprecated, so RotorHazard should at least warn users that it is recommended to upgrade to python3.

**Comment by ethomas997** [comment]
I plan on updating the setup docs to include a procedure for making Python 3 the default on the Pi.

**Comment by ethomas997** [comment]
The Software Setup now includes instructions for making Python 3 the default, so closing this issue.
