### ISSUE TITLE
Run page callouts broken

### ISSUE THREAD

**Issue by Aaronsss** [RotorHazard/RotorHazard#512]
%PILOTS% & %FREQS% no longer work on 3.0.0 dev 2

When I initially started using 3.0.0 they worked but the %FREQS% would say object object instead of the frequency.

I updated a few days ago to fix the node disable bug and now %PILOTS% & %FREQS% seem to be ignored completly

%HEAT% does still work though.

There are no errors in the log file

**Comment by HazardCreative** [comment]
Thanks for the report. Yes, it is broken, but this section is potentially getting an overhaul soon in pursuit of #501.
