### ISSUE TITLE
The Voice : Fred is same as Samantha

### ISSUE THREAD

**Issue by martinglass** [RotorHazard/RotorHazard#524]
Not sure whether this is just specific to v3.0.0-beta.1, or how the browser/os affects it all.
It seems that the Voice collections are changing name - on some browsers/os's the voice names are people's names, but in other browsers/os's the voice names are by country/region.
Anyway, on one system under test, using the people's names the Voice "Fred" sounds the same as the Voice "Samantha".

**Comment by HazardCreative** [comment]
Voice selections are provided by the browser, based on voices installed to your operating system.

Was it different before? Did something change?
