### ISSUE TITLE
default Live time integration  

### ISSUE THREAD

**Issue by coreyman2000** [RotorHazard/RotorHazard#526]
The default settings on RH Heats are blank on the heats tab and out of the box to get RH triggering inside live times is to insure pilots are in the heats otherwise live time doesn't trigger. See screenshot. 

If you can set the default so that the heats are populated  then out of the box RH and livetime will be working. 

![157371602_10159020918701838_180912468860107683_o](https://user-images.githubusercontent.com/21960367/110248303-507cfb00-7f3e-11eb-9390-aad41273fe71.jpg)
![158375385_10159020917756838_4818571026287579196_o](https://user-images.githubusercontent.com/21960367/110248305-5246be80-7f3e-11eb-8b3d-b02816c52829.jpg)

**Comment by HazardCreative** [comment]
The internal LiveTime mode should bypass all pilot checks instead of requiring pilots be assigned.

**Comment by coreyman2000** [comment]
It doesn't , you need to setup that setting as mentioned about, from default builds

**Comment by HazardCreative** [comment]
Hopefully 028a8a8 resolves this, but testing is still necessary.

**Comment by HazardCreative** [comment]
Closing old issue that was possibly resolved anyway, but for sure is no longer relevant since Delta5 emulation is gone and a new connector should be built for LT when they are ready.
