### ISSUE TITLE
Rotorhazard locked up, stopped updating laps, sending voice prompts, and required restart (Too many files open message)

### ISSUE THREAD

**Issue by RogerBFPV** [RotorHazard/RotorHazard#527]
After 5 hours of racing, stopping, starting new heats, when an interesting symptom occurred:
During a race, new laps stopped being updated at the browser.. 

Looking at the browser, we could see the RSSI graphs for a pilot rise and fall, but the lap would not show up and there was no voice prompt..

When the race was over, (it was a heads up race first to 3 laps), I pressed stop race, and save laps..  But the save laps never returned..

I tried refreshing the browser, but that didn't do much, (It would go back to the 'save laps' button, but pressing it would not. So I was unable to progress to the next race..

I then went into settings, and attempted to 'reboot' the pi, but the reboot did not occur..(The browser indicated it was rebooting, but  when connecting again, the system was in the same state)..

I then went and unplugged/replugged the power to the pi..   

AMAZING enough, the laps for that race were indeed saved!!! so that was good news.. and the rest of the day ran without issue.

The there are 'ERROR' s in the log around the time of the failure..(unable to open database file) So I'll attach that log. Around timestamp of 05:50:11. and Too many open files at 05:50:29... .

[rh_20210305_233320.log](https://github.com/RotorHazard/RotorHazard/files/6098828/rh_20210305_233320.log)

**Comment by RogerBFPV** [comment]
This was version 2.3.0:
021-03-05 23:33:20.844: __main__ [INFO] Release: 2.3.0 / Server API: 29 / Latest Node API: 25
2021-03-05 23:33:20.844: RHUtils [INFO] Host machine: Raspberry Pi 3 Model B Rev 1.2
2021-03-05 23:33:20.845: RHUtils [INFO] Host OS: Linux 4.19.66-v7+

**Comment by HazardCreative** [comment]
Thanks for the report. We will definitely be looking into this and see what we can uncover. Are we able to get the database file as well?

**Comment by RogerBFPV** [comment]
[database.db.zip](https://github.com/RotorHazard/RotorHazard/files/6111228/database.db.zip)
database file.

**Comment by HazardCreative** [comment]
Confirming there is an issue here, which appears to be inherited all the way back from Delta5. Thanks for providing logs and database. Restarting RH will clear out the buildup of unused file handlers so as a temporary workaround you could look for a place to break and restart every couple hours of racing. We are working to resolve it.

Technical: File handlers are created when the database is called. When this happens via a submodule callback to main (during processing of a lap record) the file handler is not closed.
