### ISSUE TITLE
Settings > Database. Choose an exporter. CSV (friendly) don't work

### ISSUE THREAD

**Issue by starz91** [RotorHazard/RotorHazard#529]
[rh_logs_20210313_200145.zip](https://github.com/RotorHazard/RotorHazard/files/6135457/rh_logs_20210313_200145.zip)

**Comment by HazardCreative** [comment]
From your log, you're using Python 2. That's no longer officially supported and is the most likely source of this issue. It's a unicode error and unicode string handling differs a lot between Python 2 and 3.

Upgrade Python and report back if you still have this issue. See https://github.com/RotorHazard/RotorHazard/blob/main/doc/Software%20Setup.md#5-install-python

**Comment by starz91** [comment]
thank you
