### ISSUE TITLE
Server won't boot with SQLAlchemy >= 1.4

### ISSUE THREAD

**Issue by szafranski** [RotorHazard/RotorHazard#535]
![image](https://user-images.githubusercontent.com/23621888/111902216-9fe22180-8a3c-11eb-9d9f-8f8df8a6c878.png)

Described on Fb group.

**Comment by szafranski** [comment]
It was especially visible when installation from scratch was performed - independent of RH version, main, stable etc. 
Probably cause it is one of the dependencies of some another flask-related package installed from requirements.

**Comment by szafranski** [comment]
Sorry for commenting on closed issue, but are you planing new stable release soon due to this issue? Like 2.3.3?
I am asking in case of new installations performed before that commit was made? Cheers

**Comment by HazardCreative** [comment]
We intend to do a 2.3.3 release very shortly.

**Comment by szafranski** [comment]
Sounds reasonable. Cool.

W dniu pon., 22.03.2021 o 19:21 Hazard Creative ***@***.***>
napisał(a):
