### ISSUE TITLE
Release name and release version mismatch 

### ISSUE THREAD

**Issue by szafranski** [RotorHazard/RotorHazard#543]
RotorHazard 2.3.3 contains this info:
![image](https://user-images.githubusercontent.com/23621888/112682243-21d4af00-8e70-11eb-9dbe-7b0c3196e678.png)

**Comment by szafranski** [comment]
Actually declared "node api level" in "commands.h" file is mismatched too I think. Sorry for bothering

**Comment by szafranski** [comment]
Actually declared "node api level" in "commands.h" file is mismatched too I think.

**Comment by HazardCreative** [comment]
Github somehow tagged the wrong branch. I think I've got it targeted properly now.

**Comment by szafranski** [comment]
Thats what I thought.
Will check soon.

Cheers


W dniu pt., 26.03.2021 o 21:41 Hazard Creative ***@***.***>
napisał(a):

**Comment by szafranski** [comment]
Looks it's all good now. :)
