### ISSUE TITLE
Export Data button doesn't work (3.0.0-beta.1)

### ISSUE THREAD

**Issue by martinglass** [RotorHazard/RotorHazard#554]
In Settings, Database - when I click "Export Data", nothing happens.

I've tried 3 different browsers (Safari, Brave and Firefox) on Mac OS-X Mojave 10.14.6
and I've tried Brave on Windows 10 Pro 20H2

**Comment by HazardCreative** [comment]
Include database and log file, please.

... > View Server Log -> "Download Logs"

**Comment by martinglass** [comment]
Problem Solved. I was still running Python 2.7 which is unsupported by RH now. I've upgraded to Python 3 and it's all working as it should.
