### ISSUE TITLE
Simplify ina219 instalation

### ISSUE THREAD

**Issue by Aaronsss** [RotorHazard/RotorHazard#555]
The ina219 installation described on the software setup page can be simplified by using:

sudo pip3 install pi-ina219

Alternatively it could be added to the python requirements file so it installs by default

**Comment by ethomas997** [comment]
@Aaronsss Yes, I think both 'pi-ina219' and 'RPi.bme280' can both go into 'requirements.txt' (both libraries are quite small).  Thanks.
