### ISSUE TITLE
Run the service as pi

### ISSUE THREAD

**Issue by Aaronsss** [RotorHazard/RotorHazard#556]
Having been playing about with a pi I think the software setup page should define the serivce as per the below so it runs as pi and not root

[Unit]
Description=RotorHazard Server
After=multi-user.target

[Service]
User=pi
WorkingDirectory=/home/pi/RotorHazard/src/server
ExecStart=/usr/bin/python server.py

[Install]
WantedBy=multi-user.target

**Comment by HazardCreative** [comment]
With older Pi OS (Stretch) root was required to make GPIO access work for LED support. I think that's changed so we should consider this.

**Comment by ethomas997** [comment]
@Aaronsss Good call; thanks.
