### ISSUE TITLE
cluster.md issues

### ISSUE THREAD

**Issue by Aaronsss** [RotorHazard/RotorHazard#561]
'On the primary, edit /etc/npd.conf and add lines similar to:'
and
'On the secondaries, edit /etc/npd.conf and add lines similar to:'
should point to ntp.conf? npd.conf doesnt exsist

'sudo ​/etc/init.d/ntp restart'
returns:
'sudo: ​/etc/init.d/ntp: command not found'

trying to run the above on a raspberry pi 3B+

**Comment by ethomas997** [comment]
What do you get if you run this?:
```
sudo service ntp restart
```

**Comment by Aaronsss** [comment]
I get no output but that command does restart the service

**Comment by ethomas997** [comment]
Thanks
