### ISSUE TITLE
[proposed label: Enhancement] Personalised Option for Voice Callouts

### ISSUE THREAD

**Issue by martinglass** [RotorHazard/RotorHazard#563]
The idea is that an individual pilot using their personal Smartphone could choose an option to select audio callouts just for their own passes and times (and not all others).
For example, in Audio Control can an option be added to choose callouts only for a selected single pilot, or all pilots. 
I see there's a variable for this purpose named `primaryPilot` in rotorhazard.js and current.html - which could be given a value by the user client in an option in Audio Control?
I think it could encourage the use of the RH server by pilots on their own smartphones, but please say if you think this is an option too far.

**Comment by HazardCreative** [comment]
See `Voice Calls` option in the `Audio Control` panel on the Current Race page.

**Comment by martinglass** [comment]
Damn! Don’t know how I missed that. I looked through the options but obviously overlooked the one I was searching for. Doh!
