### ISSUE TITLE
Bitmaps not displaying after updated to Commits on Apr 28, 2021

### ISSUE THREAD

**Issue by BoLtWD** [RotorHazard/RotorHazard#569]
updated to Commits on Apr 28, 2021

Bitmaps not displaying after updating, leds are working with std LED effects like "sparkle"

LED Control Effect on drop down is also not displaying bitmaps

**Comment by HazardCreative** [comment]
Please be sure to update all dependencies, then supply your log output.

**Comment by BoLtWD** [comment]
Updated dependencies

pi@RACE_TIMER:~/RotorHazard/src/server $ python server.py
RotorHazard v3.1.0-dev.4
Release: 3.1.0-dev.4 / Server API: 32 / Latest Node API: 35
Host machine: Raspberry Pi 3 Model B Rev 1.2
Host OS: Linux 4.19.66-v7+
Python version: 2.7.13 (default, Sep 26 2018, 18:42:22)
Host machine is 'RACE_TIMER' at 10.0.0.8
Using configuration file 'config.json'
Using log file: logs/rh_20210428_214015.log
Loaded module i2c_helper
Loaded module i2c_node
Loaded module serial_node
Searching for I2C nodes...
...I2C node 1 found at address 8, API_level=35, fw_version=1.1.4, fw_type=Arduino, fw_timestamp: Apr 28 2021 18:43:35
...I2C node 2 found at address 10, API_level=35, fw_version=1.1.4, fw_type=Arduino, fw_timestamp: Apr 28 2021 18:43:35
...I2C node 3 found at address 12, API_level=35, fw_version=1.1.4, fw_type=Arduino, fw_timestamp: Apr 28 2021 18:43:35
...I2C node 4 found at address 14, API_level=35, fw_version=1.1.4, fw_type=Arduino, fw_timestamp: Apr 28 2021 18:43:35
...I2C node 5 found at address 16, API_level=35, fw_version=1.1.4, fw_type=Arduino, fw_timestamp: Apr 28 2021 18:43:35
...I2C node 6 found at address 18, API_level=35, fw_version=1.1.4, fw_type=Arduino, fw_timestamp: Apr 28 2021 18:43:35
...I2C node 7 found at address 20, API_level=35, fw_version=1.1.4, fw_type=Arduino, fw_timestamp: Apr 28 2021 18:43:35
...I2C node 8 found at address 22, API_level=35, fw_version=1.1.4, fw_type=Arduino, fw_timestamp: Apr 28 2021 18:43:35
Number of nodes found: 8
Loaded module bme280_sensor
Loaded module ina219_sensor
Loaded module linux_sensor
BME280 found at address 0x76 ('i2c:0x76')
gain set to 0.04V
calibrate called with: bus max volts: 32V, max shunt volts: 0.04V
max possible current: 0.400A
current LSB: 1.220e-05 A/bit
power LSB: 2.439e-04 W/bit
max current before overflow: 0.3996A
max shunt voltage before overflow: 39.9598mV
calibration: 0x8333 (33587)
Current overflow detected - attempting to increase gain
gain is currently: 0.04V
calibrate called with: bus max volts: 32V, max shunt volts: 0.08V
max possible current: 0.800A
current LSB: 2.439e-05 A/bit
power LSB: 4.878e-04 W/bit
max current before overflow: 0.7992A
max shunt voltage before overflow: 79.9195mV
calibration: 0x4199 (16793)
gain set to: 0.08V
INA219 found at address 0x40 ('i2c:0x40')
gain set to 0.04V
calibrate called with: bus max volts: 32V, max shunt volts: 0.04V
max possible current: 0.400A
current LSB: 1.220e-05 A/bit
power LSB: 2.439e-04 W/bit
max current before overflow: 0.3996A
max shunt voltage before overflow: 39.9598mV
calibration: 0x8333 (33587)
gain set to 0.04V
calibrate called with: bus max volts: 32V, max shunt volts: 0.04V
max possible current: 0.400A
current LSB: 1.220e-05 A/bit
power LSB: 2.439e-04 W/bit
max current before overflow: 0.3996A
max shunt voltage before overflow: 39.9598mV
calibration: 0x8333 (33587)
gain set to 0.04V
calibrate called with: bus max volts: 32V, max shunt volts: 0.04V
max possible current: 0.400A
current LSB: 1.220e-05 A/bit
power LSB: 2.439e-04 W/bit
max current before overflow: 0.3996A
max shunt voltage before overflow: 39.9598mV
calibration: 0x8333 (33587)
Core temperature available
Set Profile to '4'
LED: selecting library "rpi_ws281x"
LED: hardware GPIO enabled, count=256, pin=10, freqHz=800000, dma=10, invert=False, chan=0, strip=GRB/528384
Loaded module led_handler_bitmap
Loaded module led_handler_character
Loaded module led_handler_strip
Loaded module data_export_csv
Loaded module data_export_json
Running http server at port 5000
Interface: Starting background thread
Interface: Retry (checksum) in read_block:  addr=10 cmd=13 size=8 retry=2 ts=173.075071418
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "/home/pi/RotorHazard/src/server/led_event_manager.py", line 182, in activateEffect
    args['handlerFn'](args)
  File "/home/pi/RotorHazard/src/server/led_handler_bitmap.py", line 44, in showBitmap
    setPixels(img)
  File "/home/pi/RotorHazard/src/server/led_handler_bitmap.py", line 31, in setPixels
    px = img.getpixel((c, row))
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1215, in getpixel
    return self.im.getpixel(xy)
IndexError: image index out of range
2021-04-28T20:41:00Z <Greenlet at 0x744941c8: <bound method LEDEventManager.activateEffect of <led_event_manager.LEDEventManager instance at 0x751c4cd8>>({'Language': <Language.Language instance at 0x7542)> failed with IndexError


Above selected in LED dropdown Effect "RotorHazard" then clicked GO

**Comment by HazardCreative** [comment]
Python 2.7 is end of life and no longer officially supported. Please update your Python version and re-test.

**Comment by BoLtWD** [comment]
Sorry for a stupid question but I have tried upgrading  Python but somehow I am doing something wrong.

Could you advise what to type to update Python version?

**Comment by BoLtWD** [comment]
Below is what I found to upgrade, when I did this the python version showed up as 3.9.4, on boot up RotorHazard started.
When I stopped RotorHazard  "sudo systemctl stop rotorhazard" then "cd ~/RotorHazard/src/server" "python server.py" the server would not manually start. I stopped the server so I could supply your log output. 

I am a total novice but always give things a try...


sudo apt-get update  

sudo apt-get install -y build-essential tk-dev libncurses5-dev libncursesw5-dev libreadline6-dev libdb5.3-dev libgdbm-dev libsqlite3-dev libssl-dev libbz2-dev libexpat1-dev liblzma-dev zlib1g-dev libffi-dev

wget https://www.python.org/ftp/python/3.9.4/Python-3.9.4.tgz

sudo tar zxf Python-3.9.4.tgz  

cd Python-3.9.4

sudo ./configure --enable-optimizations

sudo make -j 4

sudo make altinstall

python3.9 -V

echo "alias python=/usr/local/bin/python3.9" >> ~/.bashrc

source ~/.bashrc

To check version  by tying below
python -V

**Comment by ethomas997** [comment]
Please see here in the RH docs:  https://github.com/RotorHazard/RotorHazard/blob/main/doc/Software Setup.md#python

**Comment by BoLtWD** [comment]
Fully updated 


pi@RACE_TIMER:~ $ sudo systemctl stop rotorhazard
pi@RACE_TIMER:~ $ cd ~/RotorHazard/src/server
pi@RACE_TIMER:~/RotorHazard/src/server $ python server.py
RotorHazard v3.1.0-dev.5
Release: 3.1.0-dev.5 / Server API: 32 / Latest Node API: 35
Host machine: Raspberry Pi 3 Model B Rev 1.2
Host OS: Linux 4.19.66-v7+
Python version: 3.5.3 (default, Apr  5 2021, 09:00:41)
Host machine is 'RACE_TIMER' at 10.0.0.8
Using configuration file 'config.json'
Using log file: logs/rh_20210429_222225.log
Loaded module i2c_helper
Loaded module i2c_node
Loaded module serial_node
Searching for I2C nodes...
...I2C node 1 found at address 8, API_level=35, fw_version=1.1.4, fw_type=Arduino, fw_timestamp: Apr 28 2021 18:43:35
...I2C node 2 found at address 10, API_level=35, fw_version=1.1.4, fw_type=Arduino, fw_timestamp: Apr 28 2021 18:43:35
...I2C node 3 found at address 12, API_level=35, fw_version=1.1.4, fw_type=Arduino, fw_timestamp: Apr 28 2021 18:43:35
...I2C node 4 found at address 14, API_level=35, fw_version=1.1.4, fw_type=Arduino, fw_timestamp: Apr 28 2021 18:43:35
...I2C node 5 found at address 16, API_level=35, fw_version=1.1.4, fw_type=Arduino, fw_timestamp: Apr 28 2021 18:43:35
...I2C node 6 found at address 18, API_level=35, fw_version=1.1.4, fw_type=Arduino, fw_timestamp: Apr 28 2021 18:43:35
...I2C node 7 found at address 20, API_level=35, fw_version=1.1.4, fw_type=Arduino, fw_timestamp: Apr 28 2021 18:43:35
...I2C node 8 found at address 22, API_level=35, fw_version=1.1.4, fw_type=Arduino, fw_timestamp: Apr 28 2021 18:43:35
Number of nodes found: 8
Loaded module linux_sensor
Core temperature available
Set Profile to '1'
LED: selecting library "rpi_ws281x"
LED: hardware GPIO enabled, count=256, pin=10, freqHz=800000, dma=10, invert=False, chan=0, strip=GRB/528384
Loaded module led_handler_bitmap
Loaded module led_handler_character
Loaded module led_handler_strip
Loaded module data_export_csv
Loaded module data_export_json
Running http server at port 5000
Interface: Starting background thread
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "/home/pi/RotorHazard/src/server/led_event_manager.py", line 182, in activateEffect
    args['handlerFn'](args)
  File "/home/pi/RotorHazard/src/server/led_handler_bitmap.py", line 44, in showBitmap
    setPixels(img)
  File "/home/pi/RotorHazard/src/server/led_handler_bitmap.py", line 31, in setPixels
    px = img.getpixel((c, row))
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 1215, in getpixel
    return self.im.getpixel(xy)
IndexError: image index out of range
2021-04-29T21:23:03Z <Greenlet at 0x740d1d78: <bound method LEDEventManager.activateEffect of <led_event_manager.LEDEventManager object at 0x7436e4b0>>({'manager': <led_event_manager.LEDEventManager obj)> failed with IndexError

Above selected in LED dropdown Effect "RotorHazard" then clicked GO

**Comment by BoLtWD** [comment]
configuration & hardware

Is the old Delta5 board with 8 nodes
Fitted is a RTC, BME280 and INA219
I use a Lan wire to connect the timer to a router.
Power for the LEDs is from a Supply Module , 

LED panel works ok with bitmaps if I back date to RotorHazard-Commits on 2 Mar 05, 2021, this is on the same Fully updated platform as I have tested Commits on Apr 28, 2021 on that dos not display bitmaps. All other LED functions work ok its just the bitmaps.

Note I have also updated as below still same.



pip3 install --user --upgrade pillow

Successfully installed pillow-7.2.0


pip3 install --user --upgrade libjpeg

pi@RACE_TIMER:~ $ pip3 install --user --upgrade libjpeg
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement libjpeg
ERROR: No matching distribution found for libjpeg

**Comment by HazardCreative** [comment]
libjpeg is not a python package, (see top for led_handler_bitmap.py,) but I'm not convinced it's the source of this issue. Still not sure how to reproduce. What's in your config.json?

**Comment by BoLtWD** [comment]
{
	"GENERAL": {
		"HTTP_PORT": 5000,
		"ADMIN_USERNAME": "admin",
		"ADMIN_PASSWORD": "PASSWORD",
		"DEBUG": true,
		"CORS_ALLOWED_HOSTS": "*"
	},
	"HARDWARE": {
		"I2C_BUS": 1
	},
    "SENSORS": {
            "i2c:0x76": {
                    "name": "Climate"
            },
            "i2c:0x40": {
                    "name": "Battery",
                    "max_current": 0.1
            }
    },
	"SERIAL_PORTS": [],
	"LED": {
		"LED_COUNT": 256,
		"LED_PIN": 10,
		"LED_FREQ_HZ": 800000,
		"LED_DMA": 10,
		"LED_INVERT": false,
		"LED_CHANNEL": 0,
		"PANEL_ROTATE": 0,
		"INVERTED_PANEL_ROWS": true
	},
	"LOGGING": {
		"CONSOLE_LEVEL": "INFO",
		"SYSLOG_LEVEL": "NONE",
		"FILELOG_LEVEL": "INFO",
		"FILELOG_NUM_KEEP": 30,
		"CONSOLE_STREAM": "stdout"
	}
}

**Comment by BoLtWD** [comment]
Just installed below again no change same issue

sudo apt-get install libjpeg-dev
sudo pip install pillow

**Comment by HazardCreative** [comment]
Your configuration seems to be missing LED_ROWS (which I assume will be 16 for you if your count is 256).

Removing it on my test setup didn't cause an error, but it certainly creates an undesirable output.

**Comment by BoLtWD** [comment]
That was it..... fixed

In my config.json I added   "LED_ROWS": 16,  and I got back the bitmaps, strange as before this update this line was omitted yet all worked ok.

I noticed in config-dist.json there is no line added for LED_ROWS this is what I based my config on, as this was not there I did not enter anything. 
Should this like be added to config-dist.json so others know that this should be used to add rows?

Once again you pulled it out of the bag, hope I have helped in some way by testing.

Thank you

**Comment by HazardCreative** [comment]
Previously the bitmap handler didn't really care about the size of the panel, it just started writing out pixels. If the panel didn't match the source image size exactly, it would fail. Now the image is scaled, but to do this it needs to know the panel's size.

This was a useful thread that exposed an area we can improve. I'll look into what can be done to prevent it.
