### ISSUE TITLE
Update FatShark Sharkbyte Channels for FPV Frequency Reference Chart

### ISSUE THREAD

**Issue by ichiemo** [RotorHazard/RotorHazard#570]
Fatshark as of the latest update had changed the frequencies of channels 6,7, and 8 to make them in numerical order. So no channel 6 is 5839 instead of channel 8 and channel 7 is 5878 instead of channel 6 and channel 8 is 5914 instead of channel 7.

A link to the updated manual is here: http://s3.amazonaws.com/helpscout.net/docs/assets/52a0a907e4b010488044ba40/attachments/5fe28c1940f24b1b2aaf3be5/Shark-Byte-User-Manual-12122020.pdf

**Comment by HazardCreative** [comment]
This affects not just the reference chart but also the frequency selectors in the system itself. Thanks for the reference link. We will definitely get this done.
