### ISSUE TITLE
Complete results export for CSV

### ISSUE THREAD

**Issue by Aaronsss** [RotorHazard/RotorHazard#576]
The CSV output on the export tool doesn't include all the race data. Is it possible to get a CSV version that contains all of the data like the JSON (complete) output?

Running v3.0.0-beta.2

**Comment by HazardCreative** [comment]
CSV currently offers only a friendly output because the format does not supported nested objects. This complicates a number of data relationships. An exporter can definitely be written as the system is very flexible, but it isn't obvious how that should happen. 

What data are you hoping to get in CSV format that isn't available now?

**Comment by Aaronsss** [comment]
People are interested to see their individual lap times usually which was what I was hoping to get out of the csv

**Comment by HazardCreative** [comment]
Individual lap times should be included. CSV Results appear in this order:

- Event summaries
- `Class: X` header and class summary, if used
- `Heat X` header
- If multiple rounds exist, a `Heat Summary`
- `Round X` aggregate data
- `Round X Times` individual lap data

If your export does not contain these, please supply your database and log for investigation.

**Comment by Aaronsss** [comment]
It seems to stop after event summary, see image below

uploaded database and log

[rh_logs_20210511_212527.zip](https://github.com/RotorHazard/RotorHazard/files/6461830/rh_logs_20210511_212527.zip)
![image](https://user-images.githubusercontent.com/23297034/117880282-d8191a00-b29f-11eb-9951-3831ea3ba7bc.png)

**Comment by HazardCreative** [comment]
Thank you for the follow up. With this database and log I was able to reproduce the issue and correct it.
