### ISSUE TITLE
%FREQS% callout is confusing

### ISSUE THREAD

**Issue by Aaronsss** [RotorHazard/RotorHazard#577]
Today I used %FREQS% to let people know their frequencies. Almost everyone was confused by the way it announces the frequencies. This is because it pauses before it announces the frequency but not before the next pilot name.

Is it possible to make it clearer somehow?

Running v3.0.0-beta.2

**Comment by HazardCreative** [comment]
I've already made some changes to this for 3.1. Let me know if the current revision in the main branch resolves this for you.

**Comment by Aaronsss** [comment]
I took a look at it but I didnt notice any difference

**Comment by HazardCreative** [comment]
The phonetic callout API doesn't provide a lot of fine control. 

Open the developer tools in your browser and find the JavaScript console. Which you you prefer?
1. `speak('<div class="speech">Pilot A:R1, Pilot B:R3, Pilot C:R6</div>');`
2. `speak('<div class="speech">Pilot A: R1, Pilot B: R3, Pilot C: R6</div>');`
3. `speak('<div class="speech">Pilot A: R1. Pilot B: R3. Pilot C: R6</div>');`

**Comment by Aaronsss** [comment]
1 and 2 sound the same to me. 

I think 3 sounds the best

**Comment by HazardCreative** [comment]
Maybe they are for you. There could be differences in the speech interpreter from one OS to another.

**Comment by Aaronsss** [comment]
Windows 10 Chrome is as above

Windows 10 Firefox the first 2 sound different but I think the third is still best

**Comment by HazardCreative** [comment]
I find the 3rd callout option to delay longer than necessary, but there's no question that it's clearer on intent. There's a chance pilots will begin to ignore it because of the delay. I expect pilots will quickly get used to it if it is necessary to not miss their race. Clarity should prevail here so we'll implement option 3.
