### ISSUE TITLE
Clearing races isn't emptying the race results cache

### ISSUE THREAD

**Issue by BoLtWD** [RotorHazard/RotorHazard#58]
Add a button for the database under Database

button onclick="location.href='/database';">Database</button

**Comment by HazardCreative** [comment]
What would the button do?

**Comment by BoLtWD** [comment]
Its just to View the database as sometimes I find when you have selected delete races and return to rounds the data is still there yet when you look in the database its gone. I guess its so you can check the database of what data you are holding in there.

**Comment by HazardCreative** [comment]
That button appears if you switch the Debug setting to "true" in your configuration file.
Sounds like there's a separate bug in the race results behavior. I bet that clearing races isn't emptying the race results cache. I'll look into that; should be an easy fix.

**Comment by BoLtWD** [comment]
Agree this dose sound more like a bug, I will look into Debug setting. Thank you

**Comment by BoLtWD** [comment]
Do I need to close this and open a comment it as a bug?
