### ISSUE TITLE
Nodes not being displayed in "sensors" when firmware versions are mismatched

### ISSUE THREAD

**Issue by szafranski** [RotorHazard/RotorHazard#583]
Hello, congrats on new release. In case of mismatched firmware versions of nodes (same API, different firmware) all nodes are being recognized during server boot but older are not being shown in RH GUI and mo additional warning is being shown (like it is when API is outdated. Not a big deal but users are quite good in walking straight into edge cases. 

Possible solutions:
- always incrementing API levels, not only firmware so user see the prompt - in GUI and terminal during boot when firmware is outdated
- adding additional firmware compatibility/cohesion check - with possible prompt

Cheers, again - awesome job.

**Comment by ethomas997** [comment]
Can you post a log file from a run where nodes are not being shown?

**Comment by szafranski** [comment]
Hello, I cannot find a node code contains API35 and firmware ver. 1.1.3 (as far as I remember I had an issue with that one). 
Have you ever released node code with different firmware version and same API level? I cannot replicate issue now cause my nodes are already updated and looking back in releases i cannot find the one mentioned above.

**Comment by ethomas997** [comment]
The API level is only changed when the server-to-node protocol is modified, whereas the firmware version is updated for any node-code changes.  So, yes, there will definitely be multiple node-code versions with the same API level.  Here is the code for node version 1.1.3 (with API level 35):

https://github.com/RotorHazard/RotorHazard/archive/a599bd7129537c2b9801382adaacd622c86b65ec.zip

https://github.com/RotorHazard/RotorHazard/tree/a599bd7129537c2b9801382adaacd622c86b65ec

**Comment by szafranski** [comment]
Cannot reproduce issue now. For now - can be closed. Thx

**Comment by ethomas997** [comment]
Okay, thx, let us know if you see it again.
