### ISSUE TITLE
Need sudo privileges to access serial ports on Pi

### ISSUE THREAD

**Issue by martinglass** [RotorHazard/RotorHazard#585]
The standard setup runs the RH server as the default user, "pi".
 
With the Serial Port set in config.json, the pi can't access the serial port (as user "pi") causing the startup of the server to fail,  unless the server is run with root/superuser/sudo privileges.

**Comment by ethomas997** [comment]
I've not seen this on my setups.  Please provide configuration to reproduce, and log output.

**Comment by martinglass** [comment]
Can't reproduce the problem now. It was probably my bad, related to chown permissions in my folders.

I'm working on a test STM32 rig at home (which is really a great step forwards I must say, congratulations. I'm liking the serial interface a lot).

If I remember, I've been using "sudo unzip" to unzip the downloaded repository which made the files root:root ownership, and I should have used unzip instead, or changed the file-ownerships from root:root to pi:pi afterwards. I then ended up with privilege issues, so maybe this /dev/ttyUSB0 access issue was one of them.

**Comment by ethomas997** [comment]
Thanks for testing and for the feedback.
