### ISSUE TITLE
Send message before shutdown event

### ISSUE THREAD

**Issue by BoLtWD** [RotorHazard/RotorHazard#589]
Ref Commits on May 12, 2021  Update version code

The server shuts down before sending the full text to the LED panel, on my panel I only get the words "Ser"

This is the same for reboot.

The server has no delay before shutting down, the delay would give time for the Pi to send the text to the display before shutting down.

**Comment by HazardCreative** [comment]
Known issue, but good to have it here for tracking.

The entire message is passed into the LED handler, which then operates asynchronously to other timer operations. Waiting for the LED process to stop before shutdown is dangerous as some effects never complete (rainbow cycle, RSSI graph). We will consider some options.

**Comment by HazardCreative** [comment]
I've simply prevented the message effect from running during shutdown. The assigned shutdown effect is the only one that should be played on the LEDs during shutdown, and those effects can be properly restricted to those that don't cause issues like I mentioned above.
