### ISSUE TITLE
issue with preset led colors

### ISSUE THREAD

**Issue by BoLtWD** [RotorHazard/RotorHazard#590]
Updated to Commits on May 12, 2021

Think I found a bug, when using my led panel and selecting in the preset colours  in LED Controle  I am finding they are messed up.
Example..................
BLUE =  BLUE, 
ORANGE = RED, 
GREEN = GREEN, 
RED = RED, 
YELLOW = ORANGE, 
DARK BLUE = PINK, 
LIGHT BLUE = LIGHT BLUE, 
GRAY = ORANGE 

Using the mixer and then selecting any pattern, press go I can get yellow and any color I select

**Comment by HazardCreative** [comment]
I'm not quite following you. Can you try to explain in more detail?

**Comment by BoLtWD** [comment]
On the page for RUN under leds there are 8 preset colours , if I select them I get a color example Blue = Blue however I find some are messed up example  YELLOW = ORANGE on my panel.  On the run page using the drop downs if I select any pattern then press go button I can get yellow, so I know this is not an issue with my panel as far as I can see.

This issue looks to be with the preset colors not corresponding to a color it should represent.

BLUE = BLUE,
ORANGE = RED,
GREEN = GREEN,
RED = RED,
YELLOW = ORANGE,
DARK BLUE = PINK,
LIGHT BLUE = LIGHT BLUE,
GRAY = ORANGE

**Comment by HazardCreative** [comment]
Can you provide a visual reference with photos and screen captures?

**Comment by BoLtWD** [comment]
I think this is to do with the panel as the led strip is ok it's like the red colour is more dominant on the panel off setting the mix. 

is there no way of adjusting this?

![Untitled](https://user-images.githubusercontent.com/25492262/118522845-6d9b2a80-b734-11eb-878b-c33b8f9c1b3f.jpg)

**Comment by HazardCreative** [comment]
Thanks. This is very helpful to understanding.

Something is odd with your panel and it seems to be hardware related. We can confirm with your strip tests that RH is sending the correct color values. It could be power related. It looks like the panels at times simply don't power on all of the internal diodes. Using a stronger power supply or changing your brightness level could help with this. I often use my panel at very low brightness levels.

RH does check the database for a serialized JSON array in the options table under 'ledColorNodes'. However, no UI yet exists to manage this data array. You can set up a different node color table that your panel can better reproduce, but as of now you will have to do it manually via database manipulation. (Future versions are likely to provide UI for creating and editing these values.)

**Comment by BoLtWD** [comment]
Found it, put a lab PSU on the panel and look like I underestimated the power needed looks like I need a PSU that will give 6 amps. I found this by dialing down the LED brightness and when I did found the colours to be correct. as soon as I increased the brightness past a threshold that is when the colour mix went strange.

In sort power to the panel need more amps

**Comment by HazardCreative** [comment]
Great! No bugs here.
