### ISSUE TITLE
RSSI on LED panel displays all channels regardless if any are disable. 

### ISSUE THREAD

**Issue by BoLtWD** [RotorHazard/RotorHazard#592]
Updated to commits on May 12, 2021

One of the events displays RSSI on a panel, the RSSI on the panel still shows the full amount of channels you have  regardless if any of them have been disabled.

**Comment by BoLtWD** [comment]
Again I ran a practice run for the pilots but found the disable channels displaying full RSSI value distracting. If channels are disabled then the corresponding RSSI on the panel should also be disabled.

**Comment by HazardCreative** [comment]
Closed with ca96883.
