### ISSUE TITLE
Event Results - Not showing data from all heats

### ISSUE THREAD

**Issue by CerberusVelvet** [RotorHazard/RotorHazard#599]
In version - Version: 3.1.0-beta.1

After running one round of each of three heats. In the 'Race Results' page all three heats show expected lap data. However 'Event Data' only shows results from the pilots in the third heat.

![image](https://user-images.githubusercontent.com/29674976/121238209-c3747580-c88f-11eb-91b8-4bf2420d6d90.png)

![image](https://user-images.githubusercontent.com/29674976/121238255-d25b2800-c88f-11eb-933d-bb75917f967c.png)

![image](https://user-images.githubusercontent.com/29674976/121238296-db4bf980-c88f-11eb-808b-d415b537f2e4.png)

![image](https://user-images.githubusercontent.com/29674976/121238327-e30b9e00-c88f-11eb-8ce2-28f9b040973c.png)

Logs attached:

[rh_logs_20210608_192659.zip](https://github.com/RotorHazard/RotorHazard/files/6618815/rh_logs_20210608_192659.zip)

**Comment by HazardCreative** [comment]
Thanks for the clear submission and error case log.
