### ISSUE TITLE
Add image of Sample RSSI Graph

### ISSUE THREAD

**Issue by BoLtWD** [RotorHazard/RotorHazard#60]
Add image of Sample RSSI Graph under Troubleshooting to give a visual representation of what is going on. This would be the same as you have in the \doc\img but saved as a jpg and inserted as above.

**Comment by HazardCreative** [comment]
Makes sense, and we've [already got a graphic for this](https://github.com/RotorHazard/RotorHazard/blob/master/doc/img/Sample%20RSSI%20Graph.svg) in the docs section.
