### ISSUE TITLE
Restore Database Issues

### ISSUE THREAD

**Issue by Aaronsss** [RotorHazard/RotorHazard#600]
I have found some database bugs in 3.1.0 beta 1 

1. Database restore seems to be a bit temperamental as sometimes it doesn't restore properly and just shows no race data
2. When restoring the database, it sometimes changes my Rotorhazard theme settings back to default usually when the error in 1 happens
3. It seems to have deleted rounds 3 and 4 from heats B, C & D
4. After marshalling the rounds to publish the results the event leader board didn’t display any names 

Database attached for analysis:
database.db is after I have marshalled
the other is the original backup from the race

[rh_logs_20210609_232111.zip](https://github.com/RotorHazard/RotorHazard/files/6627232/rh_logs_20210609_232111.zip)

**Comment by HazardCreative** [comment]
Point 4 may have been related to #599. After updating with those commits, please report back if you see that particular issue again.

**Comment by HazardCreative** [comment]
Resolved a bug that was the most likely cause. Please report back if you continue to have issues.
