### ISSUE TITLE
win condition

### ISSUE THREAD

**Issue by BoLtWD** [RotorHazard/RotorHazard#62]
Is there any other drone racing win conditions other than the official that can be added?

Currently the main win condition is based around the most laps or first to a number of laps. 

I would like to see more FUN unofficial win conditions that take into consideration that a drone can be accidentally taken out of a race by another opponent based on something like fastest average X (selective number) laps within a timed race. 
This may give someone a chance to still be in a race though crashed out as long as they have achieved a number of laps.

I must admit I have been looking on the internet and cant see any to guide me in advice to win conditions.

May be others may have a better formula than me as this is only a theory .....

**Comment by HazardCreative** [comment]
More win conditions are coming. There are already a few more partly
implemented but not complete. I welcome discussion on what to include as
well as formats that are needed to support them. Please let me know what
your research turns up.
