### ISSUE TITLE
Repeated error in the logs

### ISSUE THREAD

**Issue by Aaronsss** [RotorHazard/RotorHazard#622]
Running 3.1 beta 2 I have spotted the following error keeps cropping up in the logs. Not sure if its known about but thought it worth reporting. I have attached the files from the weekend as there were about 550 recorded laps so it may be useful feedback for the current release. 

I did notice on the earlier of the two database files things really started getting slow with page loads. I guess that's known about but thought it worth mentioning 

Traceback (most recent call last):
  File "/home/pi/RotorHazard/src/server/RHUtils.py", line 180, in wrapper
    return func(*args, **kwargs)
  File "server.py", line 2217, in race_expire_thread
    check_win_condition(at_finish=True, start_token=start_token)
  File "server.py", line 4134, in check_win_condition
    win_status = Results.check_win_condition(RACE, RHData, INTERFACE, **kwargs)
  File "/home/pi/RotorHazard/src/server/Results.py", line 850, in check_win_condition
    return check_win_fastest_consecutive(raceObj, **kwargs)
  File "/home/pi/RotorHazard/src/server/Results.py", line 1155, in check_win_fastest_consecutive
    if fast_consecutives > 0: # must have recorded time (otherwise impossible to set bounds)
TypeError: '>' not supported between instances of 'NoneType' and 'int'

[Files.zip](https://github.com/RotorHazard/RotorHazard/files/6957669/Files.zip)

**Comment by HazardCreative** [comment]
Thanks for reporting. I think this is just a case of Py 3 being a bit more strongly typed than Py 2. Should be an easy one to repair once I have the time to pick it up.
