### ISSUE TITLE
Step missing from Software Setup.md

### ISSUE THREAD

**Issue by lundyfpv** [RotorHazard/RotorHazard#625]
There is no mention of creating a config.json file in the Software Setup guide. It should be located in Step 6. Install the RotorHazard Server. 

I believe for a basic setup it is simply "cp config-dist.json config.json", and it should be located after the pip install. 

![image](https://user-images.githubusercontent.com/8151341/134194820-bf69cba6-de4a-4c79-b488-1841b728b959.png)

**Comment by ethomas997** [comment]
This is described at the beginning of the User Guide -- we should probably pull that "Set up Config File" section into the Software Setup.  (Also, we should mention the User Guide in Software Setup.)

**Comment by lundyfpv** [comment]
Yeah I mean it just needs to be mentioned in the software setup guide. I'm pretty familiar with this stuff and was able to understand what was wrong but many users will have 0 clue why they get an error when in the webui.
