### ISSUE TITLE
Feature Request: Node code option for (non-SPI) 8-ch RX5808s

### ISSUE THREAD

**Issue by martinglass** [RotorHazard/RotorHazard#630]
I was thinking it might be useful to add a node code option for (non-SPI) RX5808s. 

I suspect the main use would be builders who want to test their VRX modules to find out whether they are SPI-capable or not, by the ability to alter the node firmware for either SPI or non-SPI. 

I understand the 8 default channels on the non-SPI VRXs are Boscam Band E:
5705 5685 5665 5645 5885 5905 5925 5945

https://www.foxtechfpv.com/product/5.8G%20modules/rx5808/RX5808-Spec-V1.pdf

I guess there'd need to be additional code for the RH server to recognise the non-SPI node and restrict the frequency table to just E1 to E8.

**Comment by HazardCreative** [comment]
Not planned. 
- It's a lot of work for not a great amount of benefit. 
- #655 is a better solution for testing modules
- E-band contains many channels not strictly legal to use in most places, so it's best not to encourage/make easier
