### ISSUE TITLE
System Lag/Hang

### ISSUE THREAD

**Issue by Strangedave** [RotorHazard/RotorHazard#631]
Repost from FB Groups

Ok, this is gonna be a long one. So I have been running a rotor hazard timer for probably 2 years now. I have had occasions where we have a lot of pilots and the timer feels bogged down after 8-9 rounds with 3 heats and 4-5 pilots per heat. This week we had 18 pilots for whoop racing and the timer literally locked up at like 3 rounds. I have a backup that I bought from another club. That system stopped working also. I checked voltage and changed network cables. We are POE, so I wanted to make sure that was not the issue. Is there any one here that might be able to help me debug these timers. Whoop season has some pretty big turnouts here, and I'm sure you all know how things can turn ugly when the timer isn't running. Both rigs are basically the same except one is pi4 and the other is pi 3b. The pi3 machine has been basically unusable. The pi4 can get through a night pretty well, but will be slow by the end of the night. Another guy in the group is building a blue pill setup, so we will get a chance to see how that works in the next few days. We did ssh into both systems tonight and cpu usage was always below 10%. So I'm kinda stumped.
**To Reproduce**
We tested the main timer and revised the 2nd timer to be a split unit in the config.json file. We ran 5 pilots for 8 rounds without any issue. The secondary/split unit did not run, I have no idea why. the main unit ran acceptably though. I am going to get 5 rigs on different channels and try and generate 4 heats with 5 pilots tonight. to see if I can make the system hang. 

**Expected behavior**
Just needs to run. The pilots get antsy when we are waiting for the timer to start the race. at the event in question the start button was clicked, and the start tones would not start the race for 30-40 seconds in some instances.

**Log Dump**
Attached for both systems.

**Desktop (please complete the following information):**
 - Windows 10 Pro 20h2
 - Chrome
 - rh 3.0

**Smartphone (please complete the following information):**
We did not connect via smart phone or tablet
 - 
[Main rh_logs_20211105_124602.zip](https://github.com/RotorHazard/RotorHazard/files/7487956/Main.rh_logs_20211105_124602.zip)
]

**Additional context**
Add any other context about the problem here
[Secondary rh_logs_20211105_124806.zip](https://github.com/RotorHazard/RotorHazard/files/7487975/Secondary.rh_logs_20211105_124806.zip)
.

**Comment by HazardCreative** [comment]
Have you tested with 3.1? There were considerable improvements to performance.

**Comment by Strangedave** [comment]
I have not, I’ll try and throw it on the backup box for testing at our Tuesday night event.

**Comment by ethomas997** [comment]
My recommendation would be to simplify things: run a single unit (no split timer) on the latest beta code, and see if you can get it to act up.  If it does then check the log file for any errors, etc at the time of the problems, and you could also post it here.

Are you networking through a switch or router?  I've seen freezing and lagging when there are network issues.

**Comment by Strangedave** [comment]
Ok, we did a bunch of diagnostic, hundreds of laps, and rounds of testing, and everything worked perfectly. Until tonight, the big event. once the timer was up and running and we were ready to kick off the first heat, the whole thing locked up. same as last time. This time we had everything we needed to check all the temps, voltages. we worked back through the whole system while one of the guys ran the event on our laprf. Turns out the entire problem was the router. We swapped in for a spare and WABAMO. we are back in business. Sorry for bugging you guys with my equipment issues. It also gave us a chance to remember just how much it sucks to try and time whoops with a laprf. Thanks for all of your time and effort, and again I'm sorry we didn't catch this earlier.

**Comment by ethomas997** [comment]
Called it -- network issue. :]  Hey, no worries, glad it's working better for you.

**Comment by Strangedave** [comment]
I literally had the second Router spun up and ready, just wanted to make sure we were finding the issue.  But you were correct. Thanks for the help.

**Comment by HazardCreative** [comment]
Thanks so much for putting in the effort to nail down the problem.

**Comment by Strangedave** [comment]
It’s the least we could do. Thanks for all of your hard work!
