### ISSUE TITLE
Weird issues with Adafruit_GPIO on the newest Raspbian 11 (Bullseye)

### ISSUE THREAD

**Issue by szafranski** [RotorHazard/RotorHazard#632]
**Describe the bug**
Hi, after installing RotorHazard on the fresh SD card with newest RaspberryPi OS (Bullseye),
I got some errors. I generally have weird issues with this OS but after finally SSHing in it
and installing RH using OTA I go what's shown below:

<img width="922" alt="image" src="https://user-images.githubusercontent.com/23621888/140914610-2f3ff44c-9822-4adc-b238-5c67d9e0bcb3.png">

RaspberryPi OS:
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

To be clear, there are 3 separate issues/questions/possible assumptions from my side:
1. I generally have bad experiences with this OS for now, you can try to make a fresh installation and check how it works for you. It maybe wort mentioning on the group to stick with Buster for now if you will have same issues as me. I can elaborate that part if you want.
2. It's possible that those issues are OTA related and I have to dig deeper in this software
3. It is possible that RotorHazard does not work well with Bullseye, despite what's above

**Comment by martinglass** [comment]
Jarosław, I'm not an expert but the first thing I'd do is check that the I2C bus is activated on the Pi using raspi-config.

**Comment by szafranski** [comment]
Jarosław? :) I2C is enabled and works. Nodes are being found.

**Comment by martinglass** [comment]
Sorry. I mixed you up with someone else. Pawel then? 🤣

How do you see the Nodes working? on the Pi?

The log says that the I2C bus cannot be found, which indicates a problem on the Pi's I2C bus.

**Comment by szafranski** [comment]
Yes, Paweł :) I will check. But it worked with previous version of RaspberryPi OS so that's something to check anyways.

**Comment by szafranski** [comment]
I will investigate further but for now I just wanted to let you know that same happens on fresh OS, when RotorHazard is installed without using OTA. Just a normal, step-by-step procedure. Without adding sensors etc. Just a "minimum installation"
![image](https://user-images.githubusercontent.com/23621888/141071098-2cb97dda-87a8-4673-a682-724ef4a9e1bc.png)

**Comment by szafranski** [comment]
Sorry for multiple messages but looks like I may be onto something. Looks like there is a problem with adafruit_gpio ability to report Pi (platform) version properly.

**Comment by szafranski** [comment]
Another finding - it is being install when this dependency is being installed:
pi-ina219==1.4.*

**Comment by szafranski** [comment]
Ok, Adafruit_GPIO cannot be installed cause without it INA219 is not being recognized. The fix is to make simple tweak to Adafruit_GPIO library so the RaspberryPi is being reported as recognized. I will implement the oneliner as below to OTA:
`sudo sed -i 's/UNKNOWN          = 0/UNKNOWN          = 1/' /usr/local/lib/python3*/dist-packages/Adafruit_GPIO/Platform.py
`
Without it there is just error instead of RaspberryPi being reported. 

So the fix is found but requires a new line of code implemented in a script. Using OTA - no problem. Not that manual installation would need it too as well.

**Comment by szafranski** [comment]
Ok, Adafruit_GPIO cannot be installed cause without it INA219 is not being recognized. The fix is to make simple tweak to Adafruit_GPIO library so the RaspberryPi is being reported as recognized. I will implement the one-liner to OTA.

It changes:
`UNKNOWN          = 0
`to
`UNKNOWN          = 1 
`
so it defaults to Raspberry Pi, not to "UNKNOWN"

So the fix is found but requires a new line implemented in a script. Using OTA - no problem. Not that manual installation would need it too as well.

**Comment by ethomas997** [comment]
What type of RPi were you using?  I tried doing a fresh install of the latest RPi OS ("2021-10-30-raspios-bullseye") on a "Raspberry Pi 3 Model B Plus Rev 1.3" and it runs fine with both an S32_BPill board (with INA219) and with a pair of old Delta5 boards (no INA219):
```
Starting RotorHazard...
RotorHazard v3.1.0-beta.3
Release: 3.1.0-beta.3 / Server API: 32 / Latest Node API: 35
Host machine: Raspberry Pi 3 Model B Plus Rev 1.3
Host OS: Linux 5.10.63-v7+
Python version: 3.9.2
Host machine is 'pi3number98' at 192.168.0.98
Using configuration file 'config.json'
Using log file: logs/rh_20211114_000311.log
Loaded module i2c_helper
Loaded module i2c_node
Loaded module serial_node
Searching for I2C nodes...
...I2C node 1 found at address 8, API_level=35, fw_version=1.1.2, fw_type=Arduino, fw_timestamp: Apr 10 2021 00:55:33
...I2C node 2 found at address 10, API_level=35, fw_version=1.1.2, fw_type=Arduino, fw_timestamp: Apr 10 2021 00:56:53
...I2C node 3 found at address 12, API_level=35, fw_version=1.1.2, fw_type=Arduino, fw_timestamp: Apr 10 2021 00:57:29
...I2C node 4 found at address 14, API_level=35, fw_version=1.1.2, fw_type=Arduino, fw_timestamp: Apr 10 2021 00:58:12
...I2C node 5 found at address 16, API_level=35, fw_version=1.1.2, fw_type=Arduino, fw_timestamp: Apr 10 2021 00:59:49
...I2C node 6 found at address 18, API_level=35, fw_version=1.1.2, fw_type=Arduino, fw_timestamp: Apr 10 2021 01:00:40
...I2C node 7 found at address 20, API_level=35, fw_version=1.1.2, fw_type=Arduino, fw_timestamp: Apr 10 2021 01:01:21
...I2C node 8 found at address 22, API_level=35, fw_version=1.1.2, fw_type=Arduino, fw_timestamp: Apr 10 2021 01:02:07
Number of nodes found: 8
Loaded module bme280_sensor
Loaded module ina219_sensor
Loaded module linux_sensor
Core temperature available
Set Profile to '1'
Loaded module data_export_csv
Loaded module data_export_json
Running http server at port 5000
```

**Comment by szafranski** [comment]
Hi, Pi 4, 4GB.

**Comment by ethomas997** [comment]
Thanks for identifying the issue; I was able to reproduce it and do a code fix (explicitly setting I2C 'busnum' for INA219 via "I2C_BUS" config item)
