### ISSUE TITLE
Weird issues with port forwarding on the newest Raspbian 11 (Bullseye)

### ISSUE THREAD

**Issue by szafranski** [RotorHazard/RotorHazard#634]
Port forwarding seems to be broken on the newest Raspbian 11.
Will investigate.

**Comment by szafranski** [comment]
Looks like iptables is not installed by default. For now the fix I found is:
sudo apt install iptables

**Comment by ethomas997** [comment]
Thanks, I'll add that to the docs

**Comment by szafranski** [comment]
Sure, note that I tested it with iptables installation being performed at the beginning of the port forwarding adding script. 
(sorry for reopen)
