### ISSUE TITLE
Obsolete Python2 Installation Packages in Software Setup Documentation - Python3 (Raspbian Bullseye)

### ISSUE THREAD

**Issue by martinglass** [RotorHazard/RotorHazard#636]
Performing a fresh install and following the install instructions on 3rd December 2021:(https://github.com/RotorHazard/RotorHazard/blob/main/doc/Software%20Setup.md)

Python 3.9.2 is the default at present for Raspbian Bullseye (not Python 2.7).
> pi@rotorhazard:~ $ python --version
Python 3.9.2

After sudo apt-get update && sudo apt-get upgrade, I had to use these instructions instead of the ones in the docs, because Python2 is deprecated in Raspbian Bullseye
**_sudo apt install python3-dev libffi-dev python3-smbus build-essential python3-pip git scons swig python3-rpi.gpio_**

### Error on installing python-dev etc, because python2 is deprecated ... ###

Here's the instruction and results, showing how Python2 is now deprecated ...
> pi@rotorhazard:~ $ sudo apt install python-dev python3-dev libffi-dev python-smbus build-essential python-pip python3-pip git scons swig python-rpi.gpio python3-rpi.gpio

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'python-dev-is-python2' instead of 'python-dev'
Package python-smbus is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package python-pip is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python3-pip

Package python-rpi.gpio is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-smbus' has no installation candidate
E: Package 'python-pip' has no installation candidate
E: Package 'python-rpi.gpio' has no installation candidate

**Comment by ethomas997** [comment]
What type of Raspberry Pi are you using?

**Comment by ethomas997** [comment]
I've tried fresh installs a couple of times on a Pi 4 with the Bullseye OS.  While I do see the "Package ... has no installation candidate" messages on that command, I've found that I can ignore them and continue, and the system installs and runs fine.  Are you seeing something different?

The command may not be needed at all for the Bullseye OS, but it is needed for the previous versions of the OS.  We'll look to do some kind of tweak to the instructions noting the difference for Bullseye.

**Comment by ethomas997** [comment]
I tried a fresh setup with a Pi Zero and Bullseye Lite, and I think I'm seeing what you saw: pip, smbus, and other things missing.  I think we'll want to change to the install command that you suggest; it should be okay for the previous Pi-OS versions (I'll be doing a test to make sure).

**Comment by martinglass** [comment]
I was using the new RPi Zero 2 W.

**Comment by martinglass** [comment]
I was informed that RH3 doesn't support Py2 anyway.

Can you clarify that in the instructions too, if it's not there already?

**Comment by ethomas997** [comment]
Yes, I'll update the docs according. Thanks for posting the issue.
