### ISSUE TITLE
JSON API race/all fastest_lap_source reporting wrong source

### ISSUE THREAD

**Issue by tomidland** [RotorHazard/RotorHazard#642]
In the JSON API the **fastest_lap_source** is wrong in **by_consecutives**, **by_fastest_lap** and **by_race_time**

How to generate:
Open api/race/all and look for:
**"fastest_lap_source":{"round":1,"heat":2,"**
It will give report a round and a heat number, but it is always the same as:
**"consecutives_source":{"round":1,"heat":2,**

**Comment by HazardCreative** [comment]
Can you clarify why you closed?

**Comment by tomidland** [comment]
> Can you clarify why you closed?

I do not think there is an issue after all, I was reading "Heat id" when I thought I was reading "Heat number".  So heat with id 1 was "Heat 2" and so forth. :)

**Comment by HazardCreative** [comment]
Thanks!

Heats can be renamed by users so the auto-numbering is not a reliable identifier.
