### ISSUE TITLE
NOT a bug  - only a Question - how can I work with VisualCode and start debugging server.py

### ISSUE THREAD

**Issue by mrRobot62** [RotorHazard/RotorHazard#643]
Sorry - but I unfortunately do not know how and where else I can ask this

I forked this repo and want to debug server.py on my mac with visual code. Unfortunately I run into problems.
Is there some body, who work with VS Code AND on a mac?

BTW: grad project :-)

Cheers

**Comment by pulquero** [comment]
Not me, try asking in the facebook group too: https://www.facebook.com/groups/749387998753163
