### ISSUE TITLE
Ready, Steady....(pause)....Go !

### ISSUE THREAD

**Issue by martinglass** [RotorHazard/RotorHazard#646]
At present the staging can be set by "Minimum Start Delay" and "Maximum Start Delay", which provide the existing staging beeps (and synchronised LED lights).

But they do not reflect what is commonly expected for the start of a race.

Races using "standard" systems provide a Ready-Steady (staging short beeps)...(random length pause)...Go (long beep) sequence. It might be thought of as a two-phase staging process, instead of the present one-phase staging process.

For example, could existing the two options could change from [(min start delay) and (max start delay)], to say [(fixed staging time) and (max random time to race start)], which would not even make the UI more complicated.

Using this approach, the Race Management would initiate a race-start (from the manual or scheduled selection), with beeps that sound for the number of seconds as set by ("fixed staging time"), using tones defined by "Staging Tones", namely either [none or one a second], then followed by a random length pause, set by ("max random time to race start")

**Comment by HazardCreative** [comment]
Further discussion here: https://github.com/pulquero/RotorHazard/issues/95
