### ISSUE TITLE
RH 6 nodes - no current sensor ( ina219) on i2c?..

### ISSUE THREAD

**Issue by olivier0253** [RotorHazard/RotorHazard#648]
Hello,

I'm using a 6 nodes version but i have an issue with the current sensor...
Other things seems to be ok but i just don't see the ina219.
i tried 3.1.0 and 3.1.1, on Pi 4 & Pi 0 2 W and it's the same...
So, i think about a hardware issue, but i don't find...
Can I have your help?

![IMG_20220203_140911](https://user-images.githubusercontent.com/31970251/152380111-ad6a0b52-cc85-4e81-9fa2-fda903004d57.jpg)

![IMG_20220203_140922](https://user-images.githubusercontent.com/31970251/152380136-6819da35-9099-4bed-bb64-df975aca28f3.jpg)

and there is a part of "python server" command:

Using log file: logs/rh_20220203_151922.log
Loaded module i2c_helper
Loaded module i2c_node
Loaded module serial_node
Serial multi-node found at port '/dev/serial0', count=6, API_level=35, baudrate=921600, fw_version=1.1.4, fw_type=STM32F1, fw_timestamp: Apr 27 2021 21:17:24
Receiver modules found at slot positions: 1 2 3 4 5 6
Number of nodes found: 6
Loaded module bme280_sensor
Loaded module ina219_sensor
Loaded module linux_sensor
**No INA219 found at address 0x40**
Core temperature available
Set Profile to '1'
LED: selecting library "rpi_ws281x"
LED: hardware GPIO enabled, count=35, pin=10, freqHz=800000, dma=10, invert=False, chan=0, strip=GRB/528384
Loaded module led_handler_bitmap
Loaded module led_handler_character
Loaded module led_handler_graph
Loaded module led_handler_strip
Loaded module data_export_csv
Loaded module data_export_json
Running http server at port 5000
Server exception
Traceback (most recent call last):
  File "/home/pi/RotorHazard/src/server/server.py", line 5248, in start
    SOCKET_IO.run(APP, host='0.0.0.0', port=port_val, debug=True, use_reloader=False)
  File "/usr/local/lib/python3.9/dist-packages/flask_socketio/__init__.py", line 602, in run
    self.wsgi_server.serve_forever()
  File "/usr/local/lib/python3.9/dist-packages/gevent/baseserver.py", line 398, in serve_forever
    self.start()
  File "/usr/local/lib/python3.9/dist-packages/gevent/baseserver.py", line 336, in start
    self.init_socket()
  File "/usr/local/lib/python3.9/dist-packages/gevent/pywsgi.py", line 1500, in init_socket
    StreamServer.init_socket(self)
  File "/usr/local/lib/python3.9/dist-packages/gevent/server.py", line 180, in init_socket
    self.socket = self.get_listener(self.address, self.backlog, self.family)
  File "/usr/local/lib/python3.9/dist-packages/gevent/server.py", line 192, in get_listener
    return _tcp_listener(address, backlog=backlog, reuse_addr=cls.reuse_addr, family=family)
  File "/usr/local/lib/python3.9/dist-packages/gevent/server.py", line 288, in _tcp_listener
    sock.bind(address)

if it's be helpful

Thank you

Olivier

**Comment by ethomas997** [comment]
What is the output if you run this command in a terminal on the Pi?:  sudo i2cdetect -y 1

**Comment by olivier0253** [comment]
Hello,
With this command, i have " -- -- --"...
On each line.
Module seems to be not detected.
I tried with a precedent version of raspian, same issue...

**Comment by ethomas997** [comment]
You could try installing the DS3231 RTC chip to see if it shows up in the "sudo i2cdetect -y 1" listing; see: https://github.com/RotorHazard/RotorHazard/blob/main/doc/Real%20Time%20Clock.md

(I assume the 'I2C' interface option is enabled, as per the Software Setup instructions.)

**Comment by olivier0253** [comment]
I2C is corectly enabled via raspi-config (i tried disable/enable & reboot but no more result)

I will try with DS3231 after the week-end.

Thank you for your help

**Comment by olivier0253** [comment]
DS3231 was correctly see by "sudo i2cdetect -y 1"
but, at the same time, no more ina219...
i get this with a PI4
with a PI zero 2W, no ina & no DS3231...

**Comment by ethomas997** [comment]
Sounds like hardware or wiring issues; maybe try a different INA219?

**Comment by olivier0253** [comment]
Ok, i will try will other chip.
Although i have the same problem on 2 different pcb, they have the same hardware..
I come back as soon as i have news.
Thanks you

**Comment by ethomas997** [comment]
Great to hear it's working for you!
