### ISSUE TITLE
Security Vulnerability

### ISSUE THREAD

**Issue by haby0** [RotorHazard/RotorHazard#649]
What would be the right contact to report a security vulnerabilty? thanks!

**Comment by HazardCreative** [comment]
At present the system can't be considered secure, so right here is fine for now.

**Comment by haby0** [comment]
@HazardCreative 

The following API interface has an arbitrary file read vulnerability

https://github.com/RotorHazard/RotorHazard/blob/main/src/server/server.py#L593-L611

```python
@APP.route('/img/<path:imgfile>')
def render_viewImg(imgfile):
    '''Route to img called within doc viewer.'''

    folderBase = '../../doc/'
    folderImg = 'img/'

    while imgfile[0:2] == '../':
        imgfile = imgfile[3:]

    imgPath = folderBase + folderImg + imgfile

    language = RHData.get_option("currentLanguage")
    if language:
        translated_path = folderBase + language + '/' + folderImg + imgfile
        if os.path.isfile(translated_path):
            imgPath = translated_path

    return send_file(imgPath)
```

The `imgfile` variable can be controlled by the user, the variable value is not processed safely, the path is directly spliced, and then the file content is returned to the user.

If `imgfile` variable value is `../../../../../../../../../../etc/passwd`, `language` is none, `imgPath` is `../.. /doc/img/../../../../../../../../../../etc/passwd`. The final service will read the `/etc/passwd` file Content.


Linux:
request url path: /img/..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2fetc%2fpasswd

**Comment by HazardCreative** [comment]
Thanks!

I tell anyone that RH isn't production ready (not having auth on the sockets is problematic) and shouldn't be run where there are potentially untrusted actors. But I'd like to get there eventually. I appreciate you looking into this more deeply and we'll get a fix for this in place.

**Comment by haby0** [comment]
@HazardCreative I will submit a pr to fix this security vulnerability.

**Comment by HazardCreative** [comment]
Thank you!
