### ISSUE TITLE
Server JSON API requests gets really slow after about 40-50 heats in the database

### ISSUE THREAD

**Issue by fireduckfpv** [RotorHazard/RotorHazard#651]
I do not think this is a bug, but more of a performance issue.

When we start raceday the response from the server is immidiate and everything works great. But after running aprox 40 heats the server starts getting sluggish and sometimes stops completely. Espesiallly the JSON API responses is getting really slow. We are using a Raspberry Pi 3+ without desktop

Reproduce:
1. Start server a usual, delete races in database, and check "python" CPU useage. Usually it idles at around 5-15% depending on the load.
2. Check that the Marshall page opens normally. (Within one second)
3. Test JSON API requests and observe that the CPU jumps to around 20-40% for about one or two seconds pr request. (Depending on the type of request, the heaviest command I believe is http://rotorhazard/api/race/all)
4. Run aprox 40 heats with more than 3 pilots per heat doing 10 laps or so pr heat.
5. Run JSON API request again and observe that the CPU jumps to 100% for a couple of seconds. During this time it does not register passes and the webinterface freezes..
6.  Open Marshall page and it will take several seconds just to open the page.

I understand the CPU load rises with more data in the database, but could there be a more efficient way to handle the JSON API requests? It becomes almost unusable after 4-5 hours or racing. Is it possible to use more direct / specified JSON requests to reduce CPU load? It feels like such an overkill to run http://rotorhazard/api/race/all just to get one line of data :)

We will try with better hardware (Like raspberry Pi 4) and see if the response time gets better.

**Comment by HazardCreative** [comment]
What's the one line of data you need from /race/all ? The solution here may be to add an endpoint that better suits your needs and query less of the database at a time.

**Comment by HazardCreative** [comment]
RH4 now supports plugins and a dedicated API. The JSON endpoints aren't likely to get much additional functionality as RHAPI offers better access, performance, and data security. See https://github.com/RotorHazard/RotorHazard/blob/main/doc/Plugins.md .
