### ISSUE TITLE
Frequency Reference R1268 vs R1367?

### ISSUE THREAD

**Issue by andhya** [RotorHazard/RotorHazard#652]
Currently, the Frequency Reference suggests the 4pilot scheme of R1367. R1367 only shares two channels with the IMD5c and IMD6c schemes. I believe an alternative scheme of R1268 would be as performant as R1367, whilst also being more in-line with the IMD5/6c scheme - besides R6 (usefully the DJI public channel).

If this diagram is updated in future, it would be great if R1367 could be dropped in favour of R1268?

Alternatively if the intention is to maximise CE conformancy, then R346 would allow three conforming channels as opposed to R1268's two conforming channels?

![image](https://user-images.githubusercontent.com/60676719/159279617-e981d453-96dc-42ce-ae0c-328b620768f6.png)

**Comment by HazardCreative** [comment]
R1367 is backed up by real-world experience of race directors. I'll certainly consider other options if there's empirical evidence of them being tested, proven superior, and subsequently adopted by multiple race directors. I'm not familiar with what race directors requiring CE conformance are typically using, but I would be happy to update the chart with strategies proven through event experience of multiple directors.

**Comment by andhya** [comment]
That's fair - dyu have any insight as to what the reasoning behind R1367 was originally?

**Comment by HazardCreative** [comment]
It most likely came about as a variation from R1368, which has no IMD effects, is all Raceband to simplify channel management, and the best possible channel spacing. However, R8 frequently outputs at a lower power than other channels from a typical FPV VTx. Moving R8 to R7 maintains the other features as possible while avoiding this.

R1257 would theoretically maintain the same features, overlap IMD5/6 better, and avoid both R6 and R8—but I'm not aware of race groups adopting it and proving that out. Sometimes unseen factors (such as R8 power, maybe greater WiFi overlap) come into play, so I wouldn't want to publish something here on speculation only.

**Comment by andhya** [comment]
Thanks for the insight! Hadn't come across any R8 issues myself, good to be aware of.
