### ISSUE TITLE
Support for BME280 sensor

### ISSUE THREAD

**Issue by pulquero** [RotorHazard/RotorHazard#67]
If it is of interest, I have added support for temperature monitoring with the addition of a BME280 sensor to the I2C bus. Branch is here: https://github.com/pulquero/RotorHazard/tree/ExtRotorHazard

**Comment by HazardCreative** [comment]
Thank you for your contribution! I'm happy to have support for this, and love that you've gone as far as providing updated documentation. Feel free to create a pull request for this.

To wrap it up and get it in, I'd like to see:
- Less frequent polling of the sensor, to keep the I2C traffic down. Polling once in about 10 seconds should be enough?
- A more visible location to display the data. How about in the 'about' popup?
- Storing the current reading in a server variable. (Later on we could add an alert popup if it passes a certain threshold.)

**Comment by pulquero** [comment]
Shall I also roll it into the main RHInterface? Is using heartbeat msg still appropriate (using cache value to reduce polling) or should there be a new dedicated msg?

**Comment by HazardCreative** [comment]
I think bringing it into the main interface is fine. There can be an update routine similar to those that invoke the other i2c functions before a race begins or when a frequency/calibration setting is changed. We can invoke that from within the server.py's heartbeat. You'll see there that there is already a function that's being polled less often.

**Comment by HazardCreative** [comment]
Let's also make sure it's never polled if the sensor isn't installed or enabled by a config file option.
