### ISSUE TITLE
First to X Laps closes too soon on non Team racing

### ISSUE THREAD

**Issue by pamjesus** [RotorHazard/RotorHazard#675]
Hi all,

In my country, in Europe, we run qualifications based on a fixed number of laps (typically 3, depending on the circuit) and without a time limit.
Currently, the race format "First to X Laps" sets "late lap" for everyone after a winner is declared.
Not what is required here, as we must allow other pilots to finish the X laps.

The solution I tested was not to set "late_lap"  when not in Teams mode (code coming soon).

Alternatives considered:
-  Set race format to not define a winner. In this way, we lose the generate heaps with pilots sorted.
-  Set race format with a fixed time. Not really the model in use.

You have a broader view of win conditions. Hope to hear from you.

**Comment by HazardCreative** [comment]
I see what you're saying. Rather than eliminate late laps entirely, it would be better to trigger them when each pilot (or team) hits the limit. I'll look into that.
