### ISSUE TITLE
No symbol module in Python 3.10

### ISSUE THREAD

**Issue by szafranski** [RotorHazard/RotorHazard#678]
**Describe the bug**
Symbol module is missing in Python 3.10. Sooner or later 3.10 will be default version on the Pi.
I found it by accident on Ubuntu. Attaching screenshoots.

**To Reproduce**
Start RotorHazard on OS with Python 3.10 or later

**Screenshots**
Added

**Desktop (please complete the following information):**
Linux localhost 5.19.0-23-generic #24-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct 14 15:39:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
PRETTY_NAME="Ubuntu 22.10"
NAME="Ubuntu"
VERSION_ID="22.10"
VERSION="22.10 (Kinetic Kudu)"
VERSION_CODENAME=kinetic
ID=ubuntu
ID_LIKE=debian
<img width="832" alt="Screenshot 2022-11-02 at 00 50 32" src="https://user-images.githubusercontent.com/23621888/199363613-43a896ab-c34e-41a3-9a88-2a89bc5dc30f.png">
<img width="746" alt="Screenshot 2022-11-02 at 00 50 39" src="https://user-images.githubusercontent.com/23621888/199363617-79ed3215-018f-47ca-9e5f-e34d71351364.png">

**Comment by ethomas997** [comment]
The fix may be to update to a newer version of 'gevent'.  In the current "requirements.txt" file we have "20.6.\*".  Looks like the latest '[gevent](http://www.gevent.org)' version is 22.10.2, so we should probably change that entry to "20.10.\*".

Can you try updating 'gevent' and see if that fixes the issue?

**Comment by szafranski** [comment]
Sure. Issue still present:
<img width="724" alt="image" src="https://user-images.githubusercontent.com/23621888/200510786-7fcb704c-f301-4d9e-bc85-7071035e212a.png">
<img width="727" alt="image" src="https://user-images.githubusercontent.com/23621888/200510873-b3afedda-11ea-4e30-b72b-cdae9ec4bba7.png">

**Comment by szafranski** [comment]
Ok, so that maybe my mistake or some weird edge case etc. Here is what I found. 

Modules:
gevent==20.6.*
gevent-websocket==0.10.*
greenlet==0.4.16
seem to be not compatible with python3.10. 

As @ethomas997 suggested - I removed version indicators and install those this way so I got:
gevent             22.10.2
gevent-websocket   0.10.1
greenlet           2.0.1

Looks like now it works but I woud have to make some bare-metal tests to confirm.

**Comment by ethomas997** [comment]
I've updated the GEvent version with commit 38c28ae17fc008bd33efa0b3280d5f40b5bc780a, which should take care of this issue.  Let me know if you see any problems.

**Comment by szafranski** [comment]
Looks that now everything works fine, even with python3.11

**Comment by ethomas997** [comment]
Excellent, thanks!
