### ISSUE TITLE
Lap numbers not showed perfectly 

### ISSUE THREAD

**Issue by deeph46** [RotorHazard/RotorHazard#692]
Hi there,

I 'm using LED panel 16x16, but I have issue with lap numbers showing in panel.

This is what it looks like, https://drive.google.com/file/d/1OYN9ZmXZpzD-iln_h4X_G4tPLephzeJQ/view?usp=share_link.
RotorHazard boot logo looks ok.
![Logo](https://user-images.githubusercontent.com/7850916/209948181-c589594d-9283-46ae-aed7-e37db8e9db9d.jpeg)

Is there something what I missed with the commands?

Thanks

**Comment by HazardCreative** [comment]
Some panels are address the even-numbered rows in reverse (it's cheaper to manufacture). It looks like you have one of those. You can correct for it by setting `INVERTED_PANEL_ROWS` in `Config.json` to `true`.
https://github.com/RotorHazard/RotorHazard/blob/main/doc/Software%20Setup.md#ws2812b-led-support

**Comment by deeph46** [comment]
Thanks for quick feedback. That is a quick fix, numbers display great now.

Thanks again.
