### ISSUE TITLE
Race formats are not initialised correctly

### ISSUE THREAD

**Issue by andreyzher** [RotorHazard/RotorHazard#696]
**Describe the bug**

Timed race formats are not correctly initialising the race time and staging time min/max values.
I noticed this while exploring **v3.2.0-beta.4 on a clean install**. This can also be reproduced when resetting the database

**To Reproduce**
1. Go to 'Settings' page
2. Scroll down to 'Database'
3. Select 'Races and Race Formats' as the reset method
4. Click 'Clear Data'
5. Scroll up to 'Race Format'
6. Select any timed format (e.g. 2:00 Standard Race)
7. Timer Duration, Minimum Staging Time, and Random Staging Time are not set to the values defined in `RHData.reset_raceFormats()`

**Expected behavior**

Built-in race formats should initialise/reset with the correct timers, e.g. for 2:00 Standard Race, should have the following values (as defined [here](https://github.com/RotorHazard/RotorHazard/blob/main/src/server/RHData.py#L1465)):

* Timer Duration: 120
* Minimum Staging Time: 0.5
* Random Staging Time: 3.5

**Additional context**

Seems to be a result of inconsistent naming of keys in RHData.py. The UI passes the respective values as `race_time`, `start_delay_min`, and `start_delay_max`.

`RHData.alter_raceFormat(data)` correctly remaps these to `race_time_sec`, `start_delay_min_ms`, and `start_delay_max_ms` respectively.

`RHData.add_format(init)` also expects the same keys, but the dict received from `RHData.reset_raceFormats()` does not match the expected keys.

Also, since Lap Grace Period is now available, should the 3:00 Extended Race format be set to 180 seconds for the main timer, with the 30 seconds grace period as default, rather than 210 seconds as the race time?

---
Happy to submit a PR for the same, if it's not already resolved on a branch.

**Comment by HazardCreative** [comment]
Thanks for the thorough report. I did resolve this, but it was on the event-structure branch which has a lot of other changes. I don't want to wait for that branch to merge to fix it here—let's see if that commit will cherry-pick across.

Your comments on grace periods and defaults are well placed. We should consider not only that one, but where else it makes sense within the entire list.

**Comment by HazardCreative** [comment]
Closed by 2dfd420 .
