### ISSUE TITLE
OBS race overlay timer

### ISSUE THREAD

**Issue by Aaronsss** [RotorHazard/RotorHazard#697]
When the race view is used in OBS overlay it seems the clock just adds up the time since the overlay started.

Essentially I want to get race time on my OBS steam so perhaps a separate race clock overlay is more appropriate as I was just cropping the rest of the race overlay out

I am running 3.2.0 beta 1

**Comment by HazardCreative** [comment]
I wasn't able to see this behavior with the latest code. Try updating your version and see if a fix has already been made. If not, please provide steps to reproduce the issue and we'll look into it.

**Comment by Aaronsss** [comment]
I cant seem to get this to happen on the latest build anymore, also updated OBS too

closing
