### ISSUE TITLE
Unable to save race, had to clear race data to be able to resume the race

### ISSUE THREAD

**Issue by Aaronsss** [RotorHazard/RotorHazard#708]
There I was surrounded by livetime and laprf fan boys and boy did I not hear the end of this one. Made worse by having to spend time in excel to recover race data to properly seed the finals.

Essentially on 4 different occasions last night the timer removed the ability for me to save the race data. When changing heats, the unsaved data followed me and was unable to continue with the current race database.

Setup:
RH 3.2.0
Latest Chrome but also did it in Firefox
I was using the OBS websocks plugin I wrote but did delete it and it happened again after
OBS using some of the stream displays

How to replicate:

1. Run a race, allow the timer to elapse 
2. Initially the save and clear button will be present but after a little time it would occasionally be greyed out
3. Race data can then not be saved and the recorded laps don’t go away

How to recover:

1. A strong drink and separation from the livetime fan boys! :)
2. Essentially Races had to be cleared from the database settings tab
3. I also had an instance where a server reboot was needed to stop the race timer going silly
4. I did also have to test the race would run normally as it did behave a bit abnormally on one of them until a completed race was recorded
5. Restarting the timer or the browser did not help

[rh_logs_20230219_133459.zip](https://github.com/RotorHazard/RotorHazard/files/10777113/rh_logs_20230219_133459.zip)

**Comment by HazardCreative** [comment]
This sounds very much like a bug that was present in the `event-structure` branch. Are you confident this was a 3.2.0 load?

**Comment by Aaronsss** [comment]
Yep, definitely 3.2.0

**Comment by HazardCreative** [comment]
Found it. Fix incoming.
