### ISSUE TITLE
Heats on timer

### ISSUE THREAD

**Issue by AirBlender2000** [RotorHazard/RotorHazard#714]
I would like to run heats on a timer.

You start the race, It stops and saves heat, then RH waits for nn seconds before it starts next heat...

So you set up all heats with timer and "press play".

It should be possible to pause and resume the countdown if something unpredictable happens.

**Comment by HazardCreative** [comment]
Thanks for the request. This one has been submitted already, so I'll close it as a duplicate pf #449. But your interest is noted! The 4.0 beta puts a lot of structure into place that was needed before making this happen and we'll continue to build on that.
