### ISSUE TITLE
Custom rankings for finals on results page

### ISSUE THREAD

**Issue by Aaronsss** [RotorHazard/RotorHazard#716]
So I have been playing about with RH 4.0.0 (current master copy). Its great to see the heat generator come to life for finals :)

i think it would be useful to set a way for the finals class summary on the results page to be updated though. For example if someone in a lower final managed to go faster than someone in the heat above they would think they have jumped up above them when in reality they can only advance to the highest position their final would allow

**Comment by HazardCreative** [comment]
Closed by #747
