### ISSUE TITLE
Points based finals ranking

### ISSUE THREAD

**Issue by Aaronsss** [RotorHazard/RotorHazard#719]
In the UK we tend to run triple finals and give pilots points based on their finishing positions for each race

Typically we would award the following points for each race:
10 points for 1st
7 points for 2nd
5 points for 3rd
3 points for 4th
1 points for 5th
0 points for 6th

Then the pilots overall finishing position is determined by the sum of their points over the 3 final races they have flown

Currently we have to do this is a spreadsheet when running RH. Is it possible to get this supported in RH?

**Comment by HazardCreative** [comment]
Closed by #757. You'd have to run each final as a separate class, though—so it sounds like you're interested in a merging of the functionality from [Cumulative Points](https://github.com/RotorHazard/RotorHazard/tree/main/src/server/plugins/rh_class_rank_heat_pos) and [Rank by last heat position](https://github.com/RotorHazard/RotorHazard/tree/main/src/server/plugins/rh_class_rank_heat_pos). This isn't currently planned to add to core but could be developed now as a plugin.

It's possible that I may develop this myself, but it would be made available somewhere outside the RH core.

**Comment by HazardCreative** [comment]
See: https://github.com/HazardCreative/RotorHazard-Class-Rank-Heat-Points

**Comment by Aaronsss** [comment]
Excellent work thanks :)

Would it be possible for the class ranking to do it based on the heat then points?

For example final A pilots would fill positions 1-6, final b pilots would fill positions 7-12. Currently it ranks based on points only but if it could do it based on heat then points it would save the race director that would be awesome

**Comment by HazardCreative** [comment]
That is how the linked plugin works.
