### ISSUE TITLE
add - Average of the 3 best times to perform a lap - QUALIFICATION FAI FORMAT

### ISSUE THREAD

**Issue by starz91** [RotorHazard/RotorHazard#720]
**Can you add this ranking for fai qualification

The result of each competitor for the qualification stage will be the average of the 3 (three) best
times recorded to perform one valid circuit lap taking in account all the qualifying rounds. Those
best times may be done in the same qualifying round or in different ones.

see : page 29 b) - https://www.fai.org/sites/default/files/ciam/wcup_drones/sc4_vol_f9_dronesport_23_2023-02-01.pdf

**Comment by HazardCreative** [comment]
Bundling a specific qualifier format isn't planned at this time, but the plugin system now supports custom ranking. The existing ["Best X rounds" bundled plugin](https://github.com/RotorHazard/RotorHazard/tree/main/src/server/plugins/rh_class_rank_best_x_rounds) would be a good start.

It's possible that I may develop this myself, but it would be made available somewhere outside the RH core.

**Comment by HazardCreative** [comment]
I've built this method as a plugin.
https://github.com/HazardCreative/RotorHazard-Class-Rank-Best-X-Laps
