### ISSUE TITLE
Streaming bug

### ISSUE THREAD

**Issue by MoonKIE666** [RotorHazard/RotorHazard#725]
Hello, I have detected that in version 4.0.0 beta 2 there are different problems with the part of the overlay for streaming.
When I open different windows to see the overlay of all the nodes, I only see data in the first four, and the data that appears is hidden behind the position overlay. The four remaining nodes do not see any type of information.

**Comment by HazardCreative** [comment]
Thanks. I believe #722 will address the positional issue. Can you supply a db/log package to help review the other?

**Comment by HazardCreative** [comment]
Did e8c8502 resolve your second issue?

**Comment by MoonKIE666** [comment]
> Did [e8c8502](https://github.com/RotorHazard/RotorHazard/commit/e8c85029dfdae11aaa1fe9a38846f5ffe677ef33) resolve your second issue?

Yes, now the race information is output for the stream of the eight nodes that I have connected. But the information for the first 4 laps is still hidden behind the driver name and position graphic.

![image](https://user-images.githubusercontent.com/16765270/231244721-400b0145-4a82-4f5c-b957-8ad1a9cf53c2.png)

I am sending you a copy of the database with which I have done the test.

**Comment by HazardCreative** [comment]
#722, which has been merged in, should have solved that issue—but you might need to refresh your browser cache to see it. Try holding shift while you reload the page.

**Comment by MoonKIE666** [comment]
> #722, which has been merged in, should have solved that issue—but you might need to refresh your browser cache to see it. Try holding shift while you reload the page.

I have cleared all the data from the browsing history and cookies from CHROME and then I have tried what you have told me and the problem persists.

![image](https://user-images.githubusercontent.com/16765270/231248709-ee4fd76d-0ccb-45aa-8f3a-79f69b323ebd.png)

**Comment by arulrajesh** [comment]
working fine for me now...
![image](https://user-images.githubusercontent.com/4302998/231533409-3709a4fb-400e-40a4-92e5-0f985fbf90d6.png)

**Comment by MoonKIE666** [comment]
The problem persists for me even I have deleted the database.db file with vnc viewer and restarted the server. But it is still the same

![image](https://user-images.githubusercontent.com/16765270/232316069-8265d7d9-42af-49e9-8728-1abfb1f98132.png)

**Comment by arulrajesh** [comment]
@MoonKIE666   Did you do a git pull of the latest code from the repo?what version are you using? Send screenshot of the run page. It should be in the page footer.

**Comment by HazardCreative** [comment]
Please update to 4.0.0-dev.7 and re-test.

**Comment by HazardCreative** [comment]
Closing after no response; please update to the latest version and re-raise if the issue occurs again.
