### ISSUE TITLE
Starting Up with no modules ... unable to use server to test RH server

### ISSUE THREAD

**Issue by martinglass** [RotorHazard/RotorHazard#729]
**Describe the bug**
Connecting the Pi to an STM32 PCB (in this case 8-way), with no RX5808 modules attached and/or no BPill in situ, the RH Server won't start up, for example to test hardware or to run mode nodes.

Is it possible to get mock nodes instead of this error failure?

**Expected behavior**
If no PCB is connected the server starts up with mock nodes, and the logs would show  ...
_Unable to initialize nodes via RHInterface:  Unable to read frequency value from node 1
Using mock hardware interface_

The full log  would look like this
_RotorHazard v4.0.0-dev.3
Release: 4.0.0-dev.3 / Server API: 39 / Latest Node API: 35
Host machine: Raspberry Pi 3 Model B Rev 1.2
Host OS: Linux 6.1.21-v7+
Python version: 3.9.2
Host machine is 'rotorhazard' at 192.168.0.148
Loaded plugin module rh_led_handler_graph
Loaded plugin module rh_heatgenerator_standard
Loaded plugin module rh_data_export_json
Loaded plugin module rh_led_handler_character
Loaded plugin module rh_heatgenerator_ladder
Loaded plugin module rh_led_handler_bitmap
Loaded plugin module rh_data_export_csv
Loaded plugin module rh_led_handler_strip
Using configuration file 'config.json'
Using log file: logs/rh_20230423_130956.log
Loaded module i2c_helper
Loaded module i2c_node
Loaded module serial_node
Searching for I2C nodes...
Unable to initialize nodes via RHInterface:  Unable to read frequency value from node 1
Using mock hardware interface
Number of nodes found: 8
Loaded module bme280_sensor
Loaded module ina219_sensor
Loaded module linux_sensor
BME280 found at address 0x76 ('i2c:0x76')
BME280 found at address 0x77 ('i2c:0x77')
INA219 found at address 0x40 ('i2c:0x40')
INA219 found at address 0x41 ('i2c:0x41')
INA219 found at address 0x44 ('i2c:0x44')
INA219 found at address 0x45 ('i2c:0x45')
Core temperature available
No 'database.db' file found; creating initial database
Pilot added: Pilot 1
Pilot added: Pilot 2
Pilot added: Pilot 3
Pilot added: Pilot 4
Pilot added: Pilot 5
Pilot added: Pilot 6
Pilot added: Pilot 7
Pilot added: Pilot 8
Database pilots reset
Heat added: Heat 1
Database heats reset
Database saved races reset
Database set default profiles
Database reset race formats
Database race classes reset
Reset global settings
Frequency set: Node 1 B:R Ch:1 Freq:5658
Frequency set: Node 2 B:R Ch:2 Freq:5695
Frequency set: Node 3 B:F Ch:2 Freq:5760
Frequency set: Node 4 B:F Ch:4 Freq:5800
Frequency set: Node 5 B:R Ch:7 Freq:5880
Frequency set: Node 6 B:R Ch:8 Freq:5917
Frequency set: Node 7 B:None Ch:None Freq:0
Frequency set: Node 8 B:None Ch:None Freq:0
Database initialized
Set Profile to '1'
Node enter-at set: Node 1 Level 90
Node enter-at set: Node 2 Level 90
Node enter-at set: Node 3 Level 90
Node enter-at set: Node 4 Level 90
Node enter-at set: Node 5 Level 90
Node enter-at set: Node 6 Level 90
Node enter-at set: Node 7 Level 90
Node enter-at set: Node 8 Level 90
Node exit-at set: Node 1 Level 80
Node exit-at set: Node 2 Level 80
Node exit-at set: Node 3 Level 80
Node exit-at set: Node 4 Level 80
Node exit-at set: Node 5 Level 80
Node exit-at set: Node 6 Level 80
Node exit-at set: Node 7 Level 80
Node exit-at set: Node 8 Level 80
Updated calibration with best discovered values
Unable to find java; for IMDTabler functionality try:
sudo apt install default-jdk-headless
VRx Control disabled: no registered controllers
Running http server at port 5000_

**Instead the Log Dump looks like this**
_RotorHazard v4.0.0-dev.3
Release: 4.0.0-dev.3 / Server API: 39 / Latest Node API: 35
Host machine: Raspberry Pi 3 Model B Rev 1.2
Host OS: Linux 6.1.21-v7+
Python version: 3.9.2
Host machine is 'rotorhazard' at 192.168.0.213
Loaded plugin module rh_led_handler_graph
Loaded plugin module rh_heatgenerator_standard
Loaded plugin module rh_data_export_json
Loaded plugin module rh_led_handler_character
Loaded plugin module rh_heatgenerator_ladder
Loaded plugin module rh_led_handler_bitmap
Loaded plugin module rh_data_export_csv
Loaded plugin module rh_led_handler_strip
Using configuration file 'config.json'
Loaded module i2c_helper
Loaded module i2c_node
Loaded module serial_node
Serial node (with zero modules) found at port '/dev/serial0', API_level=35, baudrate=921600, fw_version=1.1.4, fw_type=STM32F1, fw_timestamp: Mmm dd yyyy hh:mm:ss
        (alt - without BPill in situ: Unable to fetch revision code for serial node at "/dev/serial0")
Unable to initialize nodes via RHInterface:  Unable to read frequency value from node 1
Unable to initialize specified serial node(s): ['/dev/serial0']
Exception ignored in: <function _removeHandlerRef at 0x7664e610>
Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/__init__.py", line 827, in _removeHandlerRef
  File "/usr/lib/python3.9/logging/__init__.py", line 221, in _acquireLock
  File "/usr/lib/python3.9/threading.py", line 156, in acquire
  File "/home/pi/.local/lib/python3.9/site-packages/gevent/thread.py", line 74, in get_ident
TypeError: 'NoneType' object is not callable_

**Comment by amdgigabyte** [comment]
How did you solve this problem？I met this same log error
