### ISSUE TITLE
Marshalling does not affect the "Event totals" results.

### ISSUE THREAD

**Issue by fireduckfpv** [RotorHazard/RotorHazard#731]
When masrhalling in Beta 4.0.0 Beta 2, it does not affect the data in "Event Totals" only in Class results

1. Create data
2. Edit data in Marshall
3. Look in Results
4. Class results are correct but Event Totals have not been affected

To fix it, one can export and import the database. Then the Event Totals will be correct, until you marshall again.

**Comment by HazardCreative** [comment]
Thanks for reporting. There are a few other actions in Beta 2 that don't update Results properly either. Work is underway.

**Comment by HazardCreative** [comment]
Closes with #730.
