### ISSUE TITLE
When running a race, only the 3 first racers are shown in the "current" list and race list

### ISSUE THREAD

**Issue by fireduckfpv** [RotorHazard/RotorHazard#733]
In a race with 4 or more racers, only the first 3 racers are shown in the "Current" list and in the race list.  It is not the 3 best racers, it is only the racers on the 3 first sensors. So even if the 4 racer is the best, his times will not be displayed.

Rotorhazard 4.0.0 beta 2

**Comment by fireduckfpv** [comment]
Here it is:
[database_20230501_171609.zip](https://github.com/RotorHazard/RotorHazard/files/11366644/database_20230501_171609.zip)

**Comment by fireduckfpv** [comment]
![image](https://user-images.githubusercontent.com/24962379/235489457-ea0978c1-784f-4911-9331-dfb9184c8eda.png)

**Comment by fireduckfpv** [comment]
Here is a screenshot
![image](https://user-images.githubusercontent.com/24962379/235489622-41ad1516-78bf-439a-a025-0806160a83c7.png)

**Comment by fireduckfpv** [comment]
Hum, yeah, when I rebooted the server, it fixed itself.. Now all 7 are shown..

**Comment by HazardCreative** [comment]
Thanks for the follow-up. Please re-open if you can reproduce.
