### ISSUE TITLE
Race format changes to -Unrestricted- when changing class name or adding a new heat

### ISSUE THREAD

**Issue by fireduckfpv** [RotorHazard/RotorHazard#734]
Race format changes back to -Unrestricted- when changing class name or adding a new heat

Rotorhazard 4.0.0 beta 2

**Comment by fireduckfpv** [comment]
https://user-images.githubusercontent.com/24962379/235728127-dd061c8a-d709-443d-8709-540d5bf3e23c.mp4

**Comment by HazardCreative** [comment]
Thanks for the steps.
