### ISSUE TITLE
Won't change channels

### ISSUE THREAD

**Issue by Austunb** [RotorHazard/RotorHazard#744]
I can disable the channels. Seems to only sense the rssi if the drone is on raceband 1. I followed Joshua's video https://www.youtube.com/watch?v=u06_V2tFYDA

I don't think it is because of the SPI mod. These is the exact ones I have. https://www.ebay.com/itm/384417966924

Let me know if it is because of the SPI mod. I am on the latest firmware. v3.2.1

**Comment by HazardCreative** [comment]
Assuming resolved after no update.
