### ISSUE TITLE
Results page keep 'Loading...' after several heats

### ISSUE THREAD

**Issue by Alienazaz** [RotorHazard/RotorHazard#746]
**Describe the bug**
When add a lot of heats to the system and run them, after a certain heat, the result page stops updating and remains in a "loading..." state. I checked the system log and found the following error: "new_pilot_result['average_lap_raw'] = new_pilot_result['total_time_laps_raw'] / new_pilot_result['laps']
ZeroDivisionError: division by zero.".

**To Reproduce**
1. Go to 'Run'
2. Run sevral heats
3. Click 'Results' page 
4. See Loading....
![image](https://github.com/RotorHazard/RotorHazard/assets/21164563/dcf9cfd2-5755-4e8c-9b09-4a48d6ec6181)

**Expected behavior**
.

**Screenshots**
![image](https://github.com/RotorHazard/RotorHazard/assets/21164563/a7907d09-1007-4275-bd0b-1aaa92525822)

**Log Dump**
[rh_logs_20230521_220803.zip](https://github.com/RotorHazard/RotorHazard/files/11524733/rh_logs_20230521_220803.zip)
[Error databases.zip](https://github.com/RotorHazard/RotorHazard/files/11524747/Error.databases.zip)

**Desktop (please complete the following information):**
 - OS: Windows10 
 - Browser chrome
 - Version 113.0.5672.127

**Comment by HazardCreative** [comment]
Thank you for the detailed report.
