### ISSUE TITLE
Python >= 3.6 needed for v4.0.0-beta.3

### ISSUE THREAD

**Issue by ErikBorra** [RotorHazard/RotorHazard#756]
**Describe the bug**
Beta.1 works fine. Trying to update to `RotorHazard v4.0.0-beta.3` I get an invalid syntax error when running `python server.py`. Apparently my Python version (3.5.3) is too old for type hinting. I thought you might want to know, as I did `apt upgrade` etc, as described in the documentation. I should probably dist-upgrade as well :)

**To Reproduce**
```
pi@RotorHazard:~/RotorHazard/src/server $ python server.py 
RotorHazard v4.0.0-beta.3
Traceback (most recent call last):
  File "server.py", line 66, in <module>
    import RHUI
  File "/home/pi/RotorHazard/src/server/RHUI.py", line 981
    name: str
        ^
SyntaxError: invalid syntax
```

**OS and python info**
```
pi@RotorHazard:~/RotorHazard/src/server $ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.13 (stretch)
Release:	9.13
Codename:	stretch
```
```
pi@RotorHazard:~/RotorHazard/src/server $ python --version
Python 3.5.3
```

**Comment by ethomas997** [comment]
Thanks for noting this.  I think we'll probably want to make Python v3.7 the minimum for this release.  Would you see upgrading to v3.7 as problematic for your use case?

**Comment by ErikBorra** [comment]
I would not find this problematic at all. 

Note that I am still working with delta 5 hardware. The hardware is ancient, but still works like a charm with RotorHazard 4.0 :D

**Comment by ethomas997** [comment]
Updated docs to say Python 3.7
