### ISSUE TITLE
Run page call outs available to event actions 

### ISSUE THREAD

**Issue by Aaronsss** [RotorHazard/RotorHazard#761]
It would be great if the call outs from the run page were available for the event actions

%HEAT% : Current heat name
%PILOTS% : Current pilot names
%LINEUP% : Current pilot names (faster)
%FREQS% : Frequencies with current pilot assignments 

I would quite like to have it do %PILOTS% on heat change so that the pilots know who needs to be flying now

**Comment by HazardCreative** [comment]
See https://github.com/RotorHazard/RotorHazard/blob/main/src/server/plugins/rh_actions_builtin/__init__.py#L10-L48
