### ISSUE TITLE
Frozen race page 

### ISSUE THREAD

**Issue by gvotteler** [RotorHazard/RotorHazard#766]
**Describe the bug**
After start a race if you stop the race and go to configuration and change some parameter of the race, and comeback to race page, the UI showed like "blocked" or frezze, you cant change the type of race and the buttons are grey..  the same happen if you go to create new pilot, and try to update the race page or the same pilot page the options that show in the list of the heats each pilot can be selected.

**To Reproduce**
1. Go to race
2. Click on start race (first of the day)
3. Stop race
4. Go to setup
5. change some race parameter
6. Go to race page
7. The select box is loading all time and the buttons of the race are grey

**Expected behavior**
After change the parameters of the race I can restart the race, I stop the race, clean the database of the race and still happen the error.

**Desktop (please complete the following information):**
 - OS windows 11.
 - Browser chrome lasted version.

**Comment by HazardCreative** [comment]
I'm not able to reproduce this issue with the latest code. Race format parameters cannot be changed for an active race; this in intentional. save or discard the race to return the the ready state and modify parameters as normal.

**Comment by HazardCreative** [comment]
Closing after no response; please update to the latest version and re-raise if the issue occurs again.
