### ISSUE TITLE
RotorHazard 3.2.1  does not work with LiveTime 

### ISSUE THREAD

**Issue by RogerBFPV** [RotorHazard/RotorHazard#768]
The goal is to use RotorHazard as the decoder in conjunction with LiveTime in the mechanism similar to how Delta5 worked.

In very old versions of RotorHazard (prior to 3.1.0),  one would just choose the 'Delta5' decoder in LiveTime, and it worked properly.

In RotorHazard 3.1.0 using the Delta5 setting in LiveTime would not function properly.  The symptom was: 
1. Livetime would start a race, RH would start..  (all is good)
2. Livetime finish the race from LT point of view.. (no real action or change in RH,, this is 'ok' as LT doesn't really care.. 
3. Livetime would start its next race, and RH would 'stop' the race it was on and not start, Thus, LT would not receive any lap passes..    
 So in essence, it would work every 2nd try..
 
 In response to this 3.1.0 RH,  Livetime modified their implementation and created a RH specific type.. Using this type, Everything worked properly..
1. Livetime would start a race, RH would start..  (all is good)
2. Livetime finish the race from LT point of view.. (no real action or change in RH,, this is 'ok' as LT doesn't really care.. 
3. Livetime would start its next race, and RH would 'stop' the race it was on and not start a new race, and all is good..

With RotorHazard 3.2.1, using the RotorHazard setting in LT does not work properly.   
1. Livetime would start a race, and it appears RH will start..  HOWEVER, lap  crossings don't seem to be getting sent to LT.. 

Some users have reported using 'Delta5' as the decoder setting in LiveTime does work a little better..  

So what changed between 3.1.0 and 3.2.1 to modify the RH behavior.. We need for RH dev's to investigate this.. There are free versions of Livetime (for up to 10 pilots) available.  the current version of livetime is https://assets.livetimescoring.com/downloads/LiveTime_ScoringEngine_4.0.0.130_x64.exe    (if 130 is not available increment the number)

**Comment by HazardCreative** [comment]
Following the provided steps did not produce the error state listed. Is there additional information or steps to reproduce?

**Comment by RogerBFPV** [comment]
I also have an issue opened with LiveTime to also investigate to see if there is something on their end as well.

**Comment by RogerBFPV** [comment]
History: 
 In  RH 3.1.0 using delta5 decoder in livetime, when  would invoke the reset_auto_calibration, and get_timestamp,  it would get odd results depending on that state the race was in.  This would cause the 'time left and time elapsed' to sometimes be offset by many minutes immediately at the start of a race..
 
 
 In response to this livetime created a 'rotorazard' decoder type, and this used the reset_auto_calibration and get_pi_time api calls, which in theory should be more consistent.. However, that time has a bunch of various offset calculations, which confused Livetime into thinking that the actual time is about 50 years in the future.. 
 
 In RotorHazard 3.2.1,  
  While the code within get_timestamp is not different, we do notice a significant difference in behavior, most likely from the reset_auto_calibration call..  
  So the end user symptom is:  
 a. At livetime we press start race, and from LiveTime point of view, the race has started..
 b. the 'time elapsed' as seen in livetime starts at  -3 (negative 3).    In Rotorhazard, it is getting 'ready'. 
c. at the time when rototorhazard starts it's race, livetime time elapsed is at 0 and counting.. 

The problem arises if a drone at the beginning of the race crosses that start line in less than 3 seconds after the livetime start tone sounds, that pass will be missed, and the thus that drone won't be seen as 'started'..

What livetime requires is:
1.  At all times, if a drone crosses the line,  that crossing be reported to livetime..   It doesn't matter if a race is running or not, all passes should be emitted to LiveTime..  
2. The get_timestamp should return a time that is consistent and relative to the timestamp that will be used for lap crossings.  


I suspect that LiveTime may do away with the 'rotorhazard' decoder type, as that was to solve a RH 3.1.0 issue that does not appear in RH 3.2.1.. 

However using  'delta5' does have the issue with the first 3 seconds of a race.

**Comment by vikibaarathi** [comment]
I've done some test on various scenarios and uploaded the results in the following share drive
https://drive.google.com/drive/folders/1c82-XSe_ent4G3WHGJkh1rkQ7ZsL98OA?usp=sharing

The following is the summary. In practice mode, LT is able to detect laps. I'll reload 3.1.0 later today and test again. 

![Screenshot 2023-07-11 at 7 25 08 AM](https://github.com/RotorHazard/RotorHazard/assets/17153870/fe5cbd88-43da-4bf1-8519-8aace58e8831)

**Comment by RogerBFPV** [comment]
your above table is incorrect:  you have PASS for rows 3 and 5 for 'LAPS'.  There is the issue of the 3 second delay in the RH start vs the LT start.  where a lap will be missed at the start of the LT race if the drone passes before 3 seconds has elapsed since the tone.

**Comment by vikibaarathi** [comment]
Agree and updated the results table. I noticed that as well. Pilot would have to take their time on start or race director would have to use an alternative signal or tone. 
![Screenshot 2023-07-11 at 7 42 02 AM](https://github.com/RotorHazard/RotorHazard/assets/17153870/c29fd9fe-8fa7-4f42-8aea-b633e95cc2b1)

**Comment by RogerBFPV** [comment]
I'm confused why you can't recreate the livetime starting at -3,  especially since you then indicate that by design RotorHazard will delay..   

Using Livetime version 4.0.0.130 linked above.  and using RotorHazard 3.2.1:

Configuration settings from the Racing view:
Click on the Settings pullout tab on the right:

Round: Set a race for a timed race in Livetime, say 2:00 minutes..

Timing: set lap settings to Ignore Invalid Lap mode
Heads up settings : Invalid Breakout
Check use heads up first lap

audio:
0 countdown ticks
0 delay between ticks
uncheck random start delay
   (this settings are common at MultiGP events, for the race to start as soon as the director presses the start race)



Next: click the 'start race' button.  
 In LT top you will see Time Elapsed, and Time Left..    If you watch closely, the Time Elapsed will start at  -3..

If you happen to be watching the RH browser, you will see RH in the 'ready' state during the -3, -2, -1 on LT.
Then RH will begin its race..

**Comment by vikibaarathi** [comment]
Thanks @HazardCreative , I'll give the branch a go.

**Comment by vikibaarathi** [comment]
![Screenshot 2023-07-12 at 8 38 34 PM](https://github.com/RotorHazard/RotorHazard/assets/17153870/5b78cff6-395b-488a-8ab5-15e6e43d4a9e)

Tested with the above results. Only 1 configuration works for actual race which is highlighted in item 7. There is no 3 second delay. Race starts immediately in RH. 
Test result video in link below
https://drive.google.com/drive/folders/1c82-XSe_ent4G3WHGJkh1rkQ7ZsL98OA?usp=sharing

Again in summary, for best experience of using RH and LT for a race, the configuration should be **Delta5** and not RotorHazard for the decoder selection.

**Comment by HazardCreative** [comment]
@RogerBFPV with the settings as you describe, the "Time Elapsed" in LT still counts upwards from zero. I do see RotorHazard's behavior as you describe, which has been adjusted in 3.2.2-dev.1 for testing.

@vikibaarathi We cannot support the RotorHazard decoder, for the reasons listed above. RotorHazard continues to provide Delta5 emulation; no dedicated RotorHazard / LiveTime protocol exists.

**Comment by RogerBFPV** [comment]
I also agree there is no need for a RotorHazard decoder option in LT.   As seen in this thread RotorHazard is addressing the issues to have its Delta5 emulation work more closely to how original Delta5 worked from a LT point of view.

**Comment by HazardCreative** [comment]
Closed with release of 3.2.2
