### ISSUE TITLE
Incorrect default values for race formats First to 3 laps & Open Practice

### ISSUE THREAD

**Issue by vikibaarathi** [RotorHazard/RotorHazard#769]
**Describe the bug**
In Beta 4, when race format **"First to 3 laps"** or **"Open Practice"** is selected, if race is started, the race immediately goes into negative value as soon as the race starts. Similar behaviour as though a race has ended. 

After inspecting the race format in the Formats page, the Race Clock Mode default value seem to be incorrect for the above mentioned 2 race formats.  

**To Reproduce**
1. Install clean new beta 4 
2. Immedietly go to Format, Race format and observe that **"Race CLock Mode"** for First to 3 laps and Open Practice are wrong. Default value selected is fixed time with time duration = 0.

**Expected behavior**
Expected behaviour is, when "First to 3 laps" or "Open Practice is selected, the default value for **"Race Clock Mode"** should be "No Time Limit" and time duration should be hidden.

**Screenshots**

<img width="762" alt="Screenshot 2023-07-17 at 10 03 18 PM" src="https://github.com/RotorHazard/RotorHazard/assets/17153870/430fa3c4-b325-4d06-be82-0374c0503b4b">
<img width="817" alt="Screenshot 2023-07-17 at 10 03 26 PM" src="https://github.com/RotorHazard/RotorHazard/assets/17153870/89d2b15d-a7fd-45bb-bea3-043fc4df39f6">

**Comment by HazardCreative** [comment]
Pretty sure this is related to an issue in an earlier beta that was patched. Feel free to reopen if you have new information.
