### ISSUE TITLE
Cache GlobalSettings

### ISSUE THREAD

**Issue by pulquero** [RotorHazard/RotorHazard#77]
There seems to be a few getOption calls in key places like the pass_through callback. I would imagine you would want to minimize database I/O in callbacks, so maybe GlobalSettings could be read once completely and stored in a dict object, this could then be updated in setOption, with write-through to the db. Maybe the DB/alchemy has in-built caching and this isn't so much of an issue.

**Comment by HazardCreative** [comment]
I was under the impression that it was doing internal caching, but some quick searches suggest that it isn't. This sounds like a good change to make and not too difficult.
