### ISSUE TITLE
Hi 

### ISSUE THREAD

**Issue by pixcelponey** [RotorHazard/RotorHazard#773]

**Comment by pixcelponey** [comment]
Hi 
I would like to know if people have the same problem as me when configuring the stm32 node. 
I can send the blink basic example program to the stm32 to get the led blinking.... ( to make sure I can actually configure that blue pill...)
But I am not able to load the node 3.2.2 program to the sstm32 I keep getting the same error bellow when I try to compile it. 

Any help would be greatly appreciated :)




Arduino: 1.8.5 (Windows 10), Board: "Generic STM32F103C series, STM32F103C8 (20k RAM. 64k Flash), Serial, 72Mhz (Normal), Smallest (default)"

In file included from sketch\RssiNode.cpp:1:0:

sketch\RssiNode.cpp: In member function 'void RssiNode::initRx5808Pins(int)':

config.h:78: error: 'A0' was not declared in this scope

 #define RSSI_INPUT_PIN A0              //RSSI input from RX5808

                        ^

sketch\RssiNode.cpp:28:20: note: in expansion of macro 'RSSI_INPUT_PIN'

     rssiInputPin = RSSI_INPUT_PIN;    //RSSI input from RX5808

                    ^

Multiple libraries were found for "Wire.h"
 Used: C:\Users\angel\Documents\Arduino\hardware\Arduino_STM32\STM32F1\libraries\Wire
 Not used: C:\Users\angel\Documents\Arduino\hardware\Arduino_STM32\STM32F1\libraries\WireSlave
exit status 1
'A0' was not declared in this scope

**Comment by ethomas997** [comment]
Have you followed the steps from here?:

https://github.com/RotorHazard/RotorHazard/blob/main/src/node/readme_S32_BPill.md

**Comment by HazardCreative** [comment]
Closing after no response.
