### ISSUE TITLE
The install instructions are not quite correct on the releases page

### ISSUE THREAD

**Issue by Aaronsss** [RotorHazard/RotorHazard#779]
I recently updated to RH 4.0.0 beta 4 to have a play with it. 

The install instructions are not quite correct on the releases page

sudo pip install --upgrade --no-cache-dir -r requirements.txt

should read

pip install --upgrade --no-cache-dir -r requirements.txt

It needs to be run by the user running the server which is not usually root

**Comment by HazardCreative** [comment]
This is a good change, but sometimes the server must be run as root—for example certain LED configurations require root for hardware access. We need to also add a note that sudo might be needed in those cases.

**Comment by ethomas997** [comment]
I always do the command with 'sudo' and have not seen any issues.  What is the reason for not including it?  It seems like if Python is a system-wide resource it would be necessary to do it via 'sudo'.

**Comment by HazardCreative** [comment]
Closing, addressed in release notes (currently drafted)
