### ISSUE TITLE
References to race_time_finished in comments

### ISSUE THREAD

**Issue by pulquero** [RotorHazard/RotorHazard#78]
race_time_finished has been removed but is still mentioned in comments.

**Comment by HazardCreative** [comment]
I took a look and while some o the comments can just be removed, others refer to conditionals if the output comes from one function or another. Are there other ways to activate these conditionals or can those be simplified as well?

**Comment by ethomas997** [comment]
Fixed by https://github.com/RotorHazard/RotorHazard/commit/17e80bf77dade22df903ed1d9a9435a544b06242

(If we're still looking to simplify / improve logic then we can open a new issue for that.)
