### ISSUE TITLE
Heat generator doesnt seem to work on second run

### ISSUE THREAD

**Issue by Aaronsss** [RotorHazard/RotorHazard#780]
I used the heat generator to seed pilots into a qualifier but then tried to generate a second class for finals and it seems to crash the generator

![image](https://github.com/RotorHazard/RotorHazard/assets/23297034/304e1ac1-c061-4d1d-b1fe-7534e5e7b0c2)

log info:

RotorHazard v4.0.0-beta.4
Release: 4.0.0-beta.4 / Server API: 41 / Latest Node API: 35
Host machine: Raspberry Pi 3 Model B Rev 1.2
Host OS: Linux 6.1.21-v7+
Python version: 3.9.2
Host machine is 'LapTimer' at 192.168.68.15
Loaded plugin module rh_data_export_csv
Loaded plugin module rh_class_rank_heat_pos
Loaded plugin module rh_led_handler_strip
Loaded plugin module rh_points_by_position
Loaded plugin module rh_data_import_json
Loaded plugin module rh_led_handler_character
Loaded plugin module class_rank_best_pct_rounds
Loaded plugin module rh_led_handler_bitmap
Loaded plugin module rh_heatgenerator_standard
Loaded plugin module rh_led_handler_graph
Loaded plugin module rh_class_rank_best_x_rounds
Loaded plugin module class_rank_heat_points
Loaded plugin module rh_data_export_json
Loaded plugin module rh_actions_builtin
Loaded plugin module rh_heatgenerator_ladder
Loaded plugin module class_rank_best_x_laps
Loaded plugin module rh_class_rank_cumulative_points
Using configuration file 'config.json'
Using log file: logs/rh_20230831_234237.log
Loaded module i2c_helper
Loaded module i2c_node
Loaded module serial_node
Serial multi-node found at port '/dev/serial0', count=6, API_level=35, baudrate=921600, fw_version=1.1.4, fw_type=STM32F1, fw_timestamp: Apr 27 2021 21:17:24
Receiver modules found at slot positions: 1 2 3 4 5 6
Number of nodes found: 6
Loaded module bme280_sensor
Loaded module ina219_sensor
Loaded module linux_sensor
INA219 found at address 0x40 ('Battery')
Core temperature available
Set Profile to '1'
Updated calibration with best discovered values
VRx Control disabled: no registered controllers
Running http server at port 5000
Interface: Starting background thread
T4715: Built results data in: 0.315399s
Class 4 deleted
Generating heats via Balanced random fill
Exception via catchLogExceptionsWrapper
Traceback (most recent call last):
  File "/home/aaron/RotorHazard/src/server/RHUtils.py", line 182, in wrapper
    return func(*args, **kwargs)
  File "/home/aaron/RotorHazard/src/server/server.py", line 1670, in on_generate_heats_v2
    generate_result = RaceContext.heat_generate_manager.generate(generator, generate_args)
  File "/home/aaron/RotorHazard/src/server/HeatGenerator.py", line 60, in generate
    generated_heats = self._generators[generator_id].generate(self._rhapi, generate_args)
  File "/home/aaron/RotorHazard/src/server/HeatGenerator.py", line 161, in generate
    return self._generator(rhapi, generate_args)
  File "/home/aaron/RotorHazard/src/server/plugins/rh_heatgenerator_ladder/__init__.py", line 118, in generateBalancedHeats
    total_pilots = getTotalPilots(rhapi, generate_args)
  File "/home/aaron/RotorHazard/src/server/plugins/rh_heatgenerator_ladder/__init__.py", line 17, in getTotalPilots
    total_pilots = int(generate_args['total_pilots'])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Database heats reset
Database saved races reset
Switching to practice mode; races will not be saved until a heat is selected
T4791: Built results data in: 0.044320s
Database heats reset
Database race classes reset
Database saved races reset
Switching to practice mode; races will not be saved until a heat is selected
T4810: Built results data in: 0.027861s
Class added: Class <RaceClass 1>
Heat added: Heat 1
Heat 1 deleted
Class 1 deleted
Generating heats via Balanced random fill
Class added: Class <RaceClass 1>
Heat added: Heat 1
Heat added: Heat 2
Altered race class 1 to {'class_id': 1, 'class_name': 'Qualifier'}
Generating heats via Balanced random fill
Exception via catchLogExceptionsWrapper
Traceback (most recent call last):
  File "/home/aaron/RotorHazard/src/server/RHUtils.py", line 182, in wrapper
    return func(*args, **kwargs)
  File "/home/aaron/RotorHazard/src/server/server.py", line 1670, in on_generate_heats_v2
    generate_result = RaceContext.heat_generate_manager.generate(generator, generate_args)
  File "/home/aaron/RotorHazard/src/server/HeatGenerator.py", line 60, in generate
    generated_heats = self._generators[generator_id].generate(self._rhapi, generate_args)
  File "/home/aaron/RotorHazard/src/server/HeatGenerator.py", line 161, in generate
    return self._generator(rhapi, generate_args)
  File "/home/aaron/RotorHazard/src/server/plugins/rh_heatgenerator_ladder/__init__.py", line 118, in generateBalancedHeats
    total_pilots = getTotalPilots(rhapi, generate_args)
  File "/home/aaron/RotorHazard/src/server/plugins/rh_heatgenerator_ladder/__init__.py", line 17, in getTotalPilots
    total_pilots = int(generate_args['total_pilots'])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by HazardCreative** [comment]
This looks like something that was fixed after the beta release. Please update to the latest dev code and see if it persists.

**Comment by HazardCreative** [comment]
Closing after no response; please re-raise if the issue occurs after an update.
