### ISSUE TITLE
Add ids arguments to additonal event triggers

### ISSUE THREAD

**Issue by i-am-grub** [RotorHazard/RotorHazard#786]
I am looking to have some more data passed through event triggers arguments to easily use the RHAPI.  Some examples are that already great to work with are LAPS_SAVE and LAPS_RESAVE (race_id of saved race is included in the trigger's args). The following events are requested with priority (VRxC integrations), but feel free to expand this list as seen fit.

RACE_SCHEDULE : add race_id
RACE_SCHEDULE_CANCEL : add race_id
RACE_STAGE : add race_id
RACE_START : add race_id
RACE_FINISH : add race_id
RACE_STOP : add race_id

RACE_LAP_RECORDED = add pilot_id of pilot that triggered
RACE_PILOT_DONE : add pilot_id of pilot that triggered

**Comment by HazardCreative** [comment]
The active race doesn't have an ID. It only exists after being saved to the database.

**Comment by i-am-grub** [comment]
Going through the code right now and just saw that. I think the heat_id should be fine instead of the race_id if that works.
