### ISSUE TITLE
Merge similar set_XXXX socket protocol methods

### ISSUE THREAD

**Issue by pulquero** [RotorHazard/RotorHazard#79]
Currently there are a bunch of individual set_XXX methods for changing individual settings. We could save a lot of code by having a few top-level set_XXX methods that set whatever is sent in the json object, e.g.

@SOCKET_IO.on("set_race_format_settings")
def on_set_race_format_setting(data):
    race_format = getCurrentRaceFormat()
    if 'start_delay_min' in data:
        race_format.start_delay_min = data['start_delay_min']
    if 'start_delay_max' in data:
        race_format.start_delay_max = data['start_delay_max']
    DB.session.commit()
    server_log("set race format settings to %s" % data)

**Comment by HazardCreative** [comment]
Agreed. Sounds like a good change and easier to maintain going forward.

**Comment by HazardCreative** [comment]
Pulled in #84.
