### ISSUE TITLE
Problem with LED panel 

### ISSUE THREAD

**Issue by MoonKIE666** [RotorHazard/RotorHazard#798]
![imagen](https://github.com/RotorHazard/RotorHazard/assets/16765270/7b225a0f-9b28-4be0-a975-2ef83bbf429b)

I have detected a problem with the LED control.

I have a 16x16 LED panel that has a total of 256 LEDs. I have changed the value in the config.json file to tell the server the number of leds I have.

I have updated the library for LED control on the raspberry pi and I also have the server requirements updated.

But there is a problem with some of the LED control panel options. There are a series of images that do not show on the panel when I select them, and only one LED lights up.

The images that do not appear on the LED panel when I activate them are the ones that I have highlighted in red in the image at the beginning of the post.

Sorry for my English

**Comment by HazardCreative** [comment]
You have set `LED_ROWS` to 1, indicating to RH that your LED panel is 1×256px. I assume your panel has 16 rows; you need to set this config item accordingly.

**Comment by MoonKIE666** [comment]
Yes, my panel have 16 rows. Then I will chage It an prove

**Comment by MoonKIE666** [comment]
Yes was my fault. I've change that you say and leds turn to work fine

**Comment by HazardCreative** [comment]
Thanks for confirming.
