### ISSUE TITLE
Pilots and heats cannot be removed

### ISSUE THREAD

**Issue by HazardCreative** [RotorHazard/RotorHazard#8]
Especially with pilot carryover after an API update and planned update to event page to only display pilots currently assigned to heats, use of these data stores could increase and require this kind of management.

**Comment by RogerBFPV** [comment]
In Pilot sorting, heat generator, pilot attributes, display heat/round of fastest lap PR #259, we do have the ability to delete the last heat as long as it does not have race data. 

There are also pilot enhancements there that only put pilots in pulldown lists that are 'registered', and it is easy to 'unregister' all pilots by using the function to remove attribute for Registered, which an admin can do.
