### ISSUE TITLE
Shortcut (Key Press) for Schedule Race

### ISSUE THREAD

**Issue by JesseFPV** [RotorHazard/RotorHazard#800]
**Is your feature request related to a problem? Please describe.**
No problem, just inconvenience. There are shortcuts for start/stop/save/discard but not for schedule although we always use schedule instead of start.

**Describe the solution you'd like**
Add a shortcode (key press) for schedule race.

**Comment by klaasnicolaas** [comment]
Do you have a preference for which shortcut key it should be?
