### ISSUE TITLE
auto advance round spears to no longer work

### ISSUE THREAD

**Issue by Aaronsss** [RotorHazard/RotorHazard#801]
I have always used auto advance after you save a round so you don't have to manually change heat. After upgrading to 4.0.0 that no longer appears to advance the round.

I am using the best X rounds plugin with it not sure if that is relevant

**Comment by Aaronsss** [comment]
To confirm this works fine if you assign heat names. 

I think it would be good if this could be changed to give a default name to avoid this problem. That way it is one less thing to think about when throwing together a practice race

**Comment by HazardCreative** [comment]
That doesn't sound right. I'll look into it.

**Comment by HazardCreative** [comment]
Couldn't reproduce. Please provide steps and/or a database dump.

**Comment by HazardCreative** [comment]
Closing after no response. If encountered again, please provide steps and/or a database dump.
