### ISSUE TITLE
Raceclass custom attributes

### ISSUE THREAD

**Issue by i-am-grub** [RotorHazard/RotorHazard#803]
Looking to have the ability to read and write custom attributes to a raceclass through the RHAPI. 

For my specific use case, assigning a MultiGP race id to a raceclass, the attribute wouldn't have to be shown through the UI.

**Comment by HazardCreative** [comment]
This is planned. I suppose I could get it done faster if I deploy without UI support first.

**Comment by HazardCreative** [comment]
Closed in #836
