### ISSUE TITLE
gevent no matching distribution

### ISSUE THREAD

**Issue by gvotteler** [RotorHazard/RotorHazard#804]
**Describe the bug**
I'm updating from the lasted beta version to the release 4.0.0 and after type the comand for upgrade the dependencies, I get an error in that means (Line 20 could not find version that satisfies the requeriment gevent ===23.9) and the install stopped.

I have Pyhton 3.7 and the others beta versions worked fine.

**Comment by HazardCreative** [comment]
There seems to be some issues with what's available between python versions. As a workaround, altering `requirements.txt` to remove the version specification on `gevent` seems to work. gevent 22 has a known vulnerability, though.

https://github.com/advisories/GHSA-x7m3-jprg-wc5g

**Comment by gvotteler** [comment]
Ok thank you, so the solution will be change to 22 version?

**Comment by HazardCreative** [comment]
Yes.

According to https://pypi.org/project/gevent/ , gevent 23 is only available from python 3.8 and up. The means RH can't officially support python 3.7 anymore without recommending installing a dependency with a known vulnerability.

**Comment by ethomas997** [comment]
@gvotteler See this wiki page for a way to upgrade the version of Python or an existing setup

https://github.com/RotorHazard/RotorHazard/wiki/Installing-Newer-Versions-of-Python-on-the-Raspberry-Pi
