### ISSUE TITLE
Install instructions on install page are wrong

### ISSUE THREAD

**Issue by Strangedave** [RotorHazard/RotorHazard#808]
Script in the github instructions

cd ~
wget https://codeload.github.com/RotorHazard/RotorHazard/zip/v1.2.3 -O temp.zip
unzip temp.zip
mv RotorHazard RotorHazard.old
mv RotorHazard-v1.2.3 RotorHazard
rm temp.zip
cp RotorHazard.old/src/server/config.json RotorHazard/src/server/
cp RotorHazard.old/src/server/database.db RotorHazard/src/server/
cp -r RotorHazard.old/src/server/venv RotorHazard/src/server/

what it should be. 

cd ~
wget https://codeload.github.com/RotorHazard/RotorHazard/zip/1.2.3 -O temp.zip
unzip temp.zip
mv RotorHazard RotorHazard.old
mv RotorHazard-1.2.3 RotorHazard
rm temp.zip
cp RotorHazard.old/src/server/config.json RotorHazard/src/server/
cp RotorHazard.old/src/server/database.db RotorHazard/src/server/

**Comment by HazardCreative** [comment]
The venv line is correct. It'll fail if you haven't set up a venv, which is now the recommended way to do it and required depending on your python/OS setup. If you haven't set up a venv and you run it, that line will produce an error but cause no ill effects.
