### ISSUE TITLE
Error: RPI.GPIO doesn't work for the Pi5 because it now uses the RP1 chip

### ISSUE THREAD

**Issue by martinglass** [RotorHazard/RotorHazard#810]
Fresh install of RH v4.0.0 on Raspberry Pi 5, using latest 64-bit Raspian Bookworm OS

Following the instructions in /doc/Software Setup.md, including the new venv commands ...
On the command line "pip install -r requirements.txt"

The following error occured:

**Log Dump**
Installing collected packages: cffi, Adafruit-GPIO, pi-ina219, Flask, gevent-websocket, flask_sqlalchemy, Flask-SocketIO
  DEPRECATION: cffi is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for cffi ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for cffi did not run successfully.
  │ exit code: 1
  ╰─> [60 lines of output]
      Package libffi was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libffi.pc'
      to the PKG_CONFIG_PATH environment variable
      Package 'libffi', required by 'virtual:world', not found
      Package libffi was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libffi.pc'
      to the PKG_CONFIG_PATH environment variable
      Package 'libffi', required by 'virtual:world', not found
      Package libffi was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libffi.pc'
      to the PKG_CONFIG_PATH environment variable
      Package 'libffi', required by 'virtual:world', not found
      Package libffi was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libffi.pc'
      to the PKG_CONFIG_PATH environment variable
      Package 'libffi', required by 'virtual:world', not found
      Package libffi was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libffi.pc'
      to the PKG_CONFIG_PATH environment variable
      Package 'libffi', required by 'virtual:world', not found
      /home/martin/RotorHazard/src/server/venv/lib/python3.11/site-packages/setuptools/config/setupcfg.py:515: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      running install
      /home/martin/RotorHazard/src/server/venv/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-311
      creating build/lib.linux-aarch64-cpython-311/cffi
      copying cffi/error.py -> build/lib.linux-aarch64-cpython-311/cffi
      copying cffi/setuptools_ext.py -> build/lib.linux-aarch64-cpython-311/cffi
      copying cffi/cparser.py -> build/lib.linux-aarch64-cpython-311/cffi
      copying cffi/backend_ctypes.py -> build/lib.linux-aarch64-cpython-311/cffi
      copying cffi/verifier.py -> build/lib.linux-aarch64-cpython-311/cffi
      copying cffi/commontypes.py -> build/lib.linux-aarch64-cpython-311/cffi
      copying cffi/recompiler.py -> build/lib.linux-aarch64-cpython-311/cffi
      copying cffi/vengine_gen.py -> build/lib.linux-aarch64-cpython-311/cffi
      copying cffi/pkgconfig.py -> build/lib.linux-aarch64-cpython-311/cffi
      copying cffi/api.py -> build/lib.linux-aarch64-cpython-311/cffi
      copying cffi/model.py -> build/lib.linux-aarch64-cpython-311/cffi
      copying cffi/__init__.py -> build/lib.linux-aarch64-cpython-311/cffi
      copying cffi/ffiplatform.py -> build/lib.linux-aarch64-cpython-311/cffi
      copying cffi/lock.py -> build/lib.linux-aarch64-cpython-311/cffi
      copying cffi/cffi_opcode.py -> build/lib.linux-aarch64-cpython-311/cffi
      copying cffi/vengine_cpy.py -> build/lib.linux-aarch64-cpython-311/cffi
      copying cffi/_cffi_include.h -> build/lib.linux-aarch64-cpython-311/cffi
      copying cffi/parse_c_type.h -> build/lib.linux-aarch64-cpython-311/cffi
      copying cffi/_embedding.h -> build/lib.linux-aarch64-cpython-311/cffi
      copying cffi/_cffi_errors.h -> build/lib.linux-aarch64-cpython-311/cffi
      running build_ext
      building '_cffi_backend' extension
      creating build/temp.linux-aarch64-cpython-311
      creating build/temp.linux-aarch64-cpython-311/c
      aarch64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/home/martin/RotorHazard/src/server/venv/include -I/usr/include/python3.11 -c c/_cffi_backend.c -o build/temp.linux-aarch64-cpython-311/c/_cffi_backend.o
      c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory
         15 | #include <ffi.h>
            |          ^~~~~~~
      compilation terminated.
      error: command '/usr/bin/aarch64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> cffi

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by martinglass** [comment]
A manual command "pip install SQLAlchemy==1.3.*" seemed to fix the issue

**Comment by martinglass** [comment]
FYI - OS default for Python is :
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux

**Comment by martinglass** [comment]
It appears that Pi Raspbian OS Bookwork is being updated significantly. For example, the stock version doesn't work with the Pi Cameras, but the new updates this weekend have fixed most of the bugs.
I suspect, this is also affecting the RotorHazard installation.
Also, I see that the minimum version for RotorHazard has just been increased to v3.8 today. 
Python 3.11 is the Pi v5 stock version installed with Pi Raspbian OS Bookwork now.
I'll keep testing the RH Installation Instructions with (fresh install) Pi 5

**Comment by HazardCreative** [comment]
Thank you for your ongoing work with this.

**Comment by martinglass** [comment]
No worries. I'd do more if I had the time to spare. House projects eat up your time, as you know ;)

**Comment by ethomas997** [comment]
Hi Martin, thanks for testing.  I tried it today and was able to do the entire RotorHazard setup on a Pi 3 running the latest ("Bookworm" 64-bit) version of the OS.  If you upgrade to the latest ("sudo apt update && sudo apt upgrade"), are you still seeing the errors when doing it on the Pi 5?

**Comment by martinglass** [comment]
> Hi Martin, thanks for testing. I tried it today and was able to do the entire RotorHazard setup on a Pi 3 running the latest ("Bookworm" 64-bit) version of the OS. If you upgrade to the latest ("sudo apt update && sudo apt upgrade"), are you still seeing the errors when doing it on the Pi 5?

Hi Eric, I've been testing out various combinations of Boards and OS's and I concur with you that RH installs and works as expected on Pi3 with Bookworm (Python 3.11.2) both 32-bit OS and 64-bit OS.

I've tested using a Pi5 and the most recent (26th Nov. 2023) sudo apt update && sudo apt upgrade. And it has a problem reading the GPIO pins.

I've looked up the error on this page: https://forums.raspberrypi.com/viewtopic.php?t=358599
It says "RPI.GPIO doesn't work for the Pi5 because it now uses the RP1 chip, you need to move to something else like gpiozero, lgpio, ..."

Also see: https://www.tomshardware.com/how-to/control-raspberry-pi-5-gpio-with-python-3
**_With the Raspberry Pi 5, we are unable to use RPi.GPIO due to how the GPIO pins are memory mapped. This forces us to use an alternative, and libgpiod is the focus of this how to.
Libgpiod, specifically [python3-gpiod](https://github.com/hhk7734/python3-gpiod) is a pure Python module for interacting with the GPIO._**

What's your thoughts ? Here's the log(s) ...

python server.py
RotorHazard v4.0.0
Traceback (most recent call last):
  File "/home/martin/RotorHazard/src/server/server.py", line 76, in <module>
    import RHGPIO
  File "/home/martin/RotorHazard/src/server/RHGPIO.py", line 34, in <module>
    GPIO.setup(RHGPIO_S32ID_PIN, GPIO.IN, pull_up_down=GPIO.PUD_UP)
RuntimeError: No access to /dev/mem.  Try running as root!

Then, as root:
sudo ~/.venv/bin/python server.py
RotorHazard v4.0.0
Traceback (most recent call last):
  File "/home/martin/RotorHazard/src/server/server.py", line 76, in <module>
    import RHGPIO
  File "/home/martin/RotorHazard/src/server/RHGPIO.py", line 34, in <module>
    GPIO.setup(RHGPIO_S32ID_PIN, GPIO.IN, pull_up_down=GPIO.PUD_UP)
RuntimeError: Mmap of GPIO registers failed

**Comment by martinglass** [comment]
I've changed the Title of this Issue to **"Error: RPI.GPIO doesn't work for the Pi5 because it now uses the RP1 chip"**

**Comment by ethomas997** [comment]
Yes, the GPIO support something we should update.  Issue #715 is also related to this.

**Comment by martinglass** [comment]
Workaround could be changing RHGPIO.py to this, if you're willing to lose the GPIO-based shutdown

RHGPIO.py
# Utility class for Raspberry Pi GPIO functions

import time

RealRPiGPIOFlag = False
# if RPi.GPIO not available then use FakeRiGPIO from https://github.com/sn4k3/FakeRPi

RHGPIO_S32ID_PIN = 25  # input is tied low on S32_BPill PCB

S32BPillBoardFlag = False

def isRealRPiGPIO():
    return RealRPiGPIOFlag

def isS32BPillBoard():
    return S32BPillBoardFlag

def setS32BPillBoardFlag():
    global S32BPillBoardFlag
    S32BPillBoardFlag = True

**Comment by martinglass** [comment]
BTW - the Pi5 board is super fast!

**Comment by ethomas997** [comment]
I wouldn't want to lose GPIO-based shutdown, but it may be possible to have it work differently and use different libraries depending on the configuration and hardware

**Comment by martinglass** [comment]
> I wouldn't want to lose GPIO-based shutdown, but it may be possible to have it work differently and use different libraries depending on the configuration and hardware

Yeah. Sure. I wasn't suggesting to drop the GPIO-based shutdown or the STM32 firmware update function, if that's affected too. I was just providing a temporary workaround, to get the Pi5 working in some way at least.

**Comment by ethomas997** [comment]
It looks like it's currently impossible to get a Pi 5 at a reasonable price, so it's going to be hard for us to work with it.

**Comment by martinglass** [comment]
Availability in USA and elsewhere of the Pi5 is a problem. Meanwhile, it might be a good idea to wait anyway, as the author of RPI.GPIO will probably update it sometime (hopefully soon) to work with the Pi5 and RP1 chip. 

I see that author of RPI.GPIO (Ben Croston) has a track record of updating the library, for example to make it compatible with the Pi4. Fingers crossed he'll do the same soon for the Pi5, although I suspect the alterations needed will be more complex this time.

**Comment by ethomas997** [comment]
I have a Raspberry Pi 5 on hand now that I can test things with

**Comment by martinglass** [comment]
> I have a Raspberry Pi 5 on hand now that I can test things with

Excellent. Good luck 👍

**Comment by smith1488888** [comment]
Are there any updates on getting RH to work with the Pi 5?

I have one and after setup (following the Pi 5 instructions) end up with this error:

RotorHazard v4.0.1
Traceback (most recent call last):
File "/home/NuclearHazard/RotorHazard/src/server/server.py", line 75, in <module>
import RHGPIO
File "/home/NuclearHazard/RotorHazard/src/server/RHGPIO.py", line 34, in <module>
GPIO.setup(RHGPIO_S32ID_PIN, GPIO.IN, pull_up_down=GPIO.PUD_UP)
RuntimeError: Cannot determine SOC peripheral base address

I've tried both the workaround mentioned above, and the one mentioned here https://forums.raspberrypi.com/viewtopic.php?p=2160578#p2160578 and while it is then able to start the server, it is not functional as it shows these warnings on the RH web server:

Warning: Unable to access real GPIO on Pi. Try: sudo pip install RPi.GPIO
Warning: No receiver nodes found

This is the boot log at that time:

RotorHazard v4.0.1
Release: 4.0.1 / Server API: 41 / Latest Node API: 35
Host machine: Raspberry Pi 5 Model B Rev 1.0
Host OS: Linux 6.1.0-rpi7-rpi-2712
Python version: 3.11.2
Host machine is 'nuclearhazard' at 192.168.1.119
Loaded plugin 'rh_led_handler_graph'
Loaded plugin 'rh_data_import_json'
Loaded plugin 'rh_led_handler_bitmap'
Loaded plugin 'rh_connector_trackside'
Loaded plugin 'rh_class_rank_cumulative_points'
Loaded plugin 'rh_led_handler_character'
Loaded plugin 'rh_heatgenerator_standard'
Loaded plugin 'rh_actions_builtin'
Loaded plugin 'rh_class_rank_best_x_rounds'
Loaded plugin 'rh_led_handler_strip'
Loaded plugin 'rh_class_rank_heat_pos'
Loaded plugin 'rh_heatgenerator_ladder'
Loaded plugin 'rh_data_export_json'
Loaded plugin 'rh_data_export_csv'
Loaded plugin 'rh_points_by_position'
Unable to access real GPIO on Pi; try: sudo pip install RPi.GPIO
Using configuration file 'config.json'
Using log file: logs/rh_20240122_221241.log
Loaded module i2c_helper
Loaded module i2c_node
Loaded module serial_node
Searching for I2C nodes...
...No I2C node at address 8
...No I2C node at address 10
...No I2C node at address 12
...No I2C node at address 14
...No I2C node at address 16
...No I2C node at address 18
...No I2C node at address 20
...No I2C node at address 22
*** WARNING: NO RECEIVER NODES FOUND ***
Loaded module bme280_sensor
Loaded module ina219_sensor
Loaded module linux_sensor
Core temperature available
No 'database.db' file found; creating initial database
Database pilots reset
Database heats reset
Database saved races reset
Database set default profiles
Database reset race formats
Database race classes reset
Reset global settings
Database initialized
Set Profile to '1'
Switching to practice mode; races will not be saved until a heat is selected
VRx Control disabled: no registered controllers
Running http server at port 5000
Initializing Trackside connector

Happy to try any other suggestions folks might have and report back.

**Comment by klaasnicolaas** [comment]
You need to use the development branch, v4.0.1 does not support the raspberry pi 5.

**Comment by smith1488888** [comment]
Thank you, I'm not super familiar with Github so wasn't aware the main branch was newer! I've got it working now.

**Comment by HazardCreative** [comment]
Please note that the main branch is development code that is not considered stable.

**Comment by ethomas997** [comment]
Resolved by PR #848
