### ISSUE TITLE
scanner.py - MonkeyPatchWarning Python3.7+

### ISSUE THREAD

**Issue by martinglass** [RotorHazard/RotorHazard#819]
When running scanner.py I encountered an error relating to [https://github.com/gevent/gevent/issues/1016](https://github.com/gevent/gevent/issues/1016)

/home/pi/RotorHazard-main/src/server/scanner.py:7: MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016. Modules that had direct imports (NOT patched): ['urllib3.util (/home/pi/.venv/lib/python3.9/site-packages/urllib3/util/__init__.py)', 'urllib3.util.ssl_ (/home/pi/.venv/lib/python3.9/site-packages/urllib3/util/ssl_.py)']. 
  gevent.monkey.patch_all()

This fix got rid of the warning notice:
/home/pi/RotorHazard-main/src/server/scanner.py
import gevent.monkey
gevent.monkey.patch_all()
import sys
from flask import Flask, render_template
from flask_socketio import SocketIO
import webbrowser

**Comment by HazardCreative** [comment]
The warning only mentions Python 3.6 and 3.7, but RotorHazard's minimum version is 3.8.

**Comment by martinglass** [comment]
Thanks for getting back. I'm using Python 3.9 and the warning came up with that.

**Comment by ethomas997** [comment]
I wasn't able to reproduce the issue, but moving up those imports will match what is done in 'server.py' so we might as well do that.
