### ISSUE TITLE
LED panel text functions incompatible with Pillow 10

### ISSUE THREAD

**Issue by starz91** [RotorHazard/RotorHazard#822]
HELLO EVERYONE,

 I no longer have a text effect with the latest version. I am attaching the log.

can you help me please

[rh_logs_20231211_055738.zip](https://github.com/RotorHazard/RotorHazard/files/13643795/rh_logs_20231211_055738.zip)

json for info
   "LED": {
        "LED_COUNT": 256,
        "LED_ROWS": 16,
        "LED_PIN": 10,
        "LED_INVERT": false,
        "LED_CHANNEL": 0,
        "PANEL_ROTATE": 1,
        "INVERTED_PANEL_ROWS": true,
        "LED_DMA": 10,
        "LED_FREQ_HZ": 800000

**Comment by HazardCreative** [comment]
Looks like the Pillow library removed a feature that RotorHazard is using. We will have to write a fix for this.

As a temporary workaround, try downgrading Pillow: `pip install Pillow<=9.5.0`

**Comment by HazardCreative** [comment]
Adding a reference to aid future remediation: https://github.com/tensorflow/models/issues/11040

**Comment by starz91** [comment]
> pip install Pillow<=9.5.0

hi i have this message in french "pi@raspberrypi:~ $ pip install Pillow<=9.5.0
-bash: =9.5.0: Aucun fichier ou dossier de ce type"

**Comment by starz91** [comment]
> pip install Pillow==9.5.0

SORRY don't work after downgrading, same problem

**Comment by HazardCreative** [comment]
Are there errors in the new log?

**Comment by starz91** [comment]
> Are there errors in the new log?

new log 
[rh_logs_20231212_175007.zip](https://github.com/RotorHazard/RotorHazard/files/13651008/rh_logs_20231212_175007.zip)

**Comment by HazardCreative** [comment]
I'm seeing the same error as your previous log. Are you certain RotorHazard is using Pillow 9.5?

If you set up a venv per the 4.0.0 instructions, you may need to activate it before running the `pip` command.

```cd ~/RotorHazard/src/server
source venv/bin/activate
pip show Pillow```

If it's not showing 9.5, run `pip install Pillow==9.5.0` again there.

**Comment by starz91** [comment]
> I'm seeing the same error as your previous log. Are you certain RotorHazard is using Pillow 9.5?
> 
> If you set up a venv per the 4.0.0 instructions, you may need to activate it before running the `pip` command.
> 
> ```
> cd ~/RotorHazard/src/server
> source venv/bin/activate
> pip show Pillow
> ```
> 
> If it's not showing 9.5, run `pip install Pillow==9.5.0` again there.

same problem 
[rh_logs_20231212_180914.zip](https://github.com/RotorHazard/RotorHazard/files/13651215/rh_logs_20231212_180914.zip)

**Comment by HazardCreative** [comment]
What did the `pip show Pillow` command return?

**Comment by starz91** [comment]
> pip install Pillow==9.5.0

the problem is worse than before. I no longer have the rotorhazard image for example.
summary: image and text don't work
[rh_logs_20231212_182135.zip](https://github.com/RotorHazard/RotorHazard/files/13651342/rh_logs_20231212_182135.zip)

/Name: Pillow
Version: 10.1.0
Summary: Python Imaging Library (Fork)
Home-page: https://python-pillow.org
Author: Jeffrey A. Clark (Alex)
Author-email: aclark@aclark.net
License: HPND
Location: /home/pi/RotorHazard/src/server/venv/lib/python3.9/site-packages
Requires:
Required-by:
(venv) pi@raspberrypi:~/RotorHazard/src/server $ pip install Pillow==9.5.0
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting Pillow==9.5.0
  Downloading https://www.piwheels.org/simple/pillow/Pillow-9.5.0-cp39-cp39-linux_armv7l.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 1.0 MB/s
Installing collected packages: Pillow
  Attempting uninstall: Pillow
    Found existing installation: Pillow 10.1.0
    Uninstalling Pillow-10.1.0:
      Successfully uninstalled Pillow-10.1.0
Successfully installed Pillow-9.5.0

**Comment by starz91** [comment]
> Something seems wrong with your `Pillow` install now, as Python can't locate some of its core components.
> 
> Your log says: `AttributeError: module 'PIL.Image' has no attribute 'new'`
> 
> But I can access that function just fine with a Pillow 9.5 install locally.
> 
> ```
>  > pip show Pillow
> Name: Pillow
> Version: 9.5.0
> Summary: Python Imaging Library (Fork)
> Home-page: https://python-pillow.org
> Author: Jeffrey A. Clark (Alex)
> Author-email: aclark@aclark.net
> License: HPND
> Location: c:\users\web designer\appdata\local\programs\python\python310\lib\site-packages
> Requires:
> Required-by: matplotlib
> 
>  > python
> Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from PIL import Image, ImageFont, ImageDraw
> >>> Image.new('RGB', [10,10])
> <PIL.Image.Image image mode=RGB size=10x10 at 0x1FE22819CF0>
> ```
> 
> Perhaps run `pip install --upgrade --force-reinstall --no-cache-dir Pillow==9.5.0` and see if something was wrong with the 9.5 package download or install. (Don't forget to activate the venv, as above).

it's OK !! perfect thank you
