### ISSUE TITLE
Main branch is not currently working on the Linux VM

### ISSUE THREAD

**Issue by szafranski** [RotorHazard/RotorHazard#854]
Stable branch works, main shows this:
<img width="910" alt="image" src="https://github.com/RotorHazard/RotorHazard/assets/23621888/81fa0e67-9db5-4455-9047-bb70615f324d">

After: pip3 install lgpio it boots, but shows this:

<img width="923" alt="image" src="https://github.com/RotorHazard/RotorHazard/assets/23621888/40e1845e-02a6-4b8b-8581-19713d6dc57e">

<img width="924" alt="image" src="https://github.com/RotorHazard/RotorHazard/assets/23621888/5fe2d51f-be5a-4e60-bbd1-e1ee3b3ee4c6">

System info:
nh@rh:~/RH_Install-Manager$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

Linux container on Proxmox btw

**Comment by ethomas997** [comment]
@szafranski  Please try it with the modification I just pushed ("Improved import error handling in RH_GPIO") and let me know

**Comment by szafranski** [comment]
Now when I UNISTALLED lgpio it is ok. With it it shows as before. So maybe considered as fixed?

**Comment by ethomas997** [comment]
With 'lpgio' installed does the server startup and run okay (except for the warning message)?  If so then I'd say we can consider it fixed and close this issue.
