### ISSUE TITLE
New beta on pi4 with Bullseye needs some libraries - probably

### ISSUE THREAD

**Issue by szafranski** [RotorHazard/RotorHazard#857]
Hi, just saw this on on Pi OS 11, Pi 4:

![image](https://github.com/RotorHazard/RotorHazard/assets/23621888/295138ba-e1a4-4927-b63e-5a0405d2489d)

**Comment by ethomas997** [comment]
Please generate and post logs zip as per:  https://github.com/RotorHazard/RotorHazard/blob/main/doc/Software%20Setup.md#logging

**Comment by HazardCreative** [comment]
Normal if you have not installed LED support.

Ignorable if you do not need it.

**Comment by szafranski** [comment]
Ok, correct. Installing LED related libraries removes that "warning".

**Comment by HazardCreative** [comment]
This one is a slightly odd case where you must have partially installed support. The Pillow library must be added to Python which you did have, but the libopenjp2 package is for the operating system, which you did not have.

**Comment by szafranski** [comment]
Idk why it was not installed - it is a part of RHIM. Regardless - maybe it should be done to requirements.txt?

**Comment by ethomas997** [comment]
Yes, I think adding the 'pillow' to "requirements.txt' is on our to do list

**Comment by ethomas997** [comment]
The 'Pillow' library requires that 'libjpeg-dev' be installed (via "sudo apt-get install") on the Pi, and installing 'Pillow' seems to take several minutes, so I think it's best to not include it in "requirements.txt".  The user can install it via the instructions for "LED Panel Support" if they need it.
