### ISSUE TITLE
addition of a way for plugins to get a kick at a specified time interval

### ISSUE THREAD

**Issue by Aaronsss** [RotorHazard/RotorHazard#862]
It would be great if there was a way for plugins to get a periodic kick at a specified time interval. Something that is not related to race events.

This will allow for periodic checking of sensors

**Comment by Aaronsss** [comment]
It would be nice if these could be added as event actions so Something like every 1 second, every 10 seconds, every 1 min, every 10 mins etc

**Comment by HazardCreative** [comment]
#925 will make this possible.
This isn't really intended for sensors, but that's not yet addressed by RHAPI. If you build on, you'll likely want to migrate in the future when that becomes available.

**Comment by HazardCreative** [comment]
925 has been merged.
