### ISSUE TITLE
declarative_base import issues on latest commit

### ISSUE THREAD

**Issue by i-am-grub** [RotorHazard/RotorHazard#865]
As of [999944d](https://github.com/RotorHazard/RotorHazard/commit/999944d5f60033ac20fdc63059e42a9f4a4df93e) 

- Windows (updated pip packages)
- python 3.11
- SQLAlchemy version: 2.0.27

```
Traceback (most recent call last):
  File "d:\Repos\RotorHazard-plug-in-dev\src\server\server.py", line 68, in <module>
    import Database
  File "d:\Repos\RotorHazard-plug-in-dev\src\server\Database.py", line 7, in <module>
    from sqlalchemy.orm import scoped_session, sessionmaker, declarative_base
ImportError: cannot import name 'declarative_base' from 'sqlalchemy.orm' (D:\Repos\RotorHazard-plug-in-dev\src\server\venv\Lib\site-packages\sqlalchemy\orm\__init__.py)
```

I did have success with 
```
from sqlalchemy.ext.declarative import declarative_base
```

**Comment by ethomas997** [comment]
If you can get into the web GUI, please generate a ".zip" file using the "Download Logs" button (in Settings | System) and post it here.  If not, please attach a complete log file here.

**Comment by i-am-grub** [comment]
It appears that the `pip.exe` located in my venv environment wasn't updating the packages for the `python.exe` located within the same environment.

targeting the specific `python.exe` using `-m pip` was able to update the packages successfully and the server is starting as expected with `sqlalchemy.orm`
