### ISSUE TITLE
DB restore issues on latest commit

### ISSUE THREAD

**Issue by i-am-grub** [RotorHazard/RotorHazard#866]
As of [999944d](https://github.com/RotorHazard/RotorHazard/commit/999944d5f60033ac20fdc63059e42a9f4a4df93e)

Currently unable to restore saved databases on the main branch. All data (including global variables) appear to be wiped, but the restore doesn't appear to occur after that.

Test database has been sent over to Hazard.

**Comment by i-am-grub** [comment]
Additional note, there was an issue with restoring raceclass attributes on v4.1.0-beta.1. There may have been an issue with the other new attributes as well, but they were untested at the time. Global settings and pilot attributes appeared to work as expected.

**Comment by ethomas997** [comment]
I just committed a fix; please try with latest 'main' branch

**Comment by i-am-grub** [comment]
It looks like there is still an issue with restoring raceclass attributes. After some more testing on my side, it looks like the first attribute is restored correctly, but not the remaining. The database in the attached logs is pre-archival. I am still unaware if this issue extends to other new attributes as well.

[missing_attributes_rh_logs.zip](https://github.com/RotorHazard/RotorHazard/files/14353985/missing_attributes_rh_logs.zip)

**Comment by ethomas997** [comment]
Thanks for posting the logs-zip file.  My latest commit should fix the issue with 'race_class_attributes'; let me know if it works for you.

**Comment by i-am-grub** [comment]
Testing on my end suggests that the change successfully fixed the issue
