### ISSUE TITLE
Post-race recalculation doesn't match realtime calculation

### ISSUE THREAD

**Issue by HazardCreative** [RotorHazard/RotorHazard#87]
Now that I have a rudimentary interface for doing a race recalc, I see that numbers are in the rough ballpark but not nearly accurate enough. My best guess at the moment is the issue is related to history collection. With history collection, I'm trying to gather only the peaks and valleys, ignoring intermediate values while the data rises and falls, in order to keep bandwidth and data storage requirements as low as possible. 

Would appreciate review of these areas. One area I can identify of concern is handling of identical rssi values over time. I think this behavior is different, but it doesn't explain everything I'm seeing.

(Applies only to history-recalc branch at this point. Not sure if there's a proper way for me to tag that in the issue.)

![image](https://user-images.githubusercontent.com/7169527/58476945-4babd600-8120-11e9-99c6-5410e91d7ae7.png)
![image](https://user-images.githubusercontent.com/7169527/58477033-86ae0980-8120-11e9-9fee-17cee7e58bbb.png)

**Comment by HazardCreative** [comment]
I see in the data that often both a peak and a nadir are being marked as having the same timestamp. That shouldn't be possible, so I bet there's something in that to fix.

**Comment by pulquero** [comment]
Shouldnt the 2nd graph by plotting the history data? or it would be a good idea to plot the history data to see if the peaks/nadirs match with the original data.

**Comment by HazardCreative** [comment]
I can only graph the history data, not the real-time data. It's very
difficult to capture the original: the I2C bandwidth/availability isn't
high enough to transfer it in real time, and there's not enough storage on
the nano to buffer it there to transfer later. The real-time graph is only
polling at 10hz. I did store that data at one point, but abandoned that
approach because of its lack of accuracy. That's why I'm now sending a peak
with a captured time. This approach has the potential to match the accuracy
of the real-time tracking. I think the theory is sound but the
implementation is lacking somewhere.

**Comment by HazardCreative** [comment]
Oh, man. Such a newbie mistake right there. I bet that's causing all sorts of trouble.
https://github.com/RotorHazard/RotorHazard/blob/615ab2febbf625ce8d16736dcaccc82f1d83601f/src/node/node.ino#L407

**Comment by HazardCreative** [comment]
Fixed in cac7061.
