### ISSUE TITLE
Assign colors for Channels and Seats

### ISSUE THREAD

**Issue by YegorYegor** [RotorHazard/RotorHazard#875]
**Confirm the issue is with RotorHazard and not a plugin**
Yes, it is not about plugin

**Describe the bug**
If you assign colors for channels, it will be solid colors for pilot 1-6 that you can't change and no color at all for pilots 7-8
If you change channels table for nodes, colors will be the same, so it assigned not for channel, but for nodes, and only fo 1-6, not for 7-8.
If you choose to assign colors for seats, it will working same, but there are colors for all 8 pilots. But you still can't change assigned colors. For example Blue for Node 4 and Pink for Node 1.(now as default Blue for Node1 and pink for Node4)

**To Reproduce**
1. Format->Pilots->ColorMode->Frequency
2. Run->Practice Mode
3. Pilots colors are white for Node1,7,8.

**Expected behavior**
...
3.Pilots colors are different for all nodes.

**Screenshots**
![2](https://github.com/RotorHazard/RotorHazard/assets/12016942/2f01c5a3-ed5d-4c0a-a92f-2544b8aa8ce1)
![1](https://github.com/RotorHazard/RotorHazard/assets/12016942/c5750d2d-e6ce-4722-bbb3-a79c659c5534)

**Log Dump**
If at all possible, log into your server as an admin. Open the extended menu and select "View Server Log". Click on the "Download Logs" button to create and download a '.zip' archive file containing all available log files and the current configuration and database files. Upload that file into this issue.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Google Chrome
 - Version 122.0.6261.128

**Smartphone (please complete the following information):**

**Additional context**
Release: 4.1.0-dev.7 / Server API: 43 / Latest Node API: 35

**Comment by HazardCreative** [comment]
Thank you for the report. I will review.

**Comment by HazardCreative** [comment]
Resolved in latest version(s). Note that in some cases a new heat needs to be selected for color method changes to be reflected.
