### ISSUE TITLE
Ability for plugins to register stream element URLs in addition to the built in ones

### ISSUE THREAD

**Issue by skyfpv** [RotorHazard/RotorHazard#878]
**The Problem**
Currently, when creating a plugin, developers must communicate in their repository what URLs can be used to access any stream elements their plugin may expose. This may become burdensome as more plugins are created and installed by users.

**Describe the solution I'd like**
The solution I'd propose is a an additional plugin api method which allows plugins to register stream element urls. These URLs could then appear where the user expects in the RotorHazard UI. http://rotorhazard.local/streams

Here is what I imagine this might look like. The main goal would be to help race directors keep track of all the plugin-based stream elements they have access too.
![image](https://github.com/RotorHazard/RotorHazard/assets/45609851/83df9d39-66b9-407b-8667-8b4e5a17c459)

**Comment by HazardCreative** [comment]
Seems like this could be accomplished with:
- Allowing plugins to register a panel on the Streams page
- Creation of a non-interactive field for custom UI panels

The former is easy if not already done; the latter is planned.

**Comment by klaasnicolaas** [comment]
Plugins can already add a panel to the streams page 😉 

./Klaas

**Comment by skyfpv** [comment]
ahh thanks @klaasnicolaas . Not sure how I missed that
