### ISSUE TITLE
Unable to send message in multibyte language.

### ISSUE THREAD

**Issue by ToshihiroMakuuchi** [RotorHazard/RotorHazard#881]
We have found that the input form below does not allow submissions in multibyte languages such as Japanese. Please correct this if possible.

![Send_Massage01](https://github.com/RotorHazard/RotorHazard/assets/36994795/698b55c8-f935-4cc2-aea9-0b1cd3fa32cf)

**Comment by HazardCreative** [comment]
The issue appears to be that non-alphanumeric messages are thrown out when the hit this regular expression filter.
https://github.com/RotorHazard/RotorHazard/blob/main/src/server/RHUI.py#L308

@ethomas997 do you recall the purpose of the filter and can it be improved?

**Comment by ethomas997** [comment]
@HazardCreative The purpose of the filter is to abort if the message contains only blanks or only blanks and punctuation (i.e., "   ,   ").  I can see about making it more compatible with other languages / character-sets.

**Comment by ethomas997** [comment]
Fixed via https://github.com/RotorHazard/RotorHazard/commit/16b551efc79b1b9493df33c47833e523813d2cac
