### ISSUE TITLE
Add Average of the 3 best laps

### ISSUE THREAD

**Issue by arnaudmorin** [RotorHazard/RotorHazard#889]
**Is your feature request related to a problem? Please describe.**
When running a FAI race, we may want to use the "Average of the 3 best laps" option (see doc here: https://www.fai.org/sites/default/files/ciam/wcup_drones/sc4_vol_f9_dronesport_24_0.pdf option 2 p.32).

**Describe the solution you'd like**
We need a new race format (Average of the 3 best laps), and a new result table that show that.

**Comment by HazardCreative** [comment]
Does the "Best X Laps" plugin accomplish your task (or nearly so)?
https://github.com/HazardCreative/RotorHazard-Class-Rank-Best-X-Laps

The ranking will be identical to an average. You can easily adapt the plugin to divide all results by X if required.

**Comment by arnaudmorin** [comment]
Oh!
That seems to perfectly fit my needs :)
I wasn't aware of these plugins.
Is there any page referencing all available plugins somewhere?

**Comment by HazardCreative** [comment]
In the future I hope to have a system to discover, install, and manage built right in. For now, https://github.com/RotorHazard/RotorHazard/wiki/Available-Plugins

**Comment by HazardCreative** [comment]
Closing because feature exists by plugin.
