### ISSUE TITLE
NuclearHazard Beeper not working in Beta or Main when power button is pressed

### ISSUE THREAD

**Issue by Redalin** [RotorHazard/RotorHazard#891]
I have a Nuclearhazard PCB with a Raspberry Pi 4 and 4x RX5808 receivers.

**Describe the bug**
When Running the Stable branch of RH the NuclearHazard works great as expected.
To power it down using the hardware power button on the PCB it beeps when the button is pressed, and if held down for 2.5 seconds it shuts down the Pi while beeping, and does a long beep when shutdown is complete.

After an update to the Beta branch the buzzer no longer beeps when the power button is pressed. If held down the Pi still shuts down but does not run the beep cycle. Stays silent the whole time and gives no indication of shutdown status.
The Beeper DOES still beep on startup (2 when power applied, 2 when startup complete and 1 when the first connection is made).

Updating to the Main branch also exhibits the same behaviour.

Rolling back to the Stable branch the beeper starts working again 

**To Reproduce**
1. In RHIM, go to Rotorhazard manager - update the origin to Beta 
2. update the existing configuration
3. clear the old installation
4. reboot
5. Pi will reboot and beep when ready
6. Press the power button and hear no beeps.
7. Repeat steps 1-5 but change Origin to Stable
8. Press the power button and hear beeps.

**Comment by ethomas997** [comment]
@Redalin Thanks for the report.  If possible, could you generate a ".zip" file using the "Download Logs" button (in Settings | System), generating one when it's working and one when it's not working, and post them here?

**Comment by Redalin** [comment]
Thanks @ethomas997 I have attached them. Although I think i see the error you are looking for:

```
2024-05-01 11:40:50.891: __main__ [ERROR] Exception error in ButtonInputHandler setup
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpiozero/pins/pi.py", line 408, in pin
    pin = self.pins[info]
          ~~~~~~~~~^^^^^^
KeyError: PinInfo(number=35, name='GPIO19', names=frozenset({'J8:35', 19, '19', 'BCM19', 'WPI24', 'GPIO19', 'BOARD35'}), pull='', row=18, col=1, interfaces=frozenset({'', 'dpi', 'gpio', 'pcm', 'spi', 'pwm'}))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chris/RotorHazard/src/server/util/ButtonInputHandler.py", line 28, in __init__
    RH_GPIO.setup(gpioPinNum, RH_GPIO.IN, pull_up_down=RH_GPIO.PUD_UP)
  File "/home/chris/RotorHazard/src/server/util/RH_GPIO.py", line 90, in setup
    Input_devices_dict[channel] = gpiozero.InputDevice(channel, \
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 103, in __call__
    self = super().__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gpiozero/input_devices.py", line 79, in __init__
    super().__init__(pin, pin_factory=pin_factory)
  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 549, in __init__
    pin = self.pin_factory.pin(pin)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gpiozero/pins/pi.py", line 410, in pin
    pin = self.pin_class(self, info)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gpiozero/pins/lgpio.py", line 126, in __init__
    lgpio.gpio_claim_input(
  File "/usr/lib/python3/dist-packages/lgpio.py", line 755, in gpio_claim_input
    return _u2i(_lgpio._gpio_claim_input(handle&0xffff, lFlags, gpio))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lgpio.py", line 458, in _u2i
    raise error(error_text(v))
lgpio.error: 'GPIO busy'
```

Beta
[rh_logs_20240501_114453.zip](https://github.com/RotorHazard/RotorHazard/files/15172260/rh_logs_20240501_114453.zip)

Stable
[rh_logs_20240501_111351.zip](https://github.com/RotorHazard/RotorHazard/files/15172262/rh_logs_20240501_111351.zip)

**Comment by Redalin** [comment]
@ethomas997 I just tested it on the Main branch. (v4.1.0-dev.11) and the beeper is working again. 
Well done :)

**Comment by ethomas997** [comment]
Thanks for posting the info; great to hear it's working now!
