### ISSUE TITLE
Custom Frequencies / DJI 03 

### ISSUE THREAD

**Issue by ramiss** [RotorHazard/RotorHazard#900]
Hi there,

Just ran my rotor hazard with 7 pilots at our club for the first time this afternoon.  Everything worked fantastic, but the most difficult aspect was setting up frequencies.  You see, 6 out of 7 of us were on DJO 03 air units at 20mhz.  The pre-saved Dx frequencies worked for 03 above channel 3, but not the first two. It was tough to find a frequency close to 03 Ch2 and then tune it.  Took longer than all of the others combined.

Please can we have the ability to add and save our own custom frequencies OR can you add the 03 frequencies?

Thanks!

**Comment by ethomas997** [comment]
Note that in RotorHazard you can set the node to receive on any arbitrary MHz value, by entering it in the frequency field for any node in the "Settings | Frequency Setup" section.

**Comment by ramiss** [comment]
> Note that in RotorHazard you can set the node to receive on any arbitrary MHz value, by entering it in the frequency field for any node in the "Settings | Frequency Setup" section.

Correct. But remembering those frequencies and which go to which channel is cumbersome at best and prone to error.  The ask above is specifically about adding them to the dropdown presets list, whether we are allowed to add custom entries or the developer can add them.

**Comment by HazardCreative** [comment]
- O3 frequencies are already available; use O or Q bands.
- See [Frequency Reference](https://github.com/RotorHazard/RotorHazard/blob/main/doc/img/Frequency%20Reference%20Chart%202024-02-18.png) (also available within the UI).
- You may save any frequency, including arbitrary setups, into a frequency set (or "profile").

**Comment by ramiss** [comment]
> * O3 frequencies are already available; use O or Q bands.
> * See [Frequency Reference](https://github.com/RotorHazard/RotorHazard/blob/main/doc/img/Frequency%20Reference%20Chart%202024-02-18.png) (also available within the UI).
> * You may save any frequency, including arbitrary setups, into a frequency set (or "profile").
> 
> See also: #859

Recently added?  I installed v4.01 three weeks ago and only see (R, F, E, B, A, L, U, D, J & S).

**Comment by ethomas997** [comment]
> Recently added? I installed v4.01 three weeks ago and only see (R, F, E, B, A, L, U, D, J & S).

Yes, you'll need to install the latest beta release to get those new bands

**Comment by ramiss** [comment]
Perfect, thanks for the info.
