### ISSUE TITLE
Event Actions state does not save, until you reboot your pi or rh service

### ISSUE THREAD

**Issue by YegorYegor** [RotorHazard/RotorHazard#906]
Issue with a rh, not a plugin.

Changing Event Actions does not work until you reboot your pi or rh service.

1. Settings->Event Actions->On Heat Change -> Schedule Race in 20 seconds
2. Run page
3. Change Heat - Nothing. The action is still present on settings, but there is no any error message in log file about scheduling race.
4. sudo service rotorhazard restart
5. Run page->Change Heat - Race Scheduled...
6. Settings->Event Actions->Delete this Action
7. Run page->Change Heat - Race Scheduled...
8. sudo service rotorhazard restart
9. Run page->Change Heat - Nothing.

RPi 4,  RH v4.1.0-beta.4

**Comment by HazardCreative** [comment]
Fix exists on `main` and will be deployed in next beta: 035f085
