### ISSUE TITLE
New PCB Design needed

### ISSUE THREAD

**Issue by HazardCreative** [RotorHazard/RotorHazard#91]
The current D5 V2 PCB has an issue where any jumper powers all nodes. This should be corrected.

I have not personally found the all-nodes jumper to be an issue when reflashing. Should there still be one? Or just one instead of four?

A new PCB would allow us opportunity for more options:
- grounding of pins for automatic node id selection
- a jumper for selecting the low/high bank in automatic id selection
- exposing I2c so external sensors can be connected
- exposing power and gnd pads for connecting fans
- providing a VIN break point for a current sensor

What else should be included? Anything to take away?

**Comment by pulquero** [comment]
Ground pin for shielding.
Pads for a 12v regulator for LEDs.

**Comment by BoLtWD** [comment]
- If pulling #89 pads to make wiring to INA219 more easy. 
- On nodes a way to add external leds (pads) from the arduino nano for diagnostic indication.

**Comment by BoLtWD** [comment]
Not related to the PCB but something I have added

https://www.instructables.com/id/Simple-Raspberry-Pi-Shutdown-Button/

https://howchoo.com/g/ytzjyzy4m2e/build-a-simple-raspberry-pi-led-power-status-indicator

external LED as SD ACT LED 
https://www.youtube.com/watch?v=_REhMZJ8GJY

**Comment by pulquero** [comment]
5v external voltage ref for nano ADC.

**Comment by Ryanf55** [comment]
Slots for resistor divider for the voltage sensor analog input. Where are the pcb files at?

**Comment by pulquero** [comment]
I don't think I have ever been to an event with more than 6 pilots per heat, so maybe a 6 node pcb option??

**Comment by pulquero** [comment]
You can find various pcb files here
http://www.google.com/search?q=seeedstudio+delta+5

**Comment by Cerberus74** [comment]
<img width="1030" alt="PCB" src="https://user-images.githubusercontent.com/29674976/60338151-1d2e4e80-999d-11e9-972a-70a7826ba522.png">

I've made a start on a new PCB for the project. Keeping to the 100x100mm form factor. I'm no PCB wizard but I'm willing to give it a go!

**So far:**
It has power jumpers for each node (that work)
It has a jumper for the low/high node bank selection
It has hard wired node IDs. 1 to 4 or 5 to 8 depending on the high/low bank selector jumper.

**My thoughts....** 
I2C bus is a function of the Pi. If you are using a INA219 (http://tinyurl.com/y4lbfhun) for example. That 'daughterboard' would connect straight to the Pi. So I haven't added anything to the PCB for it.

You could draw your 5v for fans straight from the Pi too (as I do now). But an additional 5v header on the PCB could be added. Probably x2 as most case designs use two small Pi fans.

Current sensor, I'd say that was better accounted for in the wiring to the board? You want it in the main power feed. Adding it to the PCB could be more confusing than helpful. 

External LEDs for node diagnostics. What sort of thing are you thinking? The Nano already has an onboard LED. Can that be leveraged for a diagnostic indicator?

External SD card activity LED. Connect straight to the Pi and then present on the enclosure somewhere.

Perhaps what is actually needed is a standardised connector for the Pi gpio to bring all these connections in?

12v pad for LED's. This would mean an additional power regulator and result in the WS2812b LEDs being tethered to the timing box. As well as increasing the input voltage requirement. 5v WS2812's located away from the start gate can run on a 5v usb power bank really nicely (With wireless data connection coming soon). I don't see a lot of benefit to increasing the compolication on the nodes pcb. Along with increasing BOM and cost. 

Shutdown button and Pi status LED. These seem like an absolute must have to me. These should be wired straight to the Pi. Again I can't see a benefit of presenting this on the nodes PCB. It's doubling up the wiring.

**Changes I'm planning to make to what I have so far:**
Change to newer power regulators
Add additional +5v header pins for fans (x2?)
VBatt header pins, for voltmeter

**Comment by Ryanf55** [comment]
1. Is there a reason the i2c, 3.3, and 5v pins are not all together in a single 0.1" header instead of gaps between them? On your schematic, they are the P5,P6,P7 and P16,P17,P18. Never understood why.

1. Even if you don't want to add specific spots for some of the sensors, at least having some spare 3.3V, 5V, and i2c pads around the board would be nice. Silkscreen should be able to eliminate the confusion. I like to power the sensors off the battery supply and delta 5 pcb regulators instead of the Pi's regulators.

1. Can you add mounting holes for it to be put on standoffs from the Pi. I attached the bolt pattern. Drill 2.75mm diameter with 3mm radius circle of component clearance. I don't know how much cost that will add (if any) but it at least doesn't add wiring complexity.

![image](https://user-images.githubusercontent.com/25047695/60568133-29ae0080-9d29-11e9-887e-eacf7f667fe1.png)

**Comment by Cerberus74** [comment]
1. Nope, no real reason other than using the previous design as a jumping off point. It does give you a bit more flexibility with routing the traces to keep them seperate. I can look into grouping them as it would make the final product a bit neater.

2. Silkscreen will come for sure. It's the icing on the cake, need to bake the cake first ;) At the moment I have 2x5v 2x3.3v and 2xi2c. As per the original starting point. I'm already thinking of adding another pair of 5v for fan duties. I could probably add at least one more i2c header and 3.3v header.

3. I did consider some mounting holes to actually allow easier mounting of the PCB itself. Mounts for the pi aren't out of the question. It would have to hang below the pcb I think? the nanos and rx5808s take up all the space on top. 

Cheers for the feedback!

**Comment by Klaus-Michael** [comment]
With the latest 2.0 release we got the timestamps of the Round visible in the GUI. Unfortunately the pi does not have a RTC so the system time is wrong in situations where it is started and running whithout any internet connection.
I solved this by adding a DS3231 RTC to the i2c bus. I opened a pull request for the configuration side.
The most DS3231 boards are designed to connect directly to the GPIO pins 3.3, SDA, SCL, GPCLK0 (which is not connected) and Ground.
As SDA and SCL are already blocked by the connection to the PCB I used the connections on my PCB and soldered some wires.
On a new PCB it would be nice to get a 5 port header for a solderless installation

![image](https://user-images.githubusercontent.com/47172940/60643590-d4aae100-9e33-11e9-9ed8-bd12eb3752ed.png)

**Comment by pulquero** [comment]
Should we still be designing around Arduino Nanos, or should we be using a single ESP32 (https://github.com/realhuno/esp32_laptimer?fbclid=IwAR0T03DMYx8ZugGu3_nemLAX5phOicbsc3ybELPKjB_SWGlL_GVVH_CnXBc) or something else?

**Comment by ethomas997** [comment]
Replacing the nanos with an ESP32 is an interesting idea.  We could have a nice little 4-node board that the Pi attaches to, and an optional 4-node daughter board to get to 8 channels.  First step would be to do some prototyping and testing to make sure that it can sample the analog RSSI signals effectively.

Sparkfun has a devel board ([SparkFun ESP32 Thing](https://www.sparkfun.com/products/13907)), and I see some on eBay.

**Comment by HazardCreative** [comment]
What benefits could we expect?

**Comment by pulquero** [comment]
Easier to assemble and maintain. More ram. You could probably do away with the pi too.

**Comment by pulquero** [comment]
Consider (relatively) large 5v and gnd pad to support wiring something like a jst/xt30 for power connection to Pi. Even if still use dupont connectors at the other end, would still be beneficial as would be one less set of connectors for the current to go through.

**Comment by szafranski** [comment]
Consider using cheaper step down than pololu. Eg. This:
https://www.ebay.com/itm/DC-5-24v-to-3-3v-5V-9V-12v-3A-Adjustable-Buck-Step-down-Voltage-Regulator-Module/172825665907?hash=item283d366173:g:fa0AAOSwiYlaShLj

It has different pinout.

**Comment by szafranski** [comment]
Adding link to instructables page with "ota" updating feature. May be related to PCB design. 
https://www.instructables.com/id/RotorHazard-Updater/

**Comment by sl33pydog** [comment]
Starting to remake my attempt at pcbs.  I'm planning on making it so that you could use each board independent from each other but together they make a cool long board so that two fans cool the whole system down.  After talking to szafranski I'm adding in the uart and reset pins.  The hard part is making the node pair pcb as universal as possible and configurable.  So it's taking me a bit of time figuring out how to do it on a 2 layer board.  So far I have auto node select with upper and lower grounds for 8 node select.  Even nodes on the top and odd nodes on the bottom.  I have the reset pins for uart control in the same way.  I also have it so that you could use 3.3v for the rx5808 or vsys (which is 5v or 3.3v) for those who want to keep 5v for the Arduino but 3.3v for the RX.  And then lastly each board can fit on the other and have ground pads for multi point shielding.  Other than that I'm making it through hole mount for the RX/Arduino for however which way you want to mount it.  Then I'll start redoing the main daughter board.  Which it I have two ina219 chips with different addresses how will RH react/use that data?  Building in a hotswap circuit and think it best to show the organizer both voltages.

**Comment by szafranski** [comment]
I would assume that people allways have 2/4/6/8 nodes. No point of
designing for another configurations imo.
And remember about voltage divider for uart.

W dniu wt., 25.02.2020 o 02:27 sl33pydog <notifications@github.com>
napisał(a):

**Comment by sl33pydog** [comment]
I'm going to try for a level shifter.  It'll go well with selectable voltages.

**Comment by szafranski** [comment]
Or just a jumper header for bypassing the divider if needed

W dniu wt., 25.02.2020 o 03:32 sl33pydog <notifications@github.com>
napisał(a):

**Comment by sl33pydog** [comment]
![IMG_20200224_221915](https://user-images.githubusercontent.com/61440555/75214606-c0657c80-5753-11ea-9b19-f5565d688844.jpg)

**Comment by szafranski** [comment]
Can you post a circuit diagram for that?

**Comment by sl33pydog** [comment]
Lol if I did I couldn't sell them.

**Comment by szafranski** [comment]
I only meant this part of them. Ok ok .

W dniu wt., 25.02.2020 o 13:14 sl33pydog <notifications@github.com>
napisał(a):

**Comment by sl33pydog** [comment]
Biggest reason is that it isn't tested.  I don't want to post if I accidentally made a ground loop or something worse.  Plus you can see in that pic it still has work and missing pads to be made.

**Comment by HazardCreative** [comment]
> Lol if I did I couldn't sell them.
Just remember that the project files must be open-source if you want to use any of the RotorHazard communities to announce that you are selling them.

**Comment by sl33pydog** [comment]
Ah ok.  I'll have to think about it.  If I sell it and it's not open source I'll make sure it has no markings and isn't announced on any RH communities page.

**Comment by szafranski** [comment]
Hello. After discussion with Michael with assist from sl33pydog I designed - consider it pre-alfa version - new PCB. At least first of them.
My goals:
1. Keep existing dimensions.
2. Make use of existing recommended hardware.
3. Add an option to have a sensors attached to the board.
4. Ground auto-numbering mod embedded.
5. Have an option to use cheaper voltage converters.
6. UART programming included.
7. Option to mount RXes flat or with pins
8. Use as less cabling as possible

You can take a look here:
https://easyeda.com/join?type=project&key=21781e7b4aa81078cd3c47368c8f841d

![image](https://user-images.githubusercontent.com/23621888/75405074-d9fdf400-590c-11ea-9829-35a42255fd97.png)

**Comment by szafranski** [comment]
The alignment of the elements, silk screen etc would be improved. Why those 2x5pins connectors? To utilize "kanda" connectors and cables. The Raspberry's pinout is ideal for this. 
So:
right-low kanda - I2C and UART
left-low kanda - resets
upper left - power to second board
bottom left - I2C and UART to second board.

So it adds 4x 10-15cm flat cable - which is cheap. And clean :)

![image](https://user-images.githubusercontent.com/23621888/75405250-5abcf000-590d-11ea-81fe-988cab6049ed.png)

Write me what you think.

**Comment by szafranski** [comment]
Also added mounting holes. 
Will be added: fan-header, second board 
(boards cant be the same due to auto-numbering and uart reset pins.

**Comment by szafranski** [comment]
It maybe doable to make 1 and second PCBs identical - just with few jumper pins. I will work on that.

**Comment by szafranski** [comment]
Test

**Comment by szafranski** [comment]
Question to more experienced guys. Would you rather use PCB connected with Raspeberry just via gold pins ( no wires ) or with flex cables/cables?

**Comment by szafranski** [comment]
Ok. So right now PCB is almost in beta state :There are smd pads. When they are bridged node is connected to rst 5 insted of 1, 6 insted of 2 etc. Thanks for great idea Clayton!

Right now PCB is more suited for cable than direct connection.

![image](https://user-images.githubusercontent.com/23621888/75490510-9fe82d00-59b4-11ea-93ed-7cbec83b59b7.png)

**Comment by sl33pydog** [comment]
Looks awesome

**Comment by szafranski** [comment]
Ok, don't want to spam but iI think (as well as Clayton) that it is quite good for now. 
Included some instructions on the bottom silk screen. Take a look:

![image](https://user-images.githubusercontent.com/23621888/75508345-12bccc80-59e4-11ea-9406-a6782d87b9c4.png)

![image](https://user-images.githubusercontent.com/23621888/75508361-249e6f80-59e4-11ea-96d8-4cf0d25f5f82.png)

**Comment by szafranski** [comment]
New link:

https://easyeda.com/join?type=project&key=f95aec1e1f0d370201582586c81e3a3d

**Comment by szafranski** [comment]
Another update - for now tbh I consider this PCB ready to test.
![image](https://user-images.githubusercontent.com/23621888/75620039-f8b9f000-5b83-11ea-8b76-7f7196b41a03.png)
![image](https://user-images.githubusercontent.com/23621888/75620045-1424fb00-5b84-11ea-86f8-b6c069c92658.png)
![image](https://user-images.githubusercontent.com/23621888/75620052-269f3480-5b84-11ea-9420-62d83333adb3.png)

**Comment by szafranski** [comment]
![image](https://user-images.githubusercontent.com/23621888/75620067-4df60180-5b84-11ea-8d9c-991521915cf9.png)

**Comment by szafranski** [comment]
Main features included:
- there is only one PCB. Adjustments are done on second PCB by bridging 5 SMD pads. Clean and nice solution
- option for using 3v3 Arduinos. Not a popular solution and requires additional wiring etc but doable. 
- included UART 'mod'
- included auto-numbering 'mod'
- awesome looking RotorHazard logos
- instruction right on the bottom of the PCB
- dimensions same as previous Delta 5 PCB
- cost from JLCPCB - 2$ for 5 pcs
- schematics 100% match PCB - ease for editing and adding stuff
- additional headers for: UART, I2C, GND, BME280, INA219, Video-out (from every receiver), 5V+gnd, VIN+gnd
- mounting holes included (4 of them with ground layer exposed for easier attaching to the shielding or chassis
- dimensions and placement of the headers make using 2x5 kanda flat cables possible. also male pin headers as well as dedicated ports (photo below) can be used
- 2 flat cables are sufficient for connecting Raspberry to PCB 1 and 2 for connecting PCB 1 to PCB 2
- designed in EasyEda - can be easily converted into gerber and manufactured or shared and edited by anyone
- option for using 40 pin flat cable insted of 2x2x5 flat cables (not recommended but possible)
- optional pins marked so user won't have to make unnecessary soldering
- option for use Pololu converters as well as 3 pin ones - mounted horizontally despite concerns about the spacing at the beginning (should be tested to confirm 100%)
- spare pair of pins - one of them dedicated to use as separate back-up data LED pin 
- ability to order awesome looking white PCB :)

**Comment by szafranski** [comment]
Link: https://easyeda.com/join?type=project&key=5b77c50a4e6bcd38a2b6fcd18b36f18e

**Comment by szafranski** [comment]
![image](https://user-images.githubusercontent.com/23621888/75620300-4b48db80-5b87-11ea-8533-f7f6074d4afa.png)

**Comment by szafranski** [comment]
![image](https://user-images.githubusercontent.com/23621888/75620304-57cd3400-5b87-11ea-8632-dfe9a519d2bb.png)

**Comment by HazardCreative** [comment]
Anyone considering building this board should be sure to follow #252 as the node-numbering spec may change.

**Comment by szafranski** [comment]
I added some improvements. Arduinos 1 and 2 and 3 and 4 are evenly spaced and mounting holes are prepared for popular 3mm screws (3,1mm holes). According to auto-numbering - right now board is designed to follow "old" way of auto-numbering. Lines SCL and SDA created nice "path" for connecting pin 4 of every Arduino easily. Would be nice if that way of auto-numbering can be still available - despite adding new one to the code. Cheers

**Comment by HazardCreative** [comment]
Closing as #397 was merged.
