### ISSUE TITLE
Pilots Color Mode Can Not be Changed

### ISSUE THREAD

**Issue by L1cardo** [RotorHazard/RotorHazard#914]
**Describe the bug**
Pilots Color Mode Can Not be Changed

**To Reproduce**
1. Go to 'Settings--Pilots'
2. Change "Color Mode"

**Expected behavior**
Color mode can be changed

**Screenshots**
![recording](https://github.com/RotorHazard/RotorHazard/assets/33802186/dea2cf2b-5e31-4810-ad36-91fe35ff86f7)

**Log Dump**
[rh_logs_20240607_005456.zip](https://github.com/user-attachments/files/15661235/rh_logs_20240607_005456.zip)

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser Edge 124.0.2478.80
 - Version 4.1.0

**Comment by HazardCreative** [comment]
Thank you! Addressed in [13a807c](https://github.com/RotorHazard/RotorHazard/commit/13a807cd17b1e8b4cfdfbfc5634ab09bbef3a08e).
