### ISSUE TITLE
Nuclearhazzard Pick&Place jlcpcb

### ISSUE THREAD

**Issue by Meldinov** [RotorHazard/RotorHazard#927]
When uploading gerber, Bom and pick&place files to jlcpcb, some items are wrongly placed.
![imagen](https://github.com/RotorHazard/RotorHazard/assets/33942986/86ae055a-8290-4269-bc48-16cbf4e3e4f7)
![imagen](https://github.com/RotorHazard/RotorHazard/assets/33942986/c7bd8356-ee47-400d-8f68-9790a371f913)

**Comment by ethomas997** [comment]
@SpencerGraffunder Please note

**Comment by L1cardo** [comment]
They are not wrongly placed, try rotating the items

**Comment by klaasnicolaas** [comment]
That is purely an issue with JLCPCB, in the end it is soldered correctly by them.

**Comment by L1cardo** [comment]
> They are not wrongly placed, try rotating the items

**Rotate**

![image](https://github.com/user-attachments/assets/3f25dbb1-ac7d-45f2-944f-4dcb8ed15b46)
