### ISSUE TITLE
Database Malformed 

### ISSUE THREAD

**Issue by Theal427** [RotorHazard/RotorHazard#950]
**Describe the bug**
Database is malformed. I think I ran too many runs in one heat? I was just running and running and then it wouldn’t let me save any more runs. I did do 100 runs in one heat. How do I reset the DB? 

**To Reproduce**
1. Run 100 races in one heat. 
2. Database malformed? 

**Log Dump**
[rh_logs_20240801_175434.zip](https://github.com/user-attachments/files/16956586/rh_logs_20240801_175434.zip)

**Comment by HazardCreative** [comment]
One log entry ends with a successful write just before shutdown:
```
2024-08-01 16:53:07.683: RHData [INFO] Race added: Race 197
...
2024-08-01 16:54:59.670: __main__ [INFO] Performing system shutdown
```
And then the next run of the server throws the error the first time anything tries to write to the DB:
```
2024-08-01 17:00:21.539: RHData [INFO] Race added: Race 198
2024-08-01 17:00:21.598: RHData [ERROR] Error writing to database: (sqlite3.DatabaseError) database disk image is malformed
```

This suggests the error occurred outside RH. My recommendation would be to try with a new SD card. Let us know if that solves it.

**Comment by Theal427** [comment]
What do you mean it’s outside of RH? The SD card that’s in the Atom is the one that was shipped from Nuclear Hazard, and the system still works meaning I can still see it taking laps, I just can’t write to the DB. How do I rebuild the DB? Isn’t it all on the same SD card?

**Comment by Theal427** [comment]
That’s the latest error as I try and boot up the server. The RotorHazard Software is still working but the DB, Race results etc are all not loadable so I just need to know how I rebuild that DB. What do I have to delete or how do I rebuild it?

**Comment by Theal427** [comment]
How do I get to the SRC/Server directory? I tried pulling the SD card out and putting it into a PC but I don’t see SRC/Server or the database.db file.

**Comment by Theal427** [comment]
Also the whole unit is only a month old and ordered directly from nuclear hazard Etsy page. Is there any warranty on it if it is hardware related?

**Comment by HazardCreative** [comment]
> How do I get to the SRC/Server directory? I tried pulling the SD card out and putting it into a PC but I don’t see SRC/Server or the database.db file.

You can use SSH, plug a monitor/keyboard into the Pi directly, or open the SD card from a system that can read the linux filesystem.

>Is there any warranty on it if it is hardware related?

You'd need to discuss that with the shop.

**Comment by Theal427** [comment]
Thank you. I Ssh’d in to the server and deleted the database file and now it is working as expected. still not sure what caused it to become deformed but if it happens again I will let you know and submit the new log files. For now everything is back to working as it should.

**Comment by HazardCreative** [comment]
Closing this issue as completed. Please reopen as you've said (including log dump) if it reoccurs.
