### ISSUE TITLE
No matching distribution found for requirements.txt requirement Flask==3.0.*

### ISSUE THREAD

**Issue by BoLtWD** [RotorHazard/RotorHazard#951]
I am upgrading RH and have not done so from RELEASE_VERSION = "3.1.2-dev.1
I have Python 3.9.4
During running requirements.txt I get "Could not find a version that satisfies the requirement Flask==3.0.*" for line 2
No matching distribution found

Can you advise

**Comment by klaasnicolaas** [comment]
Which python version does it return when you do `python --version` in the terminal?

**Comment by BoLtWD** [comment]
Python 3.9.4

**Comment by klaasnicolaas** [comment]
Are you using a venv to install all pypi packages? I suspect that you are using a different python version during installation, one that is lower than what Flask 3.x requires as a minimum.

./Klaas

**Comment by BoLtWD** [comment]
Here's what I did to install Python 3.9.4 on my rpi:
-------------------------------------------------------
Copy paist enter
sudo apt-get update  
 
Copy paist enter
sudo apt-get install -y build-essential tk-dev libncurses5-dev libncursesw5-dev libreadline6-dev libdb5.3-dev libgdbm-dev libsqlite3-dev libssl-dev libbz2-dev libexpat1-dev liblzma-dev zlib1g-dev libffi-dev

Copy paist enter
wget https://www.python.org/ftp/python/3.9.4/Python-3.9.4.tgz

Copy paist enter
sudo tar zxf Python-3.9.4.tgz  

Copy paist enter
cd Python-3.9.4

Copy paist enter
sudo ./configure --enable-optimizations

Copy paist enter
sudo make -j 4

Copy paist enter
sudo make altinstall

Copy paist enter
python3.9 -V

Copy paist enter
echo "alias python=/usr/local/bin/python3.9" >> ~/.bashrc

Copy paist enter
source ~/.bashrc

To check version Copy paist enter
python -V

-------------------------------------------------------
Is this correct

**Comment by HazardCreative** [comment]
The RH version you had installed prior is from 2022. Trying to nail down the specifics of why your OS and Python/Pip can't find the newer Flask package is likely to take considerable time. My recommendation would be to just start your SD card over from scratch. That will bring you up to date with other recent improvements such as setting up a virtual environment, and will most likely take less time.

**Comment by BoLtWD** [comment]
Ok and thank you, will look at that
