### ISSUE TITLE
IMDTabler not showing IMD rating

### ISSUE THREAD

**Issue by BoLtWD** [RotorHazard/RotorHazard#952]
IMDTabler not showing IMD rating

Version: 4.1.1
Server API: 44
Node API: 35
Node Version: 1.1.5

Selecting IMDTabler within the menu then enter frequencies
Pressing view button

You can watch the loading flash-up disappear without showing the IMD rating.
This is the same problem if the page is used on other operating systems, as well as browsers such as Chrome, Opera, and Firefox.

![image](https://github.com/user-attachments/assets/e71e7dc3-a97b-4f5a-8040-caf6d1c02926)

**Comment by ethomas997** [comment]
Please generate a ".zip" file using the "Download Logs" button (in Settings | System) and post it here.  Also, please post the response from running the following command on the Raspberry Pi in your timer:
`java -version`

**Comment by BoLtWD** [comment]
Running above I got  java -version bash: java: command not found
I then input the command sudo apt install default-jdk
After this, I got the IMDTabler showing IMD rating

I think I had no Java installed, I followed the guide Software Setup.md but missed the text to install Java

[rh_20240916_193240.zip](https://github.com/user-attachments/files/17018218/rh_20240916_193240.zip)

I have attached log however with your help got to ground roots

Thank you
