### ISSUE TITLE
Pilots not starting in a heat are not given a position

### ISSUE THREAD

**Issue by FiorixF1** [RotorHazard/RotorHazard#956]
**Describe the bug**
When simulating the execution of a heat with 4 pilots, if one pilot does not start (not even reaching the hole shot), no position is given to that pilot in the leaderboard of the heat.
If the heat is a round of a winner bracket in a double elimination sequence, this pilot is not seeded in the subsequent heat of the loser bracket, as if the pilot magically disappeared from the race.
This phenomenon does not cause apparent problems if it happens in a loser bracket, but since the pilot is not ranked, it can cause problems to external plugins used for ranking since they expect 4 pilots in the leaderboard of each heat.

**To Reproduce**
1. Go to Format > Generator and use generator "Regulation bracket, double elimination" with option "MultiGP, 4-up, 16-pilot" to generate a class with double elimination format.
2. Go to Run and simulate Race 1 with only three pilots starting. The fourth pilot should not even reach the hole shot.
3. Continue to simulate races upon reaching Race 5.
4. When reaching Race 5, the popup window notifying about seeded pilots will warn you that there is an empty slot.

**Expected behavior**
Race 5 should be correctly seeded with 4 pilots: the 3rd and 4th ranked in Race 1 and the 3rd and 4th ranked in Race 2.

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser: Firefox
 - Version: 4.2.0-beta.1

**Comment by YegorYegor** [comment]
Confirm, got this problem a year ago I guess. We notice that one pilot doesn't fly before final bracket:(

**Comment by HazardCreative** [comment]
Thanks for the report.
Yes, the results processor got some recent updates, so this should already be resolved.
