### ISSUE TITLE
LED panel is not showing RSSI

### ISSUE THREAD

**Issue by BoLtWD** [RotorHazard/RotorHazard#959]
When you select either RSSI (all) or (enabled) from the LED control menu and press Go nothing is displayed.
All other LED events work, even if a quad passes the gate with RSSI enabled still the display shows nothing.
[rh_logs_20240928_212002.zip](https://github.com/user-attachments/files/17176203/rh_logs_20240928_212002.zip)

RH
Version: 4.1.1
Server API: 44
Node API: 35
Node Version: 1.1.5

Windows 11
Chrome
Opera
Firefox

**Comment by HazardCreative** [comment]
My LED panel has been broken for a few months. Lucky for you, the parts for it arrived a few days ago.

**Comment by BoLtWD** [comment]
I sandwiched mine between two pieces of perspex so it is water and quad-crashing-into-it resistant; sometimes they like using it as a target LOL.

**Comment by BoLtWD** [comment]
Sorry, I wanted to know whether an issue had been detected or if this was anything on my end. 
If so, could you please advise?

**Comment by HazardCreative** [comment]
Yes, there was an issue. You can see the close message references a commit that has the fix.
