### ISSUE TITLE
Action announcements for next heat could be optimized

### ISSUE THREAD

**Issue by SentinelFour** [RotorHazard/RotorHazard#968]
**Confirm the issue is with RotorHazard and not a plugin**
Disable all 3rd party plugins and attempt to reproduce the problem. If the problem goes away, contact the plugin's author instead of submitting an issue here.
Definitely a feature of the RotorHazard software :)

**Describe the bug**
I like to use the action to automatically call out the next heat. When I use the new round grouping feature the next heat is called like that "Next Round X slash heat Y.... (pause)... Next none". It is a bit odd. It does what it is supposed to but I think the announcement could be optimized - properly with just the heat number. Also the "next none" at the end sounds like some artifact.

**To Reproduce**
1. Create a class and use the new round grouping feature. 
2. Create one or more heats.
3. Create an action that is triggered when the next heat is selected (next %HEAT%)
4. Start and stop a heat; go to the next heat.
5. The action is triggered and the announcement is called out.

**Expected behavior**
I would expect that it only calls out the next round or heat number. I think the pilots do not need to know the round in which we are (can be looked up). In particular the second part "next none" seems to be a bug and should be removed. If the round and heat number should be part of the announcement, the / ("slash") call out should be prevented.

**Screenshots**
Not applicable but a screenshot of my settings can be provided upon request.

**Log Dump**
Not required but can be provided upon request.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 130.0

**Smartphone (please complete the following information):**
Not applicable, was not used

**Additional context**
Nope, nothing else.

**Comment by ethomas997** [comment]
Fixed by #969 and #970
