### ISSUE TITLE
missing get_catch_history method

### ISSUE THREAD

**Issue by pulquero** [RotorHazard/RotorHazard#98]
on_recover_pass in server.py makes a call to get_catch_history, which doesn't exist.

**Comment by HazardCreative** [comment]
Pass recovery needs to be re-implemented. It was based on an earlier
revision of history code that is no longer part of the node. We have enough
data in the new history to add it back in, but it hasn't been written in
yet.

**Comment by HazardCreative** [comment]
Temporarily fixed in 01bd274, but the real long term fix is #101
